### ISSUE TITLE
PyPANDA Panda.hook2/_hook_mem exception handling

### ISSUE THREAD

**Issue by pcworld** [panda-re/panda#1009]
On 27eb888ce2235debe4e7032a84ccc15d4eebde8a, Panda.hook2 and Panda._hook_mem use these FFI callbacks:
```py
@hook_cb_type # Make CFFI know it's a callback. Different from _generated_callback for some reason?
def wrapper(*args, **kw):
    return fun(*args, **kw)
```
and
```py
@mem_hook_cb_type # Make CFFI know it's a callback. Different from _generated_callback for some reason?
def wrapper(*args, **kw):
    return fun(*args, **kw)
```

Other similar FFI callbacks have special handling for exceptions, for example in Panda.hook:
```py
@hook_cb_type # Make CFFI know it's a callback. Different from _generated_callback for some reason?
def wrapper(*args, **kw):
    try:
        r = fun(*args, **kw)
        #assert(isinstance(r, int)), "Invalid return type?"
        return r
    except Exception as e:
        # exceptions wont work in our thread. Therefore we print it here and then throw it after the
        # machine exits.
        self.hook_exit_exception = e
        self.end_analysis()
        # this works in all current callback cases. CFFI auto-converts to void, bool, int, and int32_t
        return 0
```

I wonder whether Panda.hook2 and Panda._hook_mem would also need special exception handling.
If this is the case, maybe these wrapper functions should be refactored into one separate function to avoid such inconsistencies in the future.

**Comment by lacraig2** [comment]
oh yeah. There should definitely be a single wrapper function for this type of callback. That's very reusable code.

**Comment by pcworld** [comment]
@lacraig2 Do you still intend to fix this? Otherwise, maybe unassign & reopen.

**Comment by lacraig2** [comment]
Sorry about the delay. Take a look at the PR. It's a broader fix for a bunch of callback-type issues that you might see.
