### ISSUE TITLE
rrshare.org not reachable

### ISSUE THREAD

**Issue by loverics** [panda-re/panda#1012]
Hi! I've been trying to get to rrshare.org but can't connect. Specifically I tried to browse to http://www.rrshare.org/detail/38. Is there an updated fqdn?

**Comment by irwincong** [comment]
duplicates #430

**Comment by AndrewFasano** [comment]
I know that webserver is gone and I believe that dataset may have been lost, but @moyix would know best.

**Comment by AndrewFasano** [comment]
(Closing as a duplicate)
