### ISSUE TITLE
GitHub publish_docker.yml workflow broken

### ISSUE THREAD

**Issue by pcworld** [panda-re/panda#1020]
[Fails with](https://github.com/panda-re/panda/actions/runs/896627394):

> The workflow is not valid. .github/workflows/publish_docker.yml (Line: 36, Col: 12): Unexpected symbol: 'GITHUB_REF##\*/'. Located at position 1 within expression: GITHUB_REF##\*/ .github/workflows/publish_docker.yml (Line: 40, Col: 12): Unexpected symbol: 'GITHUB_REF##\*/'. Located at position 1 within expression: GITHUB_REF##\*/

Regression probably introduced in fca96b61d61fe9b26999f60d377a20d470807581

**Comment by AndrewFasano** [comment]
Fixed - thanks for pointing it out
