### ISSUE TITLE
PyPanda: Question regarding retrieving all tainted instructions

### ISSUE THREAD

**Issue by narceritor** [panda-re/panda#1035]
Hello,
I'm trying to retrieve ALL tainted instructions with a taint source being a file. My script runs a replay of a recording.
Tainting the read file in memory is no problem, but using ppp `on_taint_change` gives me headaches. 

Question: Is `on_taint_change` also triggered when taint is being propagated from register to register? Like for instance in a `MOV RAX, RCX` instruction, with RAX containing tainted data. It does not seem like it. 

I get some behaviour that I do not understand. When i print out the current PC from within the function that handles `on_taint_change`, every such printed PC points to the beginning of a basic block. This behaviour makes it very hard to understand in which cases `on_taint_change` is being triggered, when looking at the corresponding README.md. I would have assumed that `on_taint_change` is being be triggered whenever the corresponding instruction that actually propagates taint is executed. 

Also, whenever PCs are printed in this way, they will be printed multiple times in a row.

Thank you

**Comment by AndrewFasano** [comment]
I think what you might need is to enable panda's precise PC tracking. By default, qemu only updates the PC after each block finishes executing. For PANDA you can change this with a call to [panda.enable_precise_pc()](https://docs.panda.re/panda.html#pandare.panda.Panda.enable_precise_pc) and then you can get the pc with `cpu.env_ptr.panda_guest_pc` (or `panda.current_pc(cpu)` is probably the same thing).

The `on_taint_change` callback only fires when taint changes, not when it propagates (there's another callback, `on_taint_propagate` from #885 for that).

I hope that helps!

**Comment by narceritor** [comment]
Thanks for the reply. 

`panda.enable_precise_pc()` does neither affect `panda.current_pc(cpu)` nor `cpu.panda_guest_pc` (`cpu.env_ptr.panda_guest_pc` does not work, since `env_ptr` is a `CPUX86State` which does not have a field `panda_guest_pc`. `cpu` which is a `CPUState` struct, however, does have this field).

I have both enabled precise pc globally and from within the handling function. This does not change the output.

I derive the cpu from a call to `panda.get_cpu()`. Is this the right way to do it? (The doc says "This function returns first_cpu CPUState object from QEMU. XXX: You rarely want this")

**Comment by AndrewFasano** [comment]
Hm, that's unexpected. You might need to call panda.enable_precise_pc() sometime before calling `panda.run()` or `panda.run_replay()` but I'm not positive.

Can you post the script you're using? I might be able to help from that (even without a recording). 

Most callbacks give you a CPU object but I guess `on_taint_change` doesn't so that's a fine way to get a handle to the CPU object.

**Comment by narceritor** [comment]
I'm sorry. This was my mistake. I diffed the wrong files. Enabling precise pc and and working with `cpu.panda_guest_pc` (not `panda.current_pc(cpu)`) does its job. Thank you!

**Comment by AndrewFasano** [comment]
Glad to hear that it worked out!
