### ISSUE TITLE
Should after_insn_translate callback pass original pc?

### ISSUE THREAD

**Issue by pcworld** [panda-re/panda#1041]
The `after_insn_translate` callback passes the program counter of the instruction *after* the instruction in question. As the return value of that callback determines whether the previous instruction can later be hooked, that information does not seem to be too useful; what is more useful would be the address of the previous instruction (e.g., to disassemble it).

Currently, this can be worked around by *also* subscribing to `insn_translate` and saving the program counter there. However, this feels a bit cumbersome.

I locally use a patch with a modified callback signature:
```diff
-    bool (*after_insn_translate)(CPUState *env, target_ptr_t pc);
+    bool (*after_insn_translate)(CPUState *env, target_ptr_t pc, target_ptr_t previous_pc);
``` 

Before I go through the trouble of finishing this patch and adapting it to all supported architectures, would you even accept such a patch, given that it interferes with backwards compatibility?

What might be more useful than passing previous_pc might be to pass something like x86's DisasContext (which also includes the previous pc), however it appears that this struct is architecture dependent in qemu, so not sure if making this part of the callback would be in line with Panda's philosophy.

**Comment by AndrewFasano** [comment]
I think you're right, it would certainly be useful to have the prior PC available here. Looking at `after_block_translate` and `after_block_exec`, those both pass a reference to the prior block, not the next one. So, to be more consistent I think we should pass the prior PC here. If you think it would be useful to also pass the next PC (maybe as the 3rd argument), I'm not opposed, but maybe a better fix is to just change the pc arg to contain the prior pc.

As for passing the raw `DisasContext` object, it's not a bad idea idea, but personally, I'd like to avoid it. If there was a union of all the various structures like that for each architecture that we could use, it would fit within the general callback philosophy. But I'm hoping to eventually get PANDA callbacks and plugins to work without direct access to any QEMU datatypes and adding a new type of structure would cause some head. That way we could upgrade PANDA to a new QEMU version and maintain API compatibility. Maybe it's too much work, but I did try starting it on the various `panda-apiX` branches.

**Comment by AndrewFasano** [comment]
As for breaking backwards compatibility, I guess it would be nice if we just changed the value passed and kept the signature the same. I forget the exact rules we set up with versioning, but I think we can make that sort of change when we bump the minor version number but if we change the signature it would have to wait until the next major release to get the change onto the stable branch.

**Comment by pcworld** [comment]
Still relevant, may post PR or further discussion later. (Posting to remove the no-issue-activity tag.)
