### ISSUE TITLE
Integrate new Windows introspection library

### ISSUE THREAD

**Issue by rjwhelan** [panda-re/panda#1085]
We have a new Windows introspection library we'd like to integrate.  This issue will track development.

The goal for the initial PR is to not break existing plugins, but this will leave PANDA with multiple introspection approaches.  A future issue will address changes required to consolidate to a single introspection library.

**Comment by AndrewFasano** [comment]
The Windows introspection code is split over a few places. I don't know anything about it, but we currently have:
* https://github.com/panda-re/wintrospection (out-of-repo, most recently updated, but incomplete?)
* https://github.com/panda-re/panda/tree/dev/panda/plugins/wintrospection (in-repo)
* https://github.com/panda-re/panda/tree/dev/panda/plugins/win2000x86intro
* https://github.com/panda-re/panda/tree/dev/panda/plugins/win7x86intro
* https://github.com/panda-re/panda/tree/dev/panda/plugins/winxpx86intro

Not sure how your library is designed, but it would be nice if we ended with the code consolidated into a single repo or plugin.

Not sure if your introspection supports Windows 10 - I've heard rumors that it's possible to get Win 10 booting under PANDA. If you're interested in that OS it would be great to get some docs describing how to run it. Or we could just note that as a reason to eventually tackle #570.

**Comment by Ben-Dumas** [comment]
This is being finished up, PR in the next couple days.

**Comment by Ben-Dumas** [comment]
Merged. Now requires the user to install https://github.com/panda-re/libosi. We should think of a way to keep PANDA versions in sync with libosi versions if more development happens on libosi (e.g., "libosi v0.1.0 detected, but >v0.2.0 is required"). For now, though, there shouldn't be many (any) changes to libosi.
