### ISSUE TITLE
Integrate new recording format

### ISSUE THREAD

**Issue by rjwhelan** [panda-re/panda#1087]
We have a new RR format we'd like to integrate. This issue will track development.

- Format is known as RR2
- Consists of a compressed file that contains:
    - Snapshot
    - Nondet log
    - Capture command
    - Magic file
    - SHA1 hash
    - Metadata file

To accompany this, there should probably be a command line option to use the old format vs. the new format.  It may also be helpful to include utilities/documentation for converting between formats.

Additionally, we propose the next major release of PANDA only supports this version.

Related to #339.

**Comment by AndrewFasano** [comment]
Supersedes #625.

+1 for saving this until the next major version release - I think that could come out as early as this winter according to our rules.

Is the capture command just human-readable text? It would be nice to have a machine-readable field for the QEMU/panda machine type (the `-M` flag) which mostly matters for non-x86 systems.

**Comment by rjwhelan** [comment]
The capture command is a human-readable copy of the command.  The metadata file could be used to store anything useful in JSON format.  We currently use it to store the memory size, OS profile, the image the recording was taken on, among other things.

**Comment by Ben-Dumas** [comment]
This is currently being worked on by zacogen and is in progress.

**Comment by lacraig2** [comment]
Finished with merge by #1194!
