### ISSUE TITLE
Generic Images Everywhere

### ISSUE THREAD

**Issue by AndrewFasano** [panda-re/panda#1122]
Right now, only PyPANDA supports loading "generic images" which are a mapping of a simple name (e.g., x86) to some files hosted at panda.re combined with OSI profiles and standard command line options. When a generic image is requested, the required files are downloaded if they're not already present in `~/.panda` and then PANDA's arguments are automatically configured for that image.

It would be great to move this logic out of PyPANDA's [qcows.py](https://github.com/panda-re/panda/blob/dev/panda/python/core/pandare/qcows.py) and into a standardized format. Then we could add support for generic images on the command line and run commands like `panda-system-[arch] -generic x86 -loadvm root` which would load the image and properly set the OSI profile up. This could then also be used from rust.

This idea comes from @jamcleod and I believe he's working on implementing a standardized config file for generic images and then adding this into rust - not sure if he's going to tackle the CLI use case as well.

**Comment by jamcleod** [comment]
Relevant panda-rs issue: https://github.com/panda-re/panda-rs/issues/20

The current plan is just to use the same structure as pypanda's existing code but have it be in a JSON instead of a python literal, but I'm open to other ideas.

**Comment by AndrewFasano** [comment]
Do you think it would be possible/better to extend an existing VM metadata format instead of making a new one? In particular, libvirt and vagrant both have such formats defined so maybe we could pick one and add set some custom fields with panda-specific data.

(Credit for this idea belongs to Andre who suggested it in slack)
