### ISSUE TITLE
panda-system-aarch64: Not a migration stream

### ISSUE THREAD

**Issue by Rubonnek** [panda-re/panda#1134]
Using the Docker `pandare/panda:latest` image as of today, I'm attempting to save a recording with:

```
panda-system-aarch64 \
	-machine virt-2.9 \
	-nographic \
	-serial stdio \
	-m 1G \
	-cpu cortex-a57 \
	-drive file=qemu_aarch64.qcow,if=virtio \
	-drive file=qemu_aarch64-flash0.qcow,if=pflash,readonly=on \
	-monitor telnet:0.0.0.0:55555,server,nowait \
	;
```

But when adding `-replay foo` to the above command I'm getting the following `Not a migration stream` error:

```
root@112edd58e49e:/tmp/ramdisk/qemu_aarch64# bash replay_test.sh 
loading snapshot
panda-system-aarch64: Not a migration stream
Failed to load vmstate
Failed to start replay
```

I'm not quite sure how to debug this.

**Comment by Rubonnek** [comment]
Seems this issue might be related to #843.

**Comment by Rubonnek** [comment]
So it seems using the `qcow2` format, and stop the VM before starting to record, and at the end of the recording seems to help.
I tried that and this time the replay attempted to start but now I'm hitting a failed assertion in `rr_log.c:978`:

```
root@28e48f286a70:/tmp/ramdisk/qemu_aarch64# bash boot-vm.sh
loading snapshot
... done.
opening nondet log for read :   ./replaytest-rr-nondet.log
RR rr_assertion `current_item' failed at /panda/panda/src/rr/rr_log.c:978
Current log point:
{guest_instr_count=3864}
Next log entry type: RR_INPUT_8
Current replay point:
{guest_instr_count=1879}
boot-vm.sh: line 15:    67 Aborted                 (core dumped) panda-system-aarch64 -replay replaytest -machine virt-2.9 -nographic -m 1G -cpu cortex-a57 -drive file=qemu_aarch64.qcow2,format=qcow2,if=virtio -drive file=qemu_aarch64-flash0.qcow2,format=qcow2,if=pflash,readonly=on -monitor telnet:0.0.0.0:55555,server,nowait
```

**Comment by AndrewFasano** [comment]
I don't think PANDA's record replay system has ever been tested on aarch64 - it should probably raise a fatal error when you try to do it instead of giving you some subtle failure like this. We've only ever analyzed aarch64 guests live before.

The record and replay system does support arm32 so it might not be too much work to expand it to work on aarch64 if you're interested in trying to add it. But the record and replay code in PANDA is pretty complex so it might be a significant undertaking.

**Comment by Rubonnek** [comment]
At the moment I only need arm32 -- I don't think I'll need 64-bit ARM soon, but if I ever do I'll reach out.

Thanks for the information!

**Comment by AndrewFasano** [comment]
If you want arm32, then you should try using `panda-system-arm` instead of `panda-system-aarch64`
