### ISSUE TITLE
pandare.qcows output path wrong in docker container

### ISSUE THREAD

**Issue by AndrewFasano** [panda-re/panda#1174]
Running
```
python -m pandare.qcows x86_64
```

in the docker container will (after downloading the generic qcow) print an absolute path to panda-system-x86_64 which is wrong.

**Comment by lacraig2** [comment]
Is it wrong for it to print the path or is the path wrong?

**Comment by AndrewFasano** [comment]
Sorry, though I replied sooner. It prints an invalid path. I'm not sure if the path is actually wrong or something is wrong with the installer. Starting to think the latter.

```
root@f7ffadbe9d31:/# python -m pandare.qcows x86_64
[...]
Run panda for x86_64 with:
/usr/local/lib/python3.8/dist-packages/pandare/data/x86_64-softmmu/panda-system-x86_64 -L /usr/local/lib/python3.8/dist-packages/pandare/data/pc-bios /root/.panda/bionic-server-cloudimg-amd64-noaslr-nokaslr.qcow2 -m 1024 -nographic -loadvm root
```

The directory `/usr/local/lib/python3.8/dist-packages/pandare/data/[arch]-softmmu/` is populated by pypanda but it only has libpanda-[arch].so, llvm helpers, and the plugins, no `panda-system-[arch]` binary.

**Comment by AndrewFasano** [comment]
The issue is that we have a python install of PyPANDA in the usr local lib directory, but PANDA is installed system wide and we weren't distinguishing between when we needed to find libpanda and when we wanted to find a panda binary (which requires searching the $PATH as well)
