### ISSUE TITLE
panda_plugins/win7proc

### ISSUE THREAD

**Issue by xri-wen** [panda-re/panda#1183]
[panda_plugins](https://github.com/panda-re/panda/tree/974ecd18c7ce12ecfe8f974490a4b1c3721383c8/qemu/panda_plugins)/win7proc
Does the current version have a plugin with the same function like this one?

**Comment by lacraig2** [comment]
I think you're looking for the [wintrospection](https://github.com/panda-re/panda/tree/dev/panda/plugins/wintrospection) plugin.

**Comment by xri-wen** [comment]
Thanks! I got it! another question!
panda1/qemu/scripts/procstory.py
Does the current version have a .py with the same function like this one?
