### ISSUE TITLE
target os name not working

### ISSUE THREAD

**Issue by LauraLMann** [panda-re/panda#1203]
I have tried a simple test with the new PANDA that uses libosi for the Windows OSI.  But PANDA does not recognize my target OS, even though I'm using one named in the osi README.md file.  What's up?
Following is my command line, and what I get back:
<redacted>/panda-express/home-panda/build-panda/i386-softmmu/panda-system-i386 -m 4G -replay testrecording -panda osi -panda asidstory:width=132 -os windows-32-7
PANDA[asidstory]:adding argument width=132.
panda-system-i386: <redacted>/panda-express/home-panda/panda/panda/src/common.c:198: panda_set_os_name: Assertion `os_supported' failed.
Aborted (core dumped)

I could replay this recording with asidstory and OSI before the libosi changes.  Did someone remove support for Windows 7 and neglect to update the README???

**Comment by Ben-Dumas** [comment]
It is now split into windows-32-7sp0 and windows-32-7sp1 (64 bit works too!)

I made the changes, but I did forget the README, apologizes. There are minor changes in the structures between service packs, but `sp1` should work for most things!

**Comment by AndrewFasano** [comment]
@Ben-Dumas would you be able to update the readme and then we can close this issue? I'd do it myself but I don't really understand what changed.

**Comment by Ben-Dumas** [comment]
https://github.com/panda-re/panda/pull/1209 is what _I think_ was being referred to. @LauraLMann let me know if there are more confusing places! Happy to change

**Comment by LauraLMann** [comment]
Yes @Ben-Dumas , the changes made in #1209 include the fixes to the erroneous documentation I was referring to.
Thank you for making the documentation match the code!
