### ISSUE TITLE
panda-system-arm not support arm vexpress-a9 

### ISSUE THREAD

**Issue by fr0zenrain** [panda-re/panda#1215]
panda-system-arm  -M vexpress-a9 -kernel vmlinuz-3.2.0-4-vexpress -initrd nitrd.img-3.2.0-4-vexpress -drive if=sd,file=debian_wheezy_armhf_standard.qcow2 -append "root=/dev/mmcblk0p2" 
audio: Could not init `oss' audio driver
VNC server running on 127.0.0.1:5900

image download from here:
https://people.debian.org/~aurel32/qemu/armhf/
qemu-system-arm running ok

**Comment by AndrewFasano** [comment]
PANDA does (should) support the vexpress-a9 board - it looks like that output there is fine, you're getting a warning about the audio driver but then PANDA is starting a VNC server that you could connect to. If you pass the argument `-nographic` then you should see output on the console

**Comment by fr0zenrain** [comment]
i'm sorry,you are right.thanks!
