### ISSUE TITLE
Assertion error while using file_taint plugin

### ISSUE THREAD

**Issue by vivek425ster** [panda-re/panda#123]
Command which i am using to run replay downloaded from rrshare.org `deb32_simplecpp` : ```./qemu/i386-softmmu/qemu-system-i386 -m 512 -replay rec_taint -panda osi -panda osi_linux:kconf_group=mykernelinfo,kconf_file=~/panda/kernelinfo.conf -panda syscalls2:profile=linux_x86 -panda file_taint:filename=license.txt,notaint```

I am getting following error when i try to run the above command
```
Adding PANDA arg file_taint:filename=license.txt.
Adding PANDA arg file_taint:notaint.
adding /home/vivekjain/panda/qemu/i386-softmmu/panda_plugins/panda_file_taint.so to panda_plugin_files 3
loading /home/vivekjain/panda/qemu/i386-softmmu/panda_plugins/panda_osi.so
qemu-system-i386: os_intro.c:151: init_plugin: Assertion `!(panda_os_type == OST_UNKNOWN)' failed.
Aborted
```

Thanks

**Comment by m000** [comment]
Apparently the command on rrshare.org is out of date. You need to supply an
appropriate "-os" option in more recent versions of PANDA.

The string has 3 parts, delimited with dashes: <os type>-<os bits>-<os
details>.
These parts are used by the osi module to load and initialize the
os-specific plugin, so in the end you have a more compact and readable
command line.

E.g., if your kernelinfo.conf is in the default location, you don't need to
add any configuration for osi_linux.
Instead you supply something like this: -os linux-32-debian-3.2.81-486

This will result in osi_linux trying to load configuration group
[debian-3.2.81-486:32] from the default kernelinfo.conf file.

M.

2016-11-12 7:07 GMT+01:00 vivek425ster <notifications@github.com>:
