### ISSUE TITLE
llvm 3.3

### ISSUE THREAD

**Issue by greyltc** [panda-re/panda#125]
This seems like a super cool project.
I want to package it for Arch Linux.

I read on another issue here that llvm version 3.3 is a hard requirement right now. That is from 2013. Arch has many strengths, but using old versions of packages is not one of them.

Is there any plan on modernizing this project so that it can compile with a more recent version of llvm?

**Comment by moyix** [comment]
Unfortunately, LLVM 3.3 is the last version of LLVM that included the JIT we depend on. It is possible that with the newer ORC JIT we might be able to update things to the newest version of LLVM, but it looks like a fairly significant bit of re-engineering and is unlikely to happen anytime soon, unfortunately.
