### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by DA25914** [panda-re/panda#128]
Hey, 
I am having trouble building this project. It seems to be missing a few files specifically the capstone.h file.

>/Documents/PANDA/repo/panda/panda/plugins/callstack_instr/callstack_instr.cpp:24:31: fatal error: capstone/capstone.h: No such file or directory
 #include <capstone/capstone.h>
                               ^
compilation terminated.
make[2]: *** [panda/plugins/callstack_instr/callstack_instr.o] Error 1
make[1]: *** [plugin-callstack_instr] Error 2
make: *** [subdir-i386-softmmu] Error 2

I am running the panda/script/install_ubuntu.sh script on Ubuntu 14.04. I am pretty sure I have all the required libraries.  What am I missing?

Regards,

**Comment by DA25914** [comment]
Ah there are two branches of this project. I should have been using the panda1 branch not the master branch. My fault.

**Comment by phulin** [comment]
I wouldn't recommend using the panda1 branch. No development is happening on that branch and replays you produce will be incompatible with panda2. The install_ubuntu.sh script should have installed libcapstone-dev. If it didn't, let us know.
