### ISSUE TITLE
 which version of libdwarf panda2 need

### ISSUE THREAD

**Issue by fr0zenrain** [panda-re/panda#129]
i can't build panda  on ubuntu ,because pri_dwarf plugin error, which libdwarf version panda need ,any url?thx

**Comment by fr0zenrain** [comment]
sorry, may be i get it  from panda/scripts/install_ubuntu.sh.

**Comment by phulin** [comment]
Yep, that's right. The install script should have the correct package versions on 14.04 and 16.04.
