### ISSUE TITLE
race condition in python callback function?

### ISSUE THREAD

**Issue by ChipMonto** [panda-re/panda#1294]
Hi, 
I'm having issues using a function adapted from one of the examples, specifically the virt_mem_after_write() from extract_memstring.py. I'm getting some strange behavior and I'd like to understand what I'm doing wrong.
I'm running a MIPS binary so recording is not available, hence I had to adapt my script to run as follows (I'm using the generic MIPS image):
1. create panda() object
2. run my binary in a function decorated with @panda.queue_blocking using run_serial_cmd(). Just before running my binary, I run enable_memcb() to enable the callbacks.
3. I define two hooking functions using @panda.ppp and syscalls2 to intercept calls to read() and open() by the binary.
4. then I run panda.run() 
Most of the time I get an error from python from line when join() is called, complaining that string_buffer is not defined, even though I leave the 'global string_buffer' declaration at the beginning of the callback, exactly like in the example.
```
# python3 panda_just_callback.py 
using generic mips
os_name=[linux-32-debian:3.2.0-4-4kc-malta]
PANDA[core]:os_familyno=2 bits=32 os_details=debian:3.2.0-4-4kc-malta
[PYPANDA] Panda args: [/usr/local/lib/python3.8/dist-packages/pandare/data/mips-softmmu/libpanda-mips.so -L /usr/local/lib/python3.8/dist-packages/pandare/data/pc-bios /root/.panda/debian_7.3_mips.qcow -M malta -kernel /root/.panda/vmlinux-3.2.0-4-4kc-malta -append root=/dev/sda1 -nographic -m 1g -serial unix:/tmp/pypanda_s3nyry076,server,nowait -monitor unix:/tmp/pypanda_m725njsta,server,nowait]
Linux debian-mips 3.2.0-4-4kc-malta #1 Debian 3.2.51-1 mips GNU/Linux
Traceback (most recent call last):
  File "panda_just_callback.py", line 35, in <module>
    panda.run()
  File "/usr/local/lib/python3.8/dist-packages/pandare/panda.py", line 518, in run
    raise saved_exception
  File "/usr/local/lib/python3.8/dist-packages/pandare/panda.py", line 2613, in _run_and_catch
    r = fun(*args, **kwargs)
  File "panda_just_callback.py", line 24, in virt_mem_after_write
    string_buffer += "".join([x for x in py_str if x in ascii_letters or x in [' ', '\n']])
NameError: name 'string_buffer' is not defined
```

That seems to be a race condition, because if I run the script multiple times, eventually (but not often) it runs :-| 
I've tried multiple combinations of callbacks and plugins - attached are three scripts that all exhibit the same behavior.
I'm using the docker image on a Ubuntu 22.10 host system.
What am I doing wrong? :)
[scripts.tar.gz](https://github.com/panda-re/panda/files/11055948/scripts.tar.gz)

**Comment by AndrewFasano** [comment]
Here's the contents of scripts/1.py:
```
from pandare import Panda
from string import ascii_letters


panda = Panda(generic='mips') # Create an instance of panda

@panda.queue_blocking
def run_cmd():
    panda.revert_sync("root")
    print(panda.run_serial_cmd("uname -a"))
    panda.enable_memcb()
    print(panda.run_serial_cmd("ls -la /"))
    panda.stop_run()

@panda.cb_virt_mem_after_write
def virt_mem_after_write(cpu, pc, addr, size, buf):
    global string_buffer
    try:
        py_str = panda.virtual_memory_read(cpu, addr, size, fmt='str').decode("utf-8", "strict")
    except UnicodeDecodeError:
        string_buffer = ""
        return

    string_buffer += "".join([x for x in py_str if x in ascii_letters or x in [' ', '\n']])

    if len(string_buffer) > 30:
        print(f'\n[+] mem_write: "{string_buffer}"')
        string_buffer = ""

    if len(string_buffer) < size/2:
        string_buffer = ""

    return

panda.run()
print("Finished. ")
```

Seems like you've said string_buffer is global, but you only define it if there's a UnicodeDecodeError - you should always define string_buffer before your virt_mem_after_write function. That might fix your problem.

**Comment by ChipMonto** [comment]
Not sure how I missed that, adding the definition outside of the function indeed solved the problem thanks!
