### ISSUE TITLE
COSI error loading profile

### ISSUE THREAD

**Issue by IridiumXOR** [panda-re/panda#1306]
Hi, 
I have created a Volatility 3 profile (which work correctly on volatility) and I'm trying to load it with COSI plugin (on docker and also compiled from source PANDA latest version) however I obtain this error
```
PANDA[core]:initializing cosi
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Error("invalid value: integer `-2`, expected u64", line: 1321, column: 11)', /panda/panda/plugins/cosi/volatility_profile/src/lib.rs:179:34
```
how can i fix it?

**Comment by jamcleod** [comment]
That's a bug on our end, I'll try and push a fix and let you know when it's good to test, thanks for reporting

**Comment by jamcleod** [comment]
@IridiumXOR if you could send your profile that would be very helpful in figuring out the specific issue--basically one of the fields that I did not anticipate being signed (address, array size, or bitfield offset) is showing up as signed in your profile.

Alternatively if you cannot send the entire profile, doing the following should show me all I need:

```
grep "-2" your_profile.json | head
```
and sending me the results should be good enough.

**Comment by IridiumXOR** [comment]
Hi, thank you.
The profile is for the stock vmlinux-5.19.0-40-generic of a Ubuntu 22.04 desktop machine.
Here attached the xz profile (sorry, I have also zipped it due to github policy on uploads :/)

[ubuntu2204_desktop.json.xz.zip](https://github.com/panda-re/panda/files/11547768/ubuntu2204_desktop.json.xz.zip)

**Comment by IridiumXOR** [comment]
I suppose the problem is in bitfield offset, because there is some definitions with "-2" values

**Comment by jamcleod** [comment]
Very weird, don't really know what I negative offset could mean, but I guess I'll push a fix?

**Comment by jamcleod** [comment]
Feel free to test the PR if you get a chance, otherwise I'll merge it in a few days and you can open another issue if it doesn't work

**Comment by zestrada** [comment]
For what it's worth, I ran into the same issue today and can confirm this PR seems to address it.

**Comment by IridiumXOR** [comment]
Tested and it works!
