### ISSUE TITLE
Feature request: Hook module + offset

### ISSUE THREAD

**Issue by AndrewFasano** [panda-re/panda#1354]
We support hooking addresses and library functions by name. It would be nice to also support hooking a module by name + an integer offset. Could be useful for hooking non-exported functions after some manual RE.

```
# Exists
@panda.hook(0x1234)
...

# Exists
@panda.hook_symbol("libc-", "printf")
...

# What I'm proposing (open to other names)
@panda.hook_module_offset("a.out", 0x1000)
```

**Comment by lacraig2** [comment]
Hooking at an offset in a library is a feature that exists. The second argument to `hook_symbol` accepts either a `string` or an `int`. See: 

https://github.com/panda-re/panda/blob/dev/panda/python/core/pandare/panda.py#L3130

However, I think your suggestion that we add another function name for this specifically could be helpful.

**Comment by AndrewFasano** [comment]
That's amazing! It's even documented. If you want to leave this open and add another name, feel free - but I'm happy to close this as an "Andrew didn't read the docs" issue
