### ISSUE TITLE
windows qcow support

### ISSUE THREAD

**Issue by antonislouca** [panda-re/panda#1360]
I am currently using Pandare with Python to automate some analysis. 
Now, I managed to use it with the provided Linux qcow image. However, I want 
to use the automation with a Windows guest (maybe Windows 10).
Currently, I am using a Windows server qcow, but I face a problem with the initialization of Panda, where panda cannot find the qcow and the configuration to use.
Can someone shed some light on this matter?

**Comment by AndrewFasano** [comment]
Take a look at the pypanda docs for the panda constructor [here](https://docs.panda.re/#pandare.Panda) - you should be able to specify a path to your qcow.

In it's current state, it's pretty difficult to run windows 10 under PANDA, it's something we're working on fixing, but it's not high on our task list. I'd recommend using Windows 7 instead if that works for you. Then you can use the [wintrospection plugin](https://github.com/panda-re/panda/blob/dev/panda/plugins/wintrospection/) for operating system introspection.

**Comment by antonislouca** [comment]
Thank you for the quick  reply. Is there a tested image for windows 7 that you know it is PANDA compatible?

**Comment by AndrewFasano** [comment]
Unfortunately we haven't yet figured out a standard way for distributing windows images due to licensing issues. If you look at [libosi's readme](https://github.com/panda-re/libosi/tree/master) there are a list of windows kernel versions that should be supported. For windows 7 64-bit that's SP0 and SP1.

**Comment by antonislouca** [comment]
Great thank you for the support.
