### ISSUE TITLE
clone error

### ISSUE THREAD

**Issue by cctv130** [panda-re/panda#1380]
Cloning into 'panda'...
remote: Enumerating objects: 742156, done.
remote: Counting objects: 100% (742135/742135), done.
remote: Compressing objects: 100% (134176/134176), done.
remote: Total 742156 (delta 605732), reused 741245 (delta 605290), pack-reused 21Receiving objects: 100% (742156/742156)Receiving objects: 100% (742156/742156), 391.09 MiB | 10.95 MiB/s, done.

Resolving deltas: 100% (605747/605747), done.
error: invalid path 'panda/dependencies/ubuntu:18.04_base.txt'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'

**Comment by AndrewFasano** [comment]
Sounds like something wrong with your system or your connection to github, not an issue with our code. Perhaps you can delete your panda directory and re-clone or try the command git suggested in your error.

**Comment by MarkMankins** [comment]
I've seen this if you try to clone the repo on windows.

The panda repo contains files that have characters that are illegal in windows file names.

**Comment by AndrewFasano** [comment]
🤯 wow that's unexpected - perhaps this is a bug we should be tracking then!

We should be able to rename the dependency list filenames to drop the `:` and make Windows happy
