### ISSUE TITLE
docker run error

### ISSUE THREAD

**Issue by cctv130** [panda-re/panda#1406]
docker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "panda-system-i386": executable file not found in $PATH: unknown.

**Comment by AndrewFasano** [comment]
Are you using a container from dockerhub? Did you build it yourself? How did you launch it?

I just pulled the latest pandare/panda container from dockerhub and it seems to work fine:
```
docker run -it pandare/panda:latest panda-system-i386 --help
QEMU emulator version 2.9.1 (-dirty)
Build date Dec 14 2023
Copyright (c) 2003-2017 Fabrice Bellard and the QEMU Project developers
usage: panda-system-i386 [options] [disk_image]

# ...
```

**Comment by cctv130** [comment]
@AndrewFasano I am going to abandon this project and consider putting the panda core on another project (in plugin form), this project is too painful
