### ISSUE TITLE
OSI Linux broken since `thread_group` removed

### ISSUE THREAD

**Issue by be32826** [panda-re/panda#1422]
Linux removed `thread_group` in https://github.com/torvalds/linux/commit/8e1f385104ac044f1552686ad6e1cbc71cc05a30, and this breaks `osi_linux`, which expects that field to exist.

```
Reading symbols from /kernels/6.7/vmlinux.armel...
Python Exception <class 'gdb.error'>: There is no member named thread_group.
Error occurred in Python: There is no member named thread_group.
```

**Comment by AminoACID123** [comment]
It seems to me #1429 does not completely solve the issue. Could you update `kernelinfo.c` as well? Also, `current_task` is no longer a standalone variable but a member of `pcpu_hot`.

**Comment by lacraig2** [comment]
@AminoACID123 I recommend opening an issue and referencing this PR. Commenting on a merged PR itself is likely to get much less attention.
