### ISSUE TITLE
Net transfer callbacks missing

### ISSUE THREAD

**Issue by moyix** [panda-re/panda#143]
The `PANDA_CB_REPLAY_NET_TRANSFER` and `PANDA_CB_REPLAY_HANDLE_PACKET` callbacks exist, but aren't currently hooked up to anything. This should be fairly easy to port over (the e1000 device doesn't seem to have changed much); someone just needs to do it.

**Comment by scottcarr** [comment]
I'm going to attempt this.  Please see #275.  I think I may know how to do part of it, but guidance is welcome.
