### ISSUE TITLE
callstack_instr arm mode cs_open always returns error

### ISSUE THREAD

**Issue by wintao** [panda-re/panda#144]
Hi, while using callstack_instr plugin in the ARM, it seems that cs_open always return error
the code is as below:

bool init_plugin(void *self) {
    if (cs_open(CS_ARCH_ARM, CS_MODE_32, &cs_handle_32) != CS_ERR_OK)

after reading capstone.h, i suspect that the CS_MODE_32 is for x86, so it should be CS_MODE_ARM here
the following code snippet is from captone.h
// Mode type
typedef enum cs_mode {
	CS_MODE_LITTLE_ENDIAN = 0,	// little-endian mode (default mode)
	CS_MODE_ARM = 0,	// 32-bit ARM
	CS_MODE_16 = 1 << 1,	// 16-bit mode (X86)
	CS_MODE_32 = 1 << 2,	// 32-bit mode (X86)
	CS_MODE_64 = 1 << 3,	// 64-bit mode (X86, PPC)

so i change the source line into the following code, the plugin works as expected.
    if (cs_open(CS_ARCH_ARM,  CS_MODE_ARM, &cs_handle_32) != CS_ERR_OK)

Thanks!

**Comment by moyix** [comment]
Yep, you're correct. Could submit this change as a pull request?

**Comment by wintao** [comment]
OK, I made a pull request, thanks!

**Comment by moyix** [comment]
Merged, thanks!
