### ISSUE TITLE
offset/i_t.h not found while running ../build.sh

### ISSUE THREAD

**Issue by Kingsdom005** [panda-re/panda#1442]
Error information:
/home/user0/Desktop/PANDA/mypanda/panda_git/panda-dev/panda/plugins/wintrospection/wintrospection.cpp:21:10: fatal error: offset/i_t.h: No such file or directory

How to solve it?
Wish for your help!

**Comment by Kingsdom005** [comment]
Another problem:
/home/user0/Desktop/PANDA/mypanda/panda_git/panda-dev/panda/plugins/wintrospection/pandamemory.cpp:7:10: fatal error: iohal/memory/common.h: No such file or directory
    7 | #include <iohal/memory/common.h>

**Comment by AndrewFasano** [comment]
I think you need to install libosi: either [from source](https://github.com/panda-re/libosi) or a .deb: https://github.com/panda-re/libosi/releases/tag/0.1.3
