### ISSUE TITLE
Replay Error in qemu-system-i386

### ISSUE THREAD

**Issue by StablelJay** [panda-re/panda#146]
I built the panda on ubuntu14.04 and created the image using windows xp iso by qemu-system-i386.
after built, I try to test the record ,first I open the image 

> sudo ./qemu-system-i386 mywinxp.qcow2 -m 2048 -monitor stdio 

then I type "begin_record notepad"  and "end_record"  in qemu monitor command line

> (qemu) begin_record notepad
(qemu) writing snapshot:	./notepad-rr-snp
opening nondet log for write :	./notepad-rr-nondet.log
end_record
(qemu) Time taken was: 40 seconds.

then I quit qemu monitor, and try to replay the record, using following command.

> sudo ./qemu-system-i386 -replay notepad -m 2048 

but there are warnings and errors 

> loading snapshot
... done.
opening nondet log for read :	./notepad-rr-nondet.log
main-loop: WARNING: I/O thread spun for 1000 iterations
Ahead of log while looking for log entry of type RR_SKIPPED_CALL
{guest_instr_count=9761}
	RR_INPUT_8 from RR_CALLSITE_IO_READ_ALL
FOUND DISAGREEMENT!
Replay program point:
{guest_instr_count=9762}

Record program point:
{guest_instr_count=9761}

>>> guest instruction counts disagree
notepad:        9762 (  0.00%) instrs.    0.23 sec.  0.64 GB ram.
ERROR: replay failed!
Time taken was: 0 seconds.
Stats:
RR_INPUT_1 number = 0, size = 0 bytes
RR_INPUT_2 number = 0, size = 0 bytes
RR_INPUT_4 number = 10, size = 140 bytes
RR_INPUT_8 number = 14, size = 252 bytes
RR_INTERRUPT_REQUEST number = 12, size = 168 bytes
RR_EXIT_REQUEST number = 0, size = 0 bytes
RR_SKIPPED_CALL number = 0, size = 0 bytes
max_queue_len = 9
ERROR: replay failed!

Could u please help me to solve this problem? Is there any problem in my commands? THANKS!

**Comment by moyix** [comment]
Could you try recording and replaying again with the most recent PANDA? A record/replay fix was recently committed that may fix this.

**Comment by moyix** [comment]
Closing this for now – please reopen if you are still having problems.
