### ISSUE TITLE
callbacks not work: virt_mem_read() / virt_mem_write()

### ISSUE THREAD

**Issue by s0i37** [panda-re/panda#147]
Hello.
I want to write a plugin that performs a memory trace.
I use:
```
int virt_mem_before_read(CPUState *env, target_ulong pc, target_ulong addr, target_ulong size)
int virt_mem_before_write(...)
int virt_mem_after_read(...)
int virt_mem_after_write(...)
```
and the same for `phys_mem_read/write()`
then I:
```
pcb.virt_mem_before_read = virt_mem_before_read;
panda_register_callback(self, PANDA_CB_VIRT_MEM_BEFORE_READ, pcb);
```
But during replay only insn_translate() and insn_exec() callbacks. Callbacks phys_mem_read/write() and virt_mem_read/write() do not work.
I tried to do this in panda 1.0 and panda 2.0 (docker image).

**Comment by moyix** [comment]
Did you remember to call `panda_enable_memcb()` ?

**Comment by s0i37** [comment]
Yes. Thank you.

**Comment by moyix** [comment]
I assume that means it's working now? I will close this, but feel free to reopen it if it's still not working.

**Comment by DOT850** [comment]
I'm having a similar issue to this. But it misses some callbacks when I load the plugin from the console, not on panda boot. Interestingly, if I am debugging the target with GDB and have breakpoints around the areas of interest, the callback fires? I am wondering if the issue might be that the memory offsets might not be correct when the plugin is loaded later?
