### ISSUE TITLE
Docker: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /lib/libosi.so)

### ISSUE THREAD

**Issue by KarlKeu00** [panda-re/panda#1477]
Hello everyone,
unfortunately I get the error with the following code in `pandare/panda:latest` that GLIBC was not found.
```python
@panda.ppp("osi", "on_task_change")
    def taskchange(cpu):
        logging.debug("Task changed")
```
```
os_name=[windows-64-7sp1]
PANDA[core]:os_familyno=1 bits=64 os_details=7sp1
[PYPANDA] Panda args: [/usr/local/bin/libpanda-x86_64.so -L /usr/local/bin/pc-bios /images/win7.qcow2 -monitor stdio -vnc 0.0.0.0:0 -m 2G -monitor unix:/tmp/pypanda_mj3vg70xq,server,nowait]
PPP automatically loaded plugin osi
PANDA[core]:E:callbacks.c(_panda_load_plugin)> PANDA[core]:Failed to load /usr/local/lib/panda/x86_64/panda_wintrospection.so: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /lib/libosi.so)

PANDA[core]:E:callbacks.c(_panda_require)> PANDA[core]:FAILED to load required plugin wintrospection from /usr/local/lib/panda/x86_64/panda_wintrospection.so

Aborted (core dumped)
```
I have already researched the error, but unfortunately I have not been able to successfully implement a solution yet. Apparently GLIBC_2.31 is installed in the Docker image.
Perhaps someone here has an idea?

Edit: I have just found the error. The error was that Ubuntu 20.04 is not yet delivered with GLIBC_2.32. Simple fix: Change Dockerfile to ubuntu:22.04.

**Comment by AndrewFasano** [comment]
We notionally support both ubuntu 22.04 and 20.04. This might be a wintrospection specific bug if it's being built to only support 22.04.

**Comment by lacraig2** [comment]
This looks like a libosi CI bug. The packages aren't being properly built for different versions of ubuntu.

Looks like it's my fault. I'll have a look at it.

**Comment by lacraig2** [comment]
I've fixed this bug.
