### ISSUE TITLE
Issues when replaying a windows os

### ISSUE THREAD

**Issue by vancaho** [panda-re/panda#151]
Hi, I download the latest panda 2 codes and build it on my Ubuntu 16.04 64bit which runs under the Vmware. Then I record execution of notepad.exe, and try to replay it with panda. However it reports the following error:
       RR rr_assertion `0' failed at /home/vc/Codes/panda/panda/src/rr/rr_log.c:1030
How to solve this error? Thank you

**Comment by moyix** [comment]
Hi, could you try this again with the most recent PANDA? A fix for some record/replay bugs was just committed.

**Comment by moyix** [comment]
Closing for now – please reopen if this is still a problem for you.
