### ISSUE TITLE
could you explain a little how PANDA trace system-call on windows?

### ISSUE THREAD

**Issue by zshu1** [panda-re/panda#153]
I am new to system and memory. I want to learn from PANDA
I read the code and find here:

```
// Check if the instruction is sysenter (0F 34),
// syscall (0F 05) or int 0x80 (CD 80)
bool translate_callback(CPUState *cpu, target_ulong pc) {
#if defined(TARGET_I386)
    unsigned char buf[2] = {};
    panda_virtual_memory_rw(cpu, pc, buf, 2, 0);
    // Check if the instruction is syscall (0F 05)
    if (buf[0]== 0x0F && buf[1] == 0x05) {
        syscallPCpoints.insert(std::make_pair(pc, panda_current_asid(cpu)));
        return true;
    }
    // Check if the instruction is int 0x80 (CD 80)
    else if (buf[0]== 0xCD && buf[1] == 0x80) {
        syscallPCpoints.insert(std::make_pair(pc, panda_current_asid(cpu)));
        return true;
    }
    // Check if the instruction is sysenter (0F 34)
    else if (buf[0]== 0x0F && buf[1] == 0x34) {
        syscallPCpoints.insert(std::make_pair(pc, panda_current_asid(cpu)));
        return true;
    }
    else {
        return false;
    }

```
How PANDA get the instruction value by " panda_virtual_memory_rw(cpu, pc, buf, 2, 0); "?   "pc" seems to be the instruction address. should it get from CPU_State* env ?
Also , I want to get instructions value for each instructions. Could PANDA do this?
Hope someone could help me on this. Thanks

**Comment by m000** [comment]
How it worked: You check the opcode of the instruction to be executed, and
then inspect the context related to it. A convenient index of the
instruction set can be found in [1]. For the definitive manuals, you should
check Intel's (bulky) manuals [2].

Get instruction value: Not sure what you mean by that. The instructions are
listed in the locations I mentioned above. If you're looking for a more
human-friendly way to process instructions (rather having to hardcode their
opcodes), DiStorm [3] may come handy.

[1] http://www.felixcloutier.com/x86/
[2] https://software.intel.com/en-us/articles/intel-sdm
[3] https://github.com/gdabah/distorm

2017-03-30 3:39 GMT+02:00 zshu1 <notifications@github.com>:

**Comment by zshu1** [comment]
I mean because the instructions have no fixed length. The opcode also may not just first 1byte( maybe 2 bytes like syscall). For now I can only get begin address of each instructions. how do I know the end of each instructions? So I want to get the whole instruction out, including opcode and arguments.

**Comment by m000** [comment]
If you have a known-good reference point (e.g. current EIP), then a
disassembler like DiStorm will do the hard work for you. You can pass it a
memory buffer starting at that address, it will decode as far as it can,
and return you a structured representation of the instructions decoded. It
will also point out how much of the buffer couldn't be decoded, so you can
try decoding it later.

If you don't have any point of reference, then you will have to attempt
decoding at every byte and try to guess which of the decodings were good. I
believe IDA Pro has such capabilities but I haven't ever used it.


2017-03-30 16:21 GMT+02:00 zshu1 <notifications@github.com>:

**Comment by zshu1** [comment]
Thanks a lot! It really helps me.
