### ISSUE TITLE
GLIBC problem in Docker image

### ISSUE THREAD

**Issue by meatballmaestro** [panda-re/panda#1530]
In the latest Docker image [0]:

```
# panda-system-x86_64 ~/.panda/win7-x64.qcow2 -panda snake_hook:files=testplug.py -os windows-64-7sp1
[...]
PANDA[core]:E:callbacks.c(_panda_load_lugin)> PANDA[core]:Failed to load /usr/local/lib/panda/x86_64/panda_wintrospection.so: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /lib/libosi.so)

PANDA[core]:E:callbacks.c(_panda_require)> PANDA[core]: FAILED o load required plugin wintrospection from /usr/local/lib/x86_64/panda_wintrospection.so

Aborted
```

`testplug.py` is just a simple plugin that registers an informational `cb_asid_changed`:

```python
class testplug(PyPlugin):
    def __init__(self, panda):
        @panda.cb_asid_changed
        def tp_asid_changed(cpu, old, new):
            print(hex(panda.current_asid(cpu)), panda.get_process_name(cpu))
            return False
````

[0] https://hub.docker.com/r/pandare/panda

**Comment by lacraig2** [comment]
I haven't actually checked that this worked for this use-case so I'll leave this open, but I expect #1531 to fix this.

**Comment by meatballmaestro** [comment]
I just checked using the most recently published Docker image; a 64-bit Windows 7 qcow2; and the minuscule Python plugin given above. All seems well so far.

**Comment by meatballmaestro** [comment]
Reopening because this isn't my code base, so it's probably poor form for me to close the issue. But I'm happy.
