### ISSUE TITLE
panda.re web page is not working

### ISSUE THREAD

**Issue by Nicholas-wei** [panda-re/panda#1554]
Hello, the maintainer of panda.
Thanks for providing the fantastic framework. </br>I met some problems when trying to install panda framework
1. The web page of https://panda.re is not working now. 
2. When I am trying to install panda, https://panda-re.mit.edu/qcows/linux/ubuntu/1604/x86/ubuntu_1604_x86.qcow seems to be missing. (The download procedure returned nothing and raised an exception)

I checked my network and confirmed it was not my local network issue. Could you please help check out and fix the problem? Thank you.

**Comment by lacraig2** [comment]
@Nicholas-wei our infrastructure was briefly down for maintenance. It is now back up.
