### ISSUE TITLE
void on_first_syscall(CPUState*, target_ulong, target_ulong)

### ISSUE THREAD

**Issue by enlist12** [panda-re/panda#1555]
when I run plugins syscalls2 and syscalls-logger,I encounter this problem 

root@pwn-virtual-machine:/src# PANDA[core]:os_familyno=2 bits=64 os_details=ubuntu:5.6.13
PANDA[syscalls2]:using profile for linux x64 64-bit
[WARNING] syscalls_logger: No DWARF JSON provided, data logged will be incomplete.
PANDA[osi_linux]:W> failed to read task.start_time_offset
PANDA[osi_linux]:W> failed to read task.switch_task_hook_addr
PANDA[osi_linux]:W> kernelinfo bytes [20-23] not read
QEMU 2.9.1 monitor - type 'help' for more information
(qemu) panda-system-x86_64: -serial pty: char device redirected to /dev/pts/1 (label serial0)
loading snapshot
... done.
opening nondet log for read :   ./race-rr-nondet.log
panda-system-x86_64: /panda/panda/plugins/osi_linux/osi_linux.cpp:326: void on_first_syscall(CPUState*, target_ulong, target_ulong): Assertion `can_read_current(cpu) && "Couldn't find current task struct at first syscall"' failed.
Aborted (core dumped)

Similar problem is likely proposed three years ago,however,I don't know how to correct it.I run panda with docker images and kernelinfo is retrived without kaslr.

**Comment by enlist12** [comment]
name = 5.6.13|#6 SMP Mon Nov 25 23:26:34 CST 2024|x86_64
version.a = 5
version.b = 6
version.c = 13
task.per_cpu_offsets_addr = 18446744071599597248
task.per_cpu_offset_0_addr = 18446612687367438336
task.current_task_addr = 97536
task.init_addr = 18446744071601989696
#task.per_cpu_offsets_addr = FFFFFFFF823CA6C0
#task.per_cpu_offset_0_addr = 0xFFFF88813BC00000
#task.current_task_addr = 0x00017D00
#task.init_addr = 0xFFFFFFFF82612840
task.size = 6784
task.tasks_offset = 912
task.pid_offset = 1168
task.tgid_offset = 1172
task.group_leader_offset = 1232
task.thread_group_offset = 1344
task.real_parent_offset = 1184
task.parent_offset = 1192
task.mm_offset = 992
task.stack_offset = 24
task.real_cred_offset = 1584
task.cred_offset = 1592
task.comm_offset = 1608
task.comm_size = 16
task.files_offset = 1664
cred.uid_offset = 4
cred.gid_offset = 8
cred.euid_offset = 20
cred.egid_offset = 24
mm.size = 992
mm.mmap_offset = 0
mm.pgd_offset = 80
mm.arg_start_offset = 312
mm.start_brk_offset = 288
mm.brk_offset = 296
mm.start_stack_offset = 304
vma.size = 192
vma.vm_mm_offset = 64
vma.vm_start_offset = 0
vma.vm_end_offset = 8
vma.vm_next_offset = 16
vma.vm_flags_offset = 80
vma.vm_file_offset = 160
fs.f_path_dentry_offset = 24
fs.f_path_mnt_offset = 16
fs.f_pos_offset = 104
fs.fdt_offset = 32
fs.fdtab_offset = 40
fs.fd_offset = 8
qstr.size = 16
qstr.name_offset = 8
path.d_name_offset = 32
path.d_iname_offset = 56
path.d_parent_offset = 24
path.d_op_offset = 96
path.d_dname_offset = 72
path.mnt_root_offset = 0
path.mnt_parent_offset = -16
path.mnt_mountpoint_offset = -8

this is my kernelinfo

**Comment by lacraig2** [comment]
How did you generate your kernelinfo?

Is kaslr disabled?

**Comment by enlist12** [comment]
> How did you generate your kernelinfo?
> 
> Is kaslr disabled?

yes,kaslr has been disabled when I get kernelinfo and snap

**Comment by enlist12** [comment]
> How did you generate your kernelinfo?
> 
> Is kaslr disabled?

I complied kernel with CONDIG_RANDOMIZE_BASE=n,so kernel is without kaslr naturally,then I start it with qemu and execute insmod kernelinfo.ko,then I get kernelinfo.

**Comment by enlist12** [comment]
> How did you generate your kernelinfo?
> 
> Is kaslr disabled?

when I execute
#!/bin/sh

panda-system-x86_64\
    -monitor stdio\
    -serial pty\
    -m 4G\
    -kernel "./bzImage" \
    -append "console=ttyS0 quiet loglevel=3 pti=on  nokaslr min_addr=4096" \
    -no-reboot \
    -initrd "./rootfs.cpio"\
    -cpu qemu64,+smep,+smap \
    -replay race\
    -os linux-64-ubuntu:5.6.13\
    -panda callstack_instr\
    -panda osi\
    -panda osi_test

I encounter:
loading snapshot
... done.
opening nondet log for read :   ./race-rr-nondet.log
Current process: sh PID:122 PPID:120

Process list (42 procs):
  swapper/0             0       0
  init                  1       0
  kthreadd              2       0
  rcu_gp                3       2
  rcu_par_gp            4       2
  kworker/0:0           5       2
  kworker/0:0H          6       2
  kworker/u2:0          7       2
  mm_percpu_wq          8       2
  ksoftirqd/0           9       2
  rcu_sched             10      2
  migration/0           11      2
  cpuhp/0               12      2
  kdevtmpfs             13      2
  netns                 14      2
  kauditd               15      2
  oom_reaper            16      2
  writeback             17      2
  kcompactd0            18      2
  kworker/u2:1          20      2
  kworker/0:1           22      2
  kblockd               65      2
  ata_sff               66      2
  md                    67      2
  edac-poller           68      2
  rpciod                69      2
  kworker/u3:0          70      2
  xprtiod               71      2
  cfg80211              72      2
  kswapd0               73      2
  nfsiod                74      2
  acpi_thermal_pm       77      2
  scsi_eh_0             78      2
  scsi_tmf_0            79      2
  scsi_eh_1             80      2
  scsi_tmf_1            81      2
  kworker/u2:2          82      2
  kworker/0:1H          83      2
  kworker/0:2           84      2
  ipv6_addrconf         85      2
  sh                    120     1
  sh                    122     120

-------------------------------------------------

Dynamic libraries list (10 libs):
        0x0000000000400000      4096    busybox                  /bin/busybox
        0x0000000000401000      2080768 busybox                  /bin/busybox
        0x00000000005fd000      475136  busybox                  /bin/busybox
        0x0000000000671000      28672   busybox                  /bin/busybox
        0x0000000000678000      12288   busybox                  /bin/busybox
        0x000000000067b000      28672   [???]                    (null)
        0x0000000001580000      139264  [heap]                   (null)
        0x00007ffdc5af0000      135168  [stack]                  (null)
        0x00007ffdc5b4d000      16384   [???]                    (null)
        0x00007ffdc5b51000      8192    [???]                    (null)

No mapped kernel modules.

-------------------------------------------------

Cannot get current process details.

panda-system-x86_64: /panda/panda/plugins/osi_linux/default_profile.cpp:116: target_ptr_t default_get_group_leader(CPUState*, target_ptr_t): Assertion `err == struct_get_ret_t::SUCCESS && "failed to get group leader for task"' failed.
Aborted (core dumped)

this problem

**Comment by enlist12** [comment]
> How did you generate your kernelinfo?
> 
> Is kaslr disabled?

I have tried to get kernelinfo five times,they are in the same.

**Comment by enlist12** [comment]
> > How did you generate your kernelinfo?
> > Is kaslr disabled?
> 
> I have tried to get kernelinfo five times,they are in the same.

please help,this problem has disturbed me the whole day.Any help would be thanks

**Comment by enlist12** [comment]
> How did you generate your kernelinfo?
> 
> Is kaslr disabled?

[ubuntu:5.6.13:64]
name = 5.6.13|#6 SMP Mon Nov 25 23:26:34 CST 2024|x86_64
version.a = 5
version.b = 6
version.c = 13
task.per_cpu_offsets_addr = 18446744071599597248
task.per_cpu_offset_0_addr = 18446612687367438336
task.current_task_addr = 97536
task.init_addr = 18446744071601989696
#task.per_cpu_offsets_addr = FFFFFFFF823CA6C0
#task.per_cpu_offset_0_addr = 0xFFFF88813BC00000
#task.current_task_addr = 0x00017D00
#task.init_addr = 0xFFFFFFFF82612840
task.size = 6784
task.tasks_offset = 912
task.pid_offset = 1168
task.tgid_offset = 1172
task.group_leader_offset = 1232
task.thread_group_offset = 1344
task.real_parent_offset = 1184
task.parent_offset = 1192
task.mm_offset = 992
task.stack_offset = 24
task.real_cred_offset = 1584
task.cred_offset = 1592
task.comm_offset = 1608
task.comm_size = 16
task.files_offset = 1664
cred.uid_offset = 4
cred.gid_offset = 8
cred.euid_offset = 20
cred.egid_offset = 24
mm.size = 992
mm.mmap_offset = 0
mm.pgd_offset = 80
mm.arg_start_offset = 312
mm.start_brk_offset = 288
mm.brk_offset = 296
mm.start_stack_offset = 304
vma.size = 192
vma.vm_mm_offset = 64
vma.vm_start_offset = 0
vma.vm_end_offset = 8
vma.vm_next_offset = 16
vma.vm_flags_offset = 80
vma.vm_file_offset = 160
fs.f_path_dentry_offset = 24
fs.f_path_mnt_offset = 16
fs.f_pos_offset = 104
fs.fdt_offset = 32
fs.fdtab_offset = 40
fs.fd_offset = 8
qstr.size = 16
qstr.name_offset = 8
path.d_name_offset = 32
path.d_iname_offset = 56
path.d_parent_offset = 24
path.d_op_offset = 96
path.d_dname_offset = 72
path.mnt_root_offset = 0
path.mnt_parent_offset = -16
path.mnt_mountpoint_offset = -8

I have copied this into /usr/local/etc/panda/osi_linux/kernelinfo.conf

**Comment by enlist12** [comment]
> How did you generate your kernelinfo?
> 
> Is kaslr disabled?

thanks,problem has been solved,when I recorded,kpti and smep and smap is on.I try to close them just now,the problem prementioned is disappear.

**Comment by enlist12** [comment]
> How did you generate your kernelinfo?
> 
> Is kaslr disabled?

maybe you can modify osi_linux to let them suit kpti,smep and smap or remind users of disabling them when use PANDA.
