### ISSUE TITLE
Build Failure 

### ISSUE THREAD

**Issue by DEichEich** [panda-re/panda#157]
The last commit has caused building panda to fail. The problem is `panda/plugins/file_taint.cpp` on line 38. For some  reason the file `file_taint_int_fns.h` is missing. To trick panda into building you can comment line 38 out. But I am not sure the larger impacts this has on the entire system.

**Comment by moyix** [comment]
Looks like this one is for @RickyUlrich, as it's his commit.

**Comment by moyix** [comment]
Fixed by 129c85e5d14055c759ecdc54079e532a54d0a34a.
