### ISSUE TITLE
Error when using PANDA syscalls

### ISSUE THREAD

**Issue by StablelJay** [panda-re/panda#161]
I  notice that there are many syscalls in PANDA, and I want to get the syscall  on_NtOpenFIle_enter when a process open a file, thus I could know the file the process has open.  To make it, I write a plugin like this. 

**_#include "../syscalls2/gen_syscalls_ext_typedefs.h"
#include "../syscalls2/syscalls_common.h"
#include "panda_plugin_plugin.h"

void my_NtReadFile_enter(
        CPUState* env,
        target_ulong pc,
        uint32_t FileHandle,
        uint32_t Event,
        uint32_t UserApcRoutine,
        uint32_t UserApcContext,
        uint32_t IoStatusBlock,
        uint32_t Buffer,
        uint32_t BufferLength,
        uint32_t ByteOffset,
        uint32_t Key) {
   printf("NtReadFile(FileHandle=%x, Event=%x, UserApcRoutine=%x, "
                     "UserApcContext=%x, IoStatusBlock=%x, Buffer=%x, "
                     "BufferLength=%x, ByteOffset=%x, Key=%x)\n",
        FileHandle, Event, UserApcRoutine, UserApcContext,
        IoStatusBlock, Buffer, BufferLength, ByteOffset, Key);
}

// ...

bool init_plugin(void *self) {
    PPP_REG_CB("syscalls2", on_NtReadFile_enter, my_NtReadFile_enter);
    return true;
}

// ..._**

but the problem is  when I make it, something is wrong like that :

"on_NtOpenFile_enter_t" was not declared in this scope.
PPP_REG_CB("syscalls2",on_NtReadFile_enter, my_NtReadFile_enter);

Could you please help me with this problem?

**Comment by moyix** [comment]
The prototype for that is contained in `syscalls2/gen_syscalls_ext_typedefs.h`. Could you make sure you're including that file, and that that file contains a prototype for `on_NtOpenFile_enter_t` ?

**Comment by StablelJay** [comment]
Yes， I am sure I have included syscalls2/gen_syscalls_ext_typedefs.h and it contains on_NtReadFile_enter_t.  What other  problems may result in it ?

**Comment by StablelJay** [comment]
Could u please show me a successful way of using syscalls ? For Example, if Ｉwant to write a plugin to open a file, how can I do that??

**Comment by moyix** [comment]
Have a look at the file_taint plugin; it uses system call hooks to monitor when files are opened.
