### ISSUE TITLE
panda_disable_tb_chaining() does not disable tb_chaining

### ISSUE THREAD

**Issue by mariusmue** [panda-re/panda#170]
Hi everyone!
panda_disable_tb_chaining() sets the variable panda_tb_chaining to false in panda/src/callbacks.c, which should disable the chaining of translated blocks (the default for replay-mode).

However, in cpu-exec.h, the code currently looks like this:

```C
 static inline TranslationBlock *tb_find(CPUState *cpu,
                                       TranslationBlock *last_tb,
                                        int tb_exit)
{
[...]
#ifdef CONFIG_SOFTMMU
    if (rr_mode != RR_REPLAY /* && panda_tb_chaining */) {
#endif
    if (last_tb && !qemu_loglevel_mask(CPU_LOG_TB_NOCHAIN)) {
        if (!have_tb_lock) {
            tb_lock();
            have_tb_lock = true;
        }
        if (!tb->invalid) {
            tb_add_jump(last_tb, tb_exit, tb);
        }
    }
#ifdef CONFIG_SOFTMMU
[...]
}
```

As you can see, the chaining for translated block is disabled for the replay-mode - if we are not in replay mode, this code is responsible for chaining tbs.
However, the check for panda_tb_chaining is commented, hence, calling panda_disable_tb_chaining() does not have any effects, as this is the only place where panda_tb_chaining is supposed to get used.

I was wondering if this feature is removed on purpose, or if this comment just "sneaked in" somewhen along the way. In the first case, it would make sense to update the documentation, in the latter case, I'd be happy to create a tiny PR (or looking forward to have this fixed by you guys).

//Edit:
This bug made me just wondering how the status for panda_update_pc (set by panda_enable/disable_precise_pc()) is.
And in fact, this variable is also never read by qemu, hence, the same as stated for panda_tb_chaining applies here (documentation update/PR).

**Comment by moyix** [comment]
It looks like these just slipped through the cracks in the transition from panda1 to panda2. We'd be very happy if you hooked those functions back up to something :)

**Comment by moyix** [comment]
With Marius's patch I think we can close this now.
