### ISSUE TITLE
Getting the current ThreadID on windows

### ISSUE THREAD

**Issue by vigliag** [panda-re/panda#172]
Hi everyone! I'm a student in Politecnico di Milano, and as part of my master thesis I'm using Panda to replicate some of the analysis from the [Dispatcher paper](http://bitblaze.cs.berkeley.edu/papers/dispatcher_ccs09.pdf). I'm currently trying to track dependencies between system calls, and I'm evaluating the simplest possible approach: watching every memory access a given thread performs between sysenter and sysexit, tainting on write, and reading taint on read.

I'm having some troubles understanding how to get a thread identifier on Windows. From what I've read, I should be able to access it easily via the [TIB](https://en.wikipedia.org/wiki/Win32_Thread_Information_Block), which should be pointed by the FS register. Wikipedia suggests  the snippet `mov EAX, FS:[0x18]` to get the TIB address, but I'm unsure how the FS register is used in that command, and how to do the equivalent thing in Panda.

I've also come across this code in win7x86intro https://github.com/panda-re/panda/blob/master/panda/plugins/win7x86intro/win7x86intro.cpp#L149-L157 which seems to be also reading data pointed from the FS register. Could you please explain me what these lines are doing exactly?

Thanks a lot in advance,
Gabriele

**Comment by moyix** [comment]
Sure. That code is slightly complicated by the fact that we are trying to get the value of the kernel's FS register (regardless of whether we're in user or kernel mode). That means we have to use a hardcoded value for the offset into the GDT (KMODE_FS). If all you care about is the *current* base address of the FS segment, you can use env->segs[R_FS].base to pull it out. Going through the GDT is only necessary if you want to get a different FS register. You can read a little more about this here:

http://stackoverflow.com/questions/15332171/thread-fs-segment-register-switching-between-user-and-kernel-land

**Comment by vigliag** [comment]
Perfect, it is clear now. Thanks a lot!
