### ISSUE TITLE
Error when load win7 plugins

### ISSUE THREAD

**Issue by StablelJay** [panda-re/panda#173]

**Comment by StablelJay** [comment]
I use plugins osi_test with win7 x86 guest OS, I use command 'sudo ./qemu-i386-softmmu -m 2G -replay test -panda osi -panda osi_test -panda win7x86intro', but when initialize plugin winstrospection, it reports error:
'qemu-system-i386: wintrospection.c:372: init_plugin: Assertion `panda_os_type == OST_WINDOWS' failed.'
How to solve this problem??

**Comment by moyix** [comment]
You don't need to load win7x86intro explicitly. Instead use the `-os` option: `-os windows-32-7`.
