### ISSUE TITLE
Different building results on  Macos 10.12 and Ubuntu

### ISSUE THREAD

**Issue by vancaho** [panda-re/panda#174]
Hi,recently I build panda2 on Macos 10.12. After installing necessary dependencies, the building progress begins.  How ever, the following error is reported:

/panda/panda/plugins/taint2/taint_api.cpp:92:13: error: use of undeclared identifier 'shad'
    assert (shad != NULL);

I checked taint_api.cpp, and found that I cannot find the definition of the 'shad' variable. After commenting the statement, the building succeeds.

However, if I build panda2 on ubuntu, the above error does not exist, though I cannot find the definition of 'shad' either.

What's the difference?

**Comment by moyix** [comment]
My guess is that the build process on Ubuntu defines NDEBUG, which causes the `assert` to be taken out. If you have time please submit a pull request taking that assert out!

**Comment by moyix** [comment]
Fixed by 8724ddf7100f79db9528ade0481d6e8b002af67c
