### ISSUE TITLE
Segmentation Fault When Using file_taint and taint2 Plugins

### ISSUE THREAD

**Issue by antverdovsky** [panda-re/panda#180]
I'm trying to use PANDA with the `file_taint` plugin to taint a file and track it. I get a segmentation fault when trying to do so, and I'm not sure why.

I am using a 32-bit Debian 8.6.0 guest and I run QEMU with the following command to open the VM:
`./qemu-system-x86_64 -L /usr/share/qemu -drive format=raw,file=debian.img`
Once the OS boots, I `begin_record test`, create a simple text file in the VM and `end_record`.

Once the QEMU VM is turned off, I use the replay command to try and analyze the recorded file using the `file_taint` plugin:
`./qemu-system-x86_64 -L /usr/share/qemu -replay test -monitor stdio \  `
`	-os linux-32-debian-3.16.0-4-586 \  `
`	-panda osi \  `
`	-panda syscalls2:profile=linux_x86 \  `
`	-panda osi_linux:kconf_group=debian-3.16.0-4-586:32 \  `
`	-panda taint2 \  `
`	-panda file_taint:filename=test.txt,pos=0  `

I get the following output from the above command:
`os_type=2 bits=32 os_details=[debian-3.16.0-4-586]`
`Adding PANDA arg syscalls2:profile=linux_x86.`
`Adding PANDA arg osi_linux:kconf_group=debian-3.16.0-4-586:32.`
`Adding PANDA arg file_taint:filename=test.txt.`
`Adding PANDA arg file_taint:pos=0.`
`Initializing plugin osi`
`Looking for kconffile in /home/anatoly/Downloads/panda2-git/build-panda/x86_64-softmmu/./panda/plugins/osi_linux/kernelinfo.conf`
`OSI grabbing Linux introspection backend.`
`Linux OSI, using group debian-3.16.0-4-586:32 from /home/anatoly/Downloads/panda2-git/build-panda/x86_64-softmmu/panda/plugins/osi_linux/kernelinfo.conf.`
`panda_require: osi_linux`
`Initializing plugin osi_linux`
`INFO(/home/anatoly/Downloads/panda-git/panda/panda/plugins/osi_linux/osi_linux.cpp:init_plugin): ``Read kernel info from group "debian-3.16.0-4-586:32" of file "/home/anatoly/Downloads/panda2-git/build-panda/x86_64-softmmu/panda/plugins/osi_linux/kernelinfo.conf".`
`INFO(/home/anatoly/Downloads/panda-git/panda/panda/plugins/osi_linux/osi_linux.cpp:init_plugin): osi_linux initialization complete.`
`Initializing plugin syscalls2`
`syscalls2: using profile for linux x86 32-bit`
`panda_load_plugin: /home/anatoly/Downloads/panda2-git/build-panda/x86_64-softmmu/panda/plugins/panda_osi_linux.so already loaded`
`Initializing plugin taint2`
`taint2: Propagating taint through pointer dereference ENABLED.`
`taint2: Instructed not to inline taint ops.`
`panda_require: callstack_instr`
`Initializing plugin callstack_instr`
`Initializing plugin file_taint`
`taint_filename = [test.txt]`
`positional_labels = 1`
`no_taint = 0`
`end_label = 1000000`
`first_instr = 0 `
`panda_require: osi`
`panda_load_plugin: /home/anatoly/Downloads/panda2-git/build-panda/x86_64-softmmu/panda/plugins/panda_osi.so already loaded`
`panda_require: syscalls2`
`panda_load_plugin: /home/anatoly/Downloads/panda2-git/build-panda/x86_64-softmmu/panda/plugins/panda_syscalls2.so already loaded`
`panda_require: osi_linux`
`panda_load_plugin: /home/anatoly/Downloads/panda2-git/build-panda/x86_64-softmmu/panda/plugins/panda_osi_linux.so already loaded`
`panda_require: taint2`
`panda_load_plugin: /home/anatoly/Downloads/panda2-git/build-panda/x86_64-softmmu/panda/plugins/panda_taint2.so already loaded`
`taint2: __taint_enable_taint`
`taint2: Allocating small fast_shad (0 bytes) using malloc @ 7f839b880020.`
`taint2: Allocating small fast_shad (12800000 bytes) using malloc @ 7f8381cb3010.`
`taint2: Allocating small fast_shad (256 bytes) using malloc @ 7f839b957c70.`
`taint2: Allocating small fast_shad (2048 bytes) using malloc @ 7f839adc2cd0.`
`taint2: Allocating small fast_shad (685568 bytes) using malloc @ 7f839849d010.`
`taint2: Linking taint ops from ./panda/plugins/panda_taint2_ops.bc`
`taint2: Done initializing taint transformation.`
`Segmentation fault (core dumped)`

As you can see, a segmentation fault is thrown when loading the `taint2` plugin. I have already created the appropriate `osi_linux` configuration file, I have enough RAM for the taint plugin and I installed all of the dependencies of PANDA. The host machine is a 64-bit Ubuntu 14.04 build. I am not 100% sure I am executing the replay command correctly, so that may be the culprit. Thank you in advance for any help!

**Comment by moyix** [comment]
Could you run the replay command under gdb and post a backtrace (using `bt` in gdb once it crashes)?

**Comment by phulin** [comment]
There's an issue with turning taint on at the very beginning of replay that
I haven't had time to fix. Try passing first_instr=1 to the file_taint
plugin. That will defer enabling taint until the second basic block.

**Comment by antverdovsky** [comment]
@moyix, @phulin Thank you for your guys' replies! I tried applying the first_instr=1 argument and it seems to have fixed the issue but now I get another error a little bit after the original error:
`[up to here, same as before...]`
`taint2: Done initializing taint transformation.` <- Original crashed here.
`taint2: Done processing helper functions for taint.` 
`taint2: Done verifying module. Running...`
`ERROR: unknown TCG micro operation 'extu_i32_i64'`
`/home/anatoly/Downloads/panda-git/panda/panda/llvm/tcg-llvm.cpp:1387: tcg fatal error`
`Aborted (core dumped)`
I will try running replay with GDB to see exactly where the error occurs but do you guys know why this error might occur?

**Comment by phulin** [comment]
That's a new TCG micro-operation that we have somehow failed to implement. Unfortunately I don't really have an answer for you other than to add an implementation of it to tcg-llvm.cpp.

**Comment by antverdovsky** [comment]
@phulin I'm not too familiar with TCG micro-operations or their implementations. Would this be a difficult problem for me to solve by myself? Also, do you by any chance know if the Docker image of PANDA would be compatible and work out of the box, or is that missing the TCG operation also?

**Comment by antverdovsky** [comment]
@phulin Would you like me to share the replay with you?

**Comment by phulin** [comment]
First try latest commit: https://github.com/panda-re/panda/commit/fdd63f40b360997d16c21ef7055485d7dfe8a3cd

**Comment by antverdovsky** [comment]
@phulin Thank you very much! That fixed it!

**Comment by Ken-HUST** [comment]
I also get the similar error when i use the file_taint plugin. Can you give me some suggestion to fix the bug?
![image](https://user-images.githubusercontent.com/28556735/29511745-9e45b744-8692-11e7-8e5d-5ea541431e74.png)

**Comment by wangray** [comment]
@Ken-HUST it should be simply adding a line to tcg-llvm.cpp to support that micro-op. 

There's already a version for [`andc_i32`],(https://github.com/panda-re/panda/blob/ea0df1624a44afc42adf1310876cb758c12b3eea/panda/llvm/tcg-llvm.cpp#L1194) so it might just be adding the line

```
    __ARITH_OP_COMPUTE(INDEX_op_andc_i64, 64,
            m_builder.CreateAnd(v1, m_builder.CreateNot(v2)))
```
