### ISSUE TITLE
PandaLogReader has empty output

### ISSUE THREAD

**Issue by antverdovsky** [panda-re/panda#185]
I'm a bit confused as to how the PandaLog is used. In the PANDA2 manual, it says that the pandalog reader can be found in `panda/qemu/panda/pandalog_reader.cpp`. Since this doesn't exist in the PANDA2 repository I looked through the PANDA1 repository and I found it. I was able to successfully compile it and I wanted to try it with PANDA2. I ran the following replay, expecting the `tainted_instr` plugin to write the tainted instructions to the log:

`./qemu-system-x86_64 -L /usr/share/qemu -replay catTest -monitor stdio -os linux-32-debian-3.2.81-486 -panda osi -panda syscalls2:profile=linux_x86 -panda osi_linux:kconf_group=debian-3.2.81-486:32 -panda taint2 -panda file_taint:filename=apple.txt,pos=0,first_instr=1 -panda tainted_instr -pandalog catTestLog.plog`

This command generates the following output:

`os_type=2 bits=32 os_details=[debian-3.2.81-486]`
`Adding PANDA arg syscalls2:profile=linux_x86.`
`Adding PANDA arg osi_linux:kconf_group=debian-3.2.81-486:32.`
`Adding PANDA arg file_taint:filename=apple.txt.`
`Adding PANDA arg file_taint:pos=0.`
`Adding PANDA arg file_taint:first_instr=1.`
`max_chunks = 128`
`pandalogging to [catTestLog.plog]`
`Initializing plugin osi`
`[...]`
`./catTest-rr-nondet.log:     5311216 instrs total.`
`catTest:       54609 (  1.03%) instrs.    2.92 sec.  0.27 GB ram.`
`[...]`
`catTest:     5259046 ( 99.02%) instrs.   64.25 sec.  1.25 GB ram.`
`./catTest-rr-nondet.log:  log is empty.`
`Replay completed successfully. 1`
`Time taken was: 66 seconds.`
`Stats:`
`RR_INPUT_1 number = 0, size = 0 bytes`
`RR_INPUT_2 number = 0, size = 0 bytes`
`RR_INPUT_4 number = 1595, size = 22330 bytes`
`RR_INPUT_8 number = 585, size = 10530 bytes`
`RR_INTERRUPT_REQUEST number = 2884, size = 40376 bytes`
`RR_EXIT_REQUEST number = 0, size = 0 bytes`
`RR_SKIPPED_CALL number = 0, size = 0 bytes`
`max_queue_len = 61`
`Replay completed successfully 2.`
`writing chunk 0 of pandalog, 26 / 19 = 1.37 compression, 1 entries`
`header: version=2  dir_pos=93 chunk_size=16777216`

Then I try to open my plog file using the `pandalog_reader`, like so:
`./pandalog_reader catTestLog.plog | head`
and I get the following output:
`unmarshalling chunk 0`
`cs=16777216 ccs=20`
`ret = 0`
`ret =0`

For some reason, the output is essentially empty and I'm not sure if this is because the plog file is not properly created, or if the pandalog_reader is not working correctly. Am I correct in using the pandalog_reader from PANDA1? I also noticed that the `catTestLog.plog` file is only 175 bytes so maybe the replay is not properly writing to the plog file?

**Comment by moyix** [comment]
The C++ pandalog reader has been replaced by one written in Python; you can find it in `panda/scripts/plog_reader.py`.

It does look like your pandalog is just empty, though. In your output, you should see messages like "saw open of file we want to taint" and "applying uniform taint labels 0..4 to buffer". You may want to run file_taint with the "notaint" option just to see what files it sees being opened so that you can verify it does see when you open "apple.txt".

One final thing – if you're using the `-os` option you shouldn't need to explicitly pass the `profile=linux_x86` or `osi_linux:kconf_group=debian-3.2.81-486:32` options.

**Comment by antverdovsky** [comment]
@moyix I do see a `saw open of file we want to taint: [apple.txt] insn ...`, however, I do not see a `applying uniform taint labels`. Am I not using the file_taint plugin correctly?

Also thanks for the `-os` tip, it cleaned up the command a little bit.

**Comment by antverdovsky** [comment]
Also when compiling the `plog_reader.py`, I got an error that I am missing the `plog_pb2` module. I searched for it in the PANDA2 directory and I copied it from the `x86_64-softmmu` (this is the target I'm using) directory into the `scripts` directory. Am I correct in doing this, or is the `plog_pb2` located elsewhere?

**Comment by moyix** [comment]
The `plog_reader.py` script searches around for the plog_pb2 path, though it looks like it may be assuming you're using i386-softmmu:

```
def try_path(*args):
    args = list(args) + ['i386-softmmu']
    build_dir = join(*args)
    if os.path.isdir(build_dir):
        sys.path.append(build_dir)
try_path(panda_dir, 'build')
try_path(panda_dir) 
try_path(dirname(panda_dir), 'opt-panda')
try_path(dirname(panda_dir), 'debug-panda')
import plog_pb2
```

We should probably fix that!

**Comment by antverdovsky** [comment]
Well I think I got it to successfully compile just by moving the `plog_pb2` file into the local `scripts` folder, but I think my issue is the fact that the replay is not being written to the plog file for some reason, even though the `file_taint` plugin captures the opening of the `apple.txt` file.

**Comment by phulin** [comment]
The plog_pb2 script is functionally target-independent, so it shouldn't
matter which one it grabs. If your build directory is in a non-standard
location, you'll need to add the location to PYTHONPATH (I basically just
put the paths that I use in).

**Comment by antverdovsky** [comment]
Thanks for your help guys, I was able to successfully compile and run the plog_reader script. I am able to properly generate a plog file using `tstringsearch` plugin, if I just give it the name of the file, `apple.txt`, it successfully taints the data and tracks it, writing correct output to the plog. For some reason, `file_taint` is able to detect that the file was opened but it doesn't actually seem to taint it and therefore nothing gets written to the plog file... Does anyone know if I am using the plugin incorrectly or something?

**Comment by moyix** [comment]
What program are you running in the guest that reads apple.txt? You may want to modify `file_taint.cpp` and change this line at the top:

`static bool debug = false;`

to

`static bool debug = true;`

In order to turn on more verbose logging.

**Comment by antverdovsky** [comment]
@moyix I'm opening the file using Vi, appending a new line to it and closing it. I'm just doing a simple test but I thought this would be enough to trigger at least some sort of R/W logging from PANDA.

**Comment by bertcug** [comment]
I test file_taint on win7 32bit with 2G RAM，just open a txt file and append a latter, the record is 47s, but the replay process takes me 2707s and 32G RAM to complete. but in ubuntu server, it just took about 2G RAM to complete. is the os with a gui more complex ?
