### ISSUE TITLE
How Can I Get The LLVM Instructions? 

### ISSUE THREAD

**Issue by antverdovsky** [panda-re/panda#187]
Hello,

I was reading the PANDA1 [Starcraft Demo](https://github.com/moyix/panda/blob/master/docs/Starcraft.md) and the document talks about how it is possible to find where in memory a string is being used and then get the assembly instructions which work on the data. I'm confused as to how these instructions were fetched though as the document does not mention how to fetch the instructions from the EBP, EIP, CR3 values returned by the stringsearch plugin. Just from looking at some of the PANDA1 documentation, I'm assuming this is accomplished using the `llvm_trace` plugin and `dynslicer` tool, however I still don't really understand how you can use the `stringsearch` output to get the instructions using this. Furthermore, is this demo possible in PANDA2?

Thanks again for any help.

@moyix I'm tagging you since I saw your "Reverse All the Things with PANDA" presentation where you briefly show the Starcraft demo.

**Comment by moyix** [comment]
You don't need the LLVM trace to see the guest instructions. There are a few alternatives:

* Use the gdb stub (QEMU's `-s` option) to set a breakpoint on the code you want (using the EIP values from stringsearch). Then you can just use `x/i` in gdb to look at the instructions.
* Use QEMU's built-in logging. With `-d in_asm` you will get a disassembly saved to that file every time QEMU translates some guest code.
* Open the binary in IDA Pro / Bianry Ninja / Radare2 and just go to each EIP.
* Write a plugin that disassembles the code for you using something like `capstone`.

The demo is still possible in PANDA2, but you'll have to install Starcraft yourself.

We are planning to bring the LLVM tracing functionality back at some point, but it probably won't help you much for Starcraft.

**Comment by antverdovsky** [comment]
@moyix Thank you very much for your help! I will try these alternatives when I get the chance.
