### ISSUE TITLE
Capturing Connect System Call using SysCalls2

### ISSUE THREAD

**Issue by antverdovsky** [panda-re/panda#191]
Hi everybody,

I want to use PANDA's syscalls2 plugin to capture the [connect](http://man7.org/linux/man-pages/man2/connect.2.html) system call, specifically the `sockaddr` argument of the system call. After looking at the [syscalls2 definitions](https://github.com/panda-re/panda/blob/master/panda/plugins/syscalls2/gen_syscalls_ext_typedefs.h), I saw that the connect system call is only defined for ARM, however, I would like to use it with i386. Is this system call defined for i386, perhaps under a different name, or is it only available for ARM at the moment?

Thanks in advance.

**Comment by moyix** [comment]
x86 Linux doesn't have a specific call for connect, unfortunately. Instead all networking-related calls go through a single system call named `socketcall`. The first argument then specifies the operation type, one of:

```
       SYS_SOCKET        socket(2)
       SYS_BIND          bind(2)
       SYS_CONNECT       connect(2)
       SYS_LISTEN        listen(2)
       SYS_ACCEPT        accept(2)
       SYS_GETSOCKNAME   getsockname(2)
       SYS_GETPEERNAME   getpeername(2)
       SYS_SOCKETPAIR    socketpair(2)
       SYS_SEND          send(2)
       SYS_RECV          recv(2)
       SYS_SENDTO        sendto(2)
       SYS_RECVFROM      recvfrom(2)
       SYS_SHUTDOWN      shutdown(2)
       SYS_SETSOCKOPT    setsockopt(2)
       SYS_GETSOCKOPT    getsockopt(2)
       SYS_SENDMSG       sendmsg(2)
       SYS_RECVMSG       recvmsg(2)
       SYS_ACCEPT4       accept4(2)
       SYS_RECVMMSG      recvmmsg(2)
       SYS_SENDMMSG      sendmmsg(2)
```

The call-specific parameters are then passed in the second argument. You'll have to look through the Linux/glibc source to understand exactly what the various options / parameters are, as I think they're not really publicly documented.

**Comment by antverdovsky** [comment]
Thanks for the reply @moyix. Is the args parameter the virtual memory address of the arguments? So would I have to parse the raw memory into the actual, usable arguments?

**Comment by moyix** [comment]
Correct. You can use `panda_virtual_memory_read` to read the arguments.

**Comment by antverdovsky** [comment]
Is there a good way to convert it into the struct, because if I remember correctly `panda_virtual_memory_read` only reads one byte/char at a time. Do I just have to manually translate the bytes to a memory structure, or is there some panda utility that can do this for me?

**Comment by antverdovsky** [comment]
I think I figured it out, this can be accomplished by just reading to an array of uint8_t using `panda_virtual_memory_rw` and then using `reinterpret_cast` to convert the uint8_t array to whatever arbitrary structure needed. Thanks for your help, @moyix.

**Comment by bertcug** [comment]
does windows have any syscalls to deal with socket operations ?

**Comment by antverdovsky** [comment]
@bertcug I'm not sure of the exact operations but you can find the full list [here](https://github.com/panda-re/panda/blob/master/panda/plugins/syscalls2/gen_syscalls_ext_typedefs.h). Windows system calls start with `on_Nt`.

**Comment by moyix** [comment]
Windows socket system calls are even more of a mess than Linux. All the networking stuff is done using the Windows equivalent of `ioctl` (`NtDeviceIoControlFile`) on various device files like `\Device\Tcp`. You can see some information [in this article](http://www.codemachine.com/article_tdi.html), though I am not sure how up to date it is.
