### ISSUE TITLE
PANDA version 1 and version 2 differences and what's new? 

### ISSUE THREAD

**Issue by hoomanro** [panda-re/panda#192]
We implemented our plugin in PANDA version 1 and we want to know that what are the major changes in new version of PANDA. It seems there is a lot of change but I cannot find any specific document regarding the new features and changes in PANDA version 2.

**Comment by m000** [comment]
This is a good starter:
http://mailman.mit.edu/pipermail/panda-users/2016-November/000535.html

**Comment by hoomanro** [comment]
Is there any update in documentation regarding how to migrate existing plugins from PANDA 1.0 to PANDA 2.0?

**Comment by moyix** [comment]
Unfortunately not – but it should be pretty clear from comparing plugins that are in both v1 and v2, e.g.:

https://github.com/moyix/panda/blob/master/qemu/panda_plugins/asidstory/asidstory.cpp

https://github.com/panda-re/panda/blob/master/panda/plugins/asidstory/asidstory.cpp
