### ISSUE TITLE
New kernel version didn't support

### ISSUE THREAD

**Issue by syjzwjj** [panda-re/panda#203]
When compile kernel info , there's some error 

```
/home/kvm/kernelinfo/kernelinfo.c: In function ‘init_module’:
/home/kvm/kernelinfo/kernelinfo.c:56:132: error: ‘struct thread_info’ has no member named ‘task’
 %s.%s_offset = %d", cfgname, cp_memb(#memb), (int)((void *)&(structp->memb) - (
                                                                     ^
/home/kvm/kernelinfo/kernelinfo.c:98:2: note: in expansion of macro ‘PRINT_OFFSET’
  PRINT_OFFSET(ti_p, task,   "task");
  ^
/home/kvm/kernelinfo/kernelinfo.c:56:132: error: ‘struct vfsmount’ has no member named ‘mnt_parent’
 %s.%s_offset = %d", cfgname, cp_memb(#memb), (int)((void *)&(structp->memb) - (
                                                                     ^
/home/kvm/kernelinfo/kernelinfo.c:138:2: note: in expansion of macro ‘PRINT_OFFSET’
  PRINT_OFFSET(vfsmnt_p, mnt_parent,  "fs");
  ^
/home/kvm/kernelinfo/kernelinfo.c:56:132: error: ‘struct vfsmount’ has no member named ‘mnt_mountpoint’
 %s.%s_offset = %d", cfgname, cp_memb(#memb), (int)((void *)&(structp->memb) - (

```

these structures are removed from vfsmount in the newer kernel , expecially in kernel 4.x.

**Comment by syjzwjj** [comment]
Some plugins rely on it can't properly work.

**Comment by piec** [comment]
The part about `struct vfsmount` is duplicate but not the `struct thread_info` 😊
The `thread_info` structure is not stored at the bottom of the stack anymore and does not reference the current task in linux >= 4.9 (see https://github.com/torvalds/linux/commit/15f4eae70d365bba26854c90b6002aaabb18c8aa#diff-39a48c43ea193781343d2ae594de28cfL552 )

I have just updated `osi_linux` and `kernelinfo` (in our fork) in order to adapt to recent kernels https://github.com/eshard/panda/commit/2a8d097d101157bba2cae98806b54df4d587dcb8
Our fork can only work with newer kernel but `osi_linux` should really be able to use the old or the newer  get_task_struct depending on the target kernel.

**Comment by moyix** [comment]
That's good to know! Also peeking at that fork, it looks like you have support for 64-bit kernels as well? At some point, if you have time, we would love a pull request with your updates `osi_linux`...

As for KASLR, I expected that might be a problem. Volatility has previously solved this for memory dumps:

https://github.com/volatilityfoundation/volatility/pull/385

And we may be able to steal some tricks from that...

**Comment by piec** [comment]
The pull request is on my TODO list :)
I'll take a look at volatility as well.

About 64bit kernel, didn't panda support 64bit kernels already? because I didn't do anything particular for it to work -- or maybe I missed something.

**Comment by moyix** [comment]
Perhaps it always has, and we just never tried to build a 64-bit profile :)

**Comment by m000** [comment]
@moyix I had completely forgotten about @piec's changes. Can you assign this to me so github (hopefully) keeps it where I can see it?

**Comment by moyix** [comment]
Unfortunately it looks like I can't assign it to you because you're not a member of the project – do you want me to add you?

**Comment by m000** [comment]
I wouldn't mind that, but I've also found an alternative. I enabled the issues in my fork, and I can cross reference the issue here: https://github.com/m000/panda/issues/1
Feel free to do the same for any issues that I'd be the right person to have them addressed.

**Comment by nathanjackson** [comment]
@m000 any chance you might get to integrating @piec's changes soon? I've got some upcoming work where it be nice to be able to use the OSI features with a newer kernel.

**Comment by m000** [comment]
I'm working to bring #372 in order these days. I will give it a try after that.

Note however that even if we have support for 64bit linux, `syscalls2` still only supports 32bits. I had tried to fix that on the side of some other changes, but it was trickier than it seemed.
