### ISSUE TITLE
Bad pointer casting `CPUState` and `CPUArchState`

### ISSUE THREAD

**Issue by tathanhdinh** [panda-re/panda#204]
The function [`panda_callbacks_cpu_restore_state`](https://github.com/panda-re/panda/blob/master/panda/src/callback_support.c#L219) has the `env` argument of type `CPUState`, but when it is called at [`cpu_restore_state_from_tb`](https://github.com/panda-re/panda/blob/master/translate-all.c#L349), the passed argument is of type `CPUArchState*`. While there is no safe implicit conversion between these types, trying to use the passed argument will make crash.

A quick fix might be calling

`panda_callbacks_cpu_restore_state(ENV_GET_CPU(env), tb);`

instead of

`panda_callbacks_cpu_restore_state(cpu->env_ptr, tb);`

**Comment by phulin** [comment]
Yep, this is right. Can you submit a PR?
