### ISSUE TITLE
Segfault when using panda through PATH

### ISSUE THREAD

**Issue by Bobo1239** [panda-re/panda#209]
When panda is added to PATH (as e.g. in [the provided Dockerfile](https://hub.docker.com/r/pandare/panda/~/dockerfile/)) and called without the full path, it segfaults when trying to use any plugin. (`qemu-system-x86_64` vs.`/home/bobo1239/panda/build/x86_64-softmmu/qemu-system-x86_64` )

The reason is that [here](https://github.com/panda-re/panda/blob/79d447f166c4381a4e826a98cc92e573b37a94ec/vl.c#L3078) `qemu_file` is set to `NULL` because `realpath("qemu-system-x86_64", NULL)` returns `NULL` (error). When a plugin is then [loaded](https://github.com/panda-re/panda/blob/master/panda/src/callbacks.c#L139), `strdup(NULL)` segfaults.

Apparently there's no cross-platform way to get the real location of an executable (see e.g. https://stackoverflow.com/questions/933850/how-do-i-find-the-location-of-the-executable-in-c) so I'm not sure what the best way to fix this is. I'm also not sure which platforms panda tries support.

Using something like
```
char buff[PATH_MAX];
ssize_t len = readlink("/proc/self/exe", buff, sizeof(buff) - 1);
if (len == -1) {
    error_report("Failed to read /proc/self/exe.");
}
buff[len] = '\0';
qemu_file = buff;
```
(readlinks output is not null-terminated) works on Linux.

**Comment by Bobo1239** [comment]
It appears that the `-llvm` flag and [some others](https://github.com/panda-re/panda/search?utf8=%E2%9C%93&q=gargv&type=) are also affected by this.

**Comment by vigliag** [comment]
+1 I had patched my local copy with something similar, with a (probably useless) fallback to the old method when readlink fails. I'm also not sure what would happen on platforms other than Linux.
```
static char* this_executable_path(const char* argv0){
    char buf[PATH_MAX] = {0};
    ssize_t size = readlink("/proc/self/exe", buf, sizeof(buf));
    if (size == -1 || size == 0 || size == sizeof(buf)) {
        //fallback
        return realpath(argv0, NULL);
    }
    return strdup(buf);
}
```

**Comment by moyix** [comment]
We support Linux and (in theory) OS X, though the latter hasn't been tested in a while as far as I know. If one of you would like to submit a pull request to fix the behavior on Linux (with some appropriate guard that keeps the current behavior on other platforms) I'd be happy to merge it.
