### ISSUE TITLE
Modifying Instructions in a Recording File

### ISSUE THREAD

**Issue by antverdovsky** [panda-re/panda#213]
As far as I understand, and please correct me if I'm wrong, the PANDA recording file stores the TCG instructions that it has recorded from QEMU. Is it possible for me to gain access to these TCG instructions, modify them, and then re-run the replay with the new, modified instructions?

**Comment by moyix** [comment]
No, that's not correct. The record log only stores the non-deterministic events required to drive execution down the same sequence of instructions. The actual instructions are not stored in the log file (this is why the record logs are so compact compared to full instruction traces).

It is also not possible to modify the instructions during a replay; doing so would change the state of the emulator from what was seen at record time, and so the remaining events in the nondeterministic log would no longer match. This means you can't "go live" after changing something in a replay.

You can read more about the record/replay system in our paper:

http://dl.acm.org/citation.cfm?id=2843867

Or in the PANDA manual:

https://github.com/panda-re/panda/blob/master/panda/docs/manual.md#recordreplay-details
