### ISSUE TITLE
Replay: guest instruction counts disagrees

### ISSUE THREAD

**Issue by cmhpass** [panda-re/panda#217]
Hi,

I was playing around with panda and am currently facing some troubles with the replay feature.

This is my setup during recording:
`qemu-system-i386 -monitor stdio -show-cursor -m 512 -netdev user,smb=/media/samba,id=mynet -device rtl8139,netdev=mynet -net nic,vlan=0 -net tap,ifname=tap0,script=/etc/qemu-ifup -drive file=win7.qcow2 -loadvm snapshot1`

The recording was completed successfully but when I try to replay with this command:
`qemu-system-i386 -m 512 -netdev user,smb=/media/samba,id=mynet -device rtl8139,netdev=mynet -net nic,vlan=0 -net tap,ifname=tap0,script=/etc/qemu-ifup -replay myrecording`

I get the following error:

Output 1:
> loading snapshot
> ... done.
> opening nondet log for read :	./592f31-rr-nondet.log
> main-loop: WARNING: I/O thread spun for 1000 iterations
> ./592f31-rr-nondet.log:   948781957 instrs total.
> 592f31:     9487820 (  1.00%) instrs.    4.55 sec.  0.58 GB ram.
> 592f31:    18975640 (  2.00%) instrs.    9.63 sec.  0.60 GB ram.
> 592f31:    28463461 (  3.00%) instrs.   12.32 sec.  0.60 GB ram.
> 592f31:    37951283 (  4.00%) instrs.   14.55 sec.  0.61 GB ram.
> Ahead of log while looking for log entry of type RR_SKIPPED_CALL
> {guest_instr_count=44128097}
> 	RR_INPUT_8 from RR_CALLSITE_IO_READ_ALL
> FOUND DISAGREEMENT!
> Replay program point:
> {guest_instr_count=44128099}
> 
> Record program point:
> {guest_instr_count=44128097}
> 
> guest instruction counts disagree
> 592f31:    44128099 (  4.65%) instrs.   15.98 sec.  0.61 GB ram.
> ERROR: replay failed!
> Time taken was: 21 seconds.
> Stats:
> RR_INPUT_1 number = 0, size = 0 bytes
> RR_INPUT_2 number = 0, size = 0 bytes
> RR_INPUT_4 number = 609, size = 8526 bytes
> RR_INPUT_8 number = 3713, size = 66834 bytes
> RR_INTERRUPT_REQUEST number = 722, size = 10108 bytes
> RR_EXIT_REQUEST number = 0, size = 0 bytes
> RR_SKIPPED_CALL number = 265, size = 854465 bytes
> RR_END_OF_LOG number = 0, size = 0 bytes
> RR_PENDING_INTERRUPTS number = 0, size = 0 bytes
> RR_EXCEPTION number = 0, size = 0 bytes
> max_queue_len = 97
> Checksum of guest memory: 0xb0d2b205
> ERROR: replay failed!
> Aborted (core dumped)

Output2:

> loading snapshot
> ... done.
> opening nondet log for read :	./592f31-rr-nondet.log
> main-loop: WARNING: I/O thread spun for 1000 iterations
> Ahead of log while looking for log entry of type RR_SKIPPED_CALL
> {guest_instr_count=8420731}
> 	RR_INPUT_8 from RR_CALLSITE_IO_READ_ALL
> FOUND DISAGREEMENT!
> Replay program point:
> {guest_instr_count=8420739}
> 
> Record program point:
> {guest_instr_count=8420731}
> 
> guest instruction counts disagree
> 592f31:     8420739 (  0.89%) instrs.    6.66 sec.  0.57 GB ram.
> ERROR: replay failed!
> Time taken was: 9 seconds.
> Stats:
> RR_INPUT_1 number = 0, size = 0 bytes
> RR_INPUT_2 number = 0, size = 0 bytes
> RR_INPUT_4 number = 241, size = 3374 bytes
> RR_INPUT_8 number = 1519, size = 27342 bytes
> RR_INTERRUPT_REQUEST number = 360, size = 5040 bytes
> RR_EXIT_REQUEST number = 0, size = 0 bytes
> RR_SKIPPED_CALL number = 52, size = 5547 bytes
> RR_END_OF_LOG number = 0, size = 0 bytes
> RR_PENDING_INTERRUPTS number = 0, size = 0 bytes
> RR_EXCEPTION number = 0, size = 0 bytes
> max_queue_len = 97
> Checksum of guest memory: 0x86fb75fa
> ERROR: replay failed!
> Aborted (core dumped)

What's interesting is that each time I try to replay with the same command the output seem to differ (Refer to output 1 and output 2). The location of failure seem to differ every time, thus the replay could never reach 100%.

I have done some debugging and testing, this problem seem to occur whenever networking is involved. I have used bridged network in the example above, by bridging tap0 to eth0. If I remove networking, everything seems to work fine.

I have applied this patch to main-loop.c:
https://github.com/panda-re/panda/issues/133#issuecomment-293499444

But it does not seem to solve my problem.

**Comment by vigliag** [comment]
I've had some problems when replaying records which use networking too, replacing my `tap` network device with `user` devices (during replays) seems to help. As long as the `-device` part remains the same, qemu is still able to load up the recordings.

I use this during recording:
```
-netdev tap,ifname=tap_vm1,script=no,id=net1 -device rtl8139,netdev=net1,mac=02:29:07:29:9F:41
```
And change it to this during replay:
```
-netdev user,id=net1 -device rtl8139,netdev=net1,mac=02:29:07:29:9F:41
```

**Comment by moyix** [comment]
I suspect what's happening is that we're not correctly disabling the tap device during replay, which is allowing the tap device to modify guest state during replay, which causes a divergence.

Using the `user` interface is a fine workaround for now, but it would be good to figure out why this is happening and fix it properly.

**Comment by senjitsu** [comment]
I am experiencing a similar issue to the OP, however, I have removed all networking from the equation. 
Running i386 running windows 2000, -cpu pentium3 -m 512 -vga cirrus and three isa-serial com port devices. 

Like the OP, I can roughly record the same interaction, and get different disagreement errors for any given recording replay. The replay command I am using is identical to the normal run. The errors are usually a failed assertion somewhere in rr_log as some form of disagreement. I did originally have networking devices, and multiple HD's, but have tried to reduce to a minimally  complete error reproduction. 

The disagreement is usually pretty early in the replay, maybe 3-8% of the instructions. I have only recently tried debugging it a bit, but its a slow process as I need to refresh my gdb knowledge.

**Comment by moyix** [comment]
@senjitsu, this sounds like a different problem than the ones above. Could you open a new issue? Also, if you are using a system where `rr` is available, you may want to try using `diverge.py`, which records PANDA's recording and replay and then looks for discrepancies between the two, which can help narrow down these kinds of issues.

**Comment by senjitsu** [comment]
#225 Created a new issue. I need to find more info on the RR thing, I have seen it come up before.

**Comment by LauraLMann** [comment]
I am experiencing the same symptoms as @cmhpass (replay crashing due to instruction count disagreement at different places each time).  I am using a bridge network.  The workaround that @vigliag suggested with tap networks (switch from tap to user network) seems to be working with bridge as well.

**Comment by ajgay** [comment]
@LauraLMann @moyix This is definitely still an issue. I'd be up to working on a patch to support TAP/TUN as I will need this down the road. Any suggestions as to where to start, if you have an idea of where to problem resides?

**Comment by KangMing-ux** [comment]
Excuse me, so far, is the solution still just the replacement proposed by @vigliag, because I build the branch softmmu_rethink to record & replay and still get the same error.
