### ISSUE TITLE
Panda compile failing when selecting target-list as "mips-softmmu"

### ISSUE THREAD

**Issue by dan-zingbox** [panda-re/panda#218]
--target-list=x86_64-softmmu,i386-softmmu,arm-softmmu, mips64-softmmu, mips-softmmu

Got this error on:
Linux panda 4.4.0-81-generic #104~14.04.1-Ubuntu SMP Wed Jun 14 12:45:52 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

------

CC      mips64-softmmu/panda/src/callbacks.o

  CC      mips64-softmmu/panda/src/callback_support.o

  CC      mips64-softmmu/panda/src/common.o

/home/danux/panda/panda/src/common.c: In function ‘panda_current_asid’:

/home/danux/panda/panda/src/common.c:111:2: error: #error "panda_current_asid() not implemented for target architecture."

 #error "panda_current_asid() not implemented for target architecture."

  ^

/home/danux/panda/panda/src/common.c: In function ‘panda_current_sp’:

/home/danux/panda/panda/src/common.c:131:2: error: #error "panda_current_asid() not implemented for target architecture."

 #error "panda_current_asid() not implemented for target architecture."

  ^

/home/danux/panda/panda/src/common.c:121:17: error: unused variable ‘env’ [-Werror=unused-variable]

   CPUArchState *env = (CPUArchState *)cpu->env_ptr;

                 ^

/home/danux/panda/panda/src/common.c: In function ‘panda_in_kernel’:

/home/danux/panda/panda/src/common.c:149:2: error: #error "panda_in_kernel() not implemented for target architecture."

 #error "panda_in_kernel() not implemented for target architecture."

  ^

/home/danux/panda/panda/src/common.c:141:18: error: unused variable ‘env’ [-Werror=unused-variable]

    CPUArchState *env = cpu->env_ptr;

                  ^

cc1: all warnings being treated as errors

make[1]: *** [panda/src/common.o] Error 1

make: *** [subdir-mips64-softmmu] Error 2

**Comment by moyix** [comment]
Yep. PANDA is not yet implemented for every architecture QEMU supports. The ones we support are the ones enabled in `build.sh`. We would be very happy if you want to work on a port to MIPS!
