### ISSUE TITLE
Unable to find a source package for qemu

### ISSUE THREAD

**Issue by Manouchehri** [panda-re/panda#219]
Just noticed the Dockerfile is no longer functional. I'll probably fix it myself later, posting this as a reminder.

```
...
Duplicate sources.list entry http://archive.ubuntu.com/ubuntu/ trusty/universe amd64 Packages (/var/lib/apt/lists/archive.ubuntu.com_ubuntu_dists_trusty_universe_binary-amd64_Packages.gz)
W: Duplicate sources.list entry http://archive.ubuntu.com/ubuntu/ trusty/multiverse amd64 Packages (/var/lib/apt/lists/archive.ubuntu.com_ubuntu_dists_trusty_multiverse_binary-amd64_Packages.gz)
W: You may want to run apt-get update to correct these problems
E: Unable to find a source package for qemu
...
```

https://hub.docker.com/r/thawsystems/panda/builds/bvyrv6tkmhdx9gt6bftueez/

**Comment by moyix** [comment]
Hmm. Maybe they got rid of the qemu package and we need to `apt-get build-dep qemu-system` now?

Would definitely appreciate you taking a look!

**Comment by piec** [comment]
@Manouchehri You need to enable the source package repository "deb-src" in your `/etc/apt/sources.list`

**Comment by moyix** [comment]
May be related to this?

https://github.com/tianon/docker-brew-ubuntu-core/issues/84
