### ISSUE TITLE
port to Debian

### ISSUE THREAD

**Issue by Z-Y00** [panda-re/panda#220]
Hi ,
 I'm wondering if you can upgrade the llvm dependence. since the older version of llvm(3.x)will be removed from Debian. 
https://github.com/panda-re/panda/issues/107#issuecomment-225396169
if it is impossible, can you fork the needed llvm to panda.
because if Debian is to remove old llvm, after some while Ubuntu is going to follow up.

**Comment by moyix** [comment]
LLVM 3.3 is required and we can't migrate to a newer version – they removed functionality we depend on (specifically the JIT compiler). We have an Ubuntu PPA that includes the LLVM 3.3, and that may work for you on Debian as well (it's also not too hard to build LLVM 3.3 from source; see the details in [the compile doc](https://github.com/panda-re/panda/blob/master/panda/docs/compile.md#llvm)).

**Comment by Z-Y00** [comment]
https://bugs.kali.org/view.php?id=4321
I posted this to kali, maybe they are able to pack panda,
 sorry that Debian can't pack this.
