### ISSUE TITLE
empty recording when built from source?

### ISSUE THREAD

**Issue by scottcarr** [panda-re/panda#221]
I have been attempting build Panda with an LLVM I compiled myself. Following: https://github.com/panda-re/panda/blob/master/panda/docs/compile.md and panda/build.sh

My build apparently succeeds but when I run `begin_record foo` and `end_record` the recording is apparently empty.  It says: `Checksum of guest memory: 0x00000000`

1) Any idea why it would seemingly build/run without errors but the recording is empty?
2) Is it possible to build a working Panda with LLVM compiled from source?

If I build Panda against the LLVM from the PPA, it works as expected.

**Comment by moyix** [comment]
What makes you think the recording is empty? Are you able to replay it?

**Comment by scottcarr** [comment]
I assumed that if the checksum of memory is 0x00000000, that meant the recording failed because 
I had a replay that had the checksum as 0 and that replay could not be replayed.  I can't find that replay right now.

Now I'm making sure to follow the build instructions exactly.  Still, Panda will report that the guest memory checksum is 0, but the replay is apparently valid.  At least, it appears to replay without errors.

How could the checksum of guest memory be 0?  That seems extremely improbable.  I've noticed that this occurs when I specify the amount of guest RAM to qemu as 4G.

**Comment by moyix** [comment]
It definitely seems very improbable, but if the replay gets to 100% then it almost certainly just means that the memory checksum is broken rather than the replay. Are you able to reproduce this on a clean system (e.g. a docker Ubuntu image)? If not, then I'd suspect some kind of build system breakage...

**Comment by scottcarr** [comment]
I've haven't run into checksum = 0x0 again.  I'm not really familiar with docker, and I've been able to make a bunch of recordings with a i386 guest and < 4 GB of RAM, so I'll close this.
