### ISSUE TITLE
Issue in Migration of plugin from panda 1 - Error while compiling

### ISSUE THREAD

**Issue by rohg** [panda-re/panda#230]
Hi All, 
I am trying to migrate my plugin Faros from PANDA 1 to PANDA 2. I have made all the changes in cpp file. But when I am trying to build it, it is throwing error (attached file ). I think that plugin file faros.cpp couldn't find reference to method called and causing linker error. 

Also attaching Makefile of plugin

[Makefile.txt](https://github.com/panda-re/panda/files/1436172/Makefile.txt)

[error.txt](https://github.com/panda-re/panda/files/1436166/error.txt)

**Comment by moyix** [comment]
Hmm, it's a little difficult to say without seeing the plugin code itself, but it looks like you're including `tcg.h` in your plugin? QEMU's internals changed quite a bit from 1.0.1 (which we based panda1 off of) and the most recent version (which we used for panda2). In general we tried to keep PANDA's APIs mostly the same, but if you were using QEMU APIs and data structures directly, you will have to see what changes they made.

As for the Makefile issues - we have simplified plugin Makefiles quite a bit. You may want to try redoing it along these lines:

https://github.com/panda-re/panda/blob/master/panda/plugins/cppskeleton/Makefile
