### ISSUE TITLE
Recording snapshot vs Scissors snapshot

### ISSUE THREAD

**Issue by cmhpass** [panda-re/panda#232]
This is my QEmu command:
qemu-system-i386 -monitor stdio -show-cursor -m 512 -netdev user,smb=/media/samba,id=net1 -device rtl8139,netdev=net1 -net nic,vlan=0 -net tap,ifname=tap0,script=/etc/qemu-ifup -os windows-32-7 -drive file=win7.qcow2

This is my scissors command:
qemu-system-i386 -monitor stdio -show-cursor -m 512 -netdev user,smb=/media/samba,id=net1 -device rtl8139,netdev=net1 -net nic,vlan=0 -net tap,ifname=tap0,script=/etc/qemu-ifup -os windows-32-7 -replay <recording> -panda "scissors:start=0"

When panda begins recording, it will write a snapshot, lets say snapshot1-snp
After recording, if I were to use Scissors plugin to dump a snapshot at start=0, say snapshot2-snp

The two snapshots have the exact same size but is there a difference between the two snapshots due to the way it is created? 
(snapshot1 is created during recording while snapshot2 is created using snapshot1 + non-det.log)
I am guessing that during replay, certain information about network devices are not initialized because they are not required, thus snapshot2 might be missing some information.

I'm asking this because if I were to load snapshot2 into QEmu and run it again to ping the host, it doesnt have any network connectivity and will hang after a while.

However, I am able to load snapshot1 into QEmu again and everything works fine (I can ping the host) and it doesn't hang.

Is it possible for me to load snapshot2 with network connectivity?

**Comment by moyix** [comment]
I would expect snapshot2 to be missing some information, yes. During replay we don't initialize or run the devices at all, so their state will not be consistent with the code that's executing.

You may be able to figure out the differences with `diff` and some knowledge of the QEMU migration snapshot format, but in general I wouldn't expect this to work.

**Comment by gogolena** [comment]
May I ask you a question? Can you replay the snapshot2-snp successfully?

**Comment by moyix** [comment]
I believe there are currently some bugs in `scissors` that @wangray is currently fixing (see https://github.com/panda-re/panda/pull/236, which should be merged shortly). If you're having trouble with scissors, can you try checking out that pull request and seeing if it works for you?

**Comment by Manouchehri** [comment]
Reference to related answer on the mailing list: http://mailman.mit.edu/pipermail/panda-users/2017-December/000633.html
