### ISSUE TITLE
taint2 plugin overtainting?

### ISSUE THREAD

**Issue by evandowning** [panda-re/panda#233]
I'm having some trouble using the taint2 plugin for PANDA.

In short, it appears to be overtainting significantly for my small c++ test case (below).

```
#include <Windows.h>

int main() {
    HANDLE fh, fh2;

    char content[] = "This is some content.\n";
    DWORD len = 22;
    DWORD written = 0;

    char content2[22];
    DWORD len2 = 0;

    // This creates a file
    fh = CreateFileA("hello.txt",GENERIC_WRITE,0,NULL,CREATE_NEW,FILE_ATTRIBUTE_NORMAL,NULL);
    WriteFile(fh, content, len, &written, NULL);
    CloseHandle(fh);

    // This reads the first file's contents and writes them to a new file
    fh = CreateFileA("hello.txt", GENERIC_READ, 0, NULL, OPEN_EXISTING, FILE_ATTRIBUTE_NORMAL, NULL);
    fh2 = CreateFileA("hello2.txt", GENERIC_WRITE, 0, NULL, CREATE_NEW, FILE_ATTRIBUTE_NORMAL, NULL);
    ReadFile(fh, content2, len, &len2, NULL);
    WriteFile(fh2, content, len2, &written, NULL);
    CloseHandle(fh);
    CloseHandle(fh2);

    return 0;
}
```

I am wanting to taint the **Handle**'s of the API calls mentioned in the test source file (i.e., CreateFile, ReadFile, WriteFile, and CloseHandle).

I'm running a Windows 7 32-bit guest.

I taint each CreateFile call's return value (i.e., EAX register) with different labels and query the Handle parameters within the other API calls (i.e., ReadFile, WriteFile, CloseHandle).

Specifically I'm using the following implementations:
```
// Taints EAX register
taint2_label_reg(R_EAX, 0, label);  // where "label" is a uint32_t
```
```
// Returns labels associated with virt_addr
uint32_t *rv = NULL;

hwaddr pa = panda_virt_to_phys(cpu, virt_addr);
if (pa == (hwaddr) -1) {
    printf ("query_taint_va: virtual addr " TARGET_FMT_lx " not available\n", virt_addr);
    return false;
}

// Determine cardinality of taint set
uint32_t size = taint2_query_ram(pa);

// If it isn't tainted, return empty pointer
if (size == 0) {
    return rv;
}

// Allocate space to hold taint set
rv = (uint32_t *) malloc(sizeof(uint32_t)*size);

// Retrieve taint set
taint2_query_set_ram(pa,rv);

return rv;
```

I expect to see three different labels for the tuples (Create,Write,Close), (Create,Read,Close), and (Create,Write,Close), however I'm getting intermixed labels.

For example, I see the taint label I applied to the first Create being passed to the other Read, Write, and two Close calls.

Attached are three outputs of my debugging attempts.
[out-taint-apis-normally.txt](https://github.com/panda-re/panda/files/1451604/out-taint-apis-normally.txt)
[out-just-taint-first-createfile.txt](https://github.com/panda-re/panda/files/1451610/out-just-taint-first-createfile.txt)
[out-remove-taint-after-close.txt](https://github.com/panda-re/panda/files/1451609/out-remove-taint-after-close.txt)

Each extra line printed to stdout shows the following:
```
    application.exe: CreateFile Handle Filename
            taint label applied (and queried to double-check)
    application.exe: OtherAPI VirtualAddress Handle
            tainted with label(s)
```

I tried also tainting the corresponding Native API calls (i.e., NtCreateFile, NtReadFile, etc.) but got identical results as described above.

Am I using the taint2 plugin incorrectly or is this potentially a bug?

Thanks,
Evan

**Comment by vigliag** [comment]
I'm not that familiar with taint2 myself to spot if that's a bug or the intended behavior, but I'm also having some issues with the taint2 plugin overtainting. Unfortunately I haven't been able to reproduce my problem on a smaller testcase (oversimplifying, I'm tainting buffers after a syscall ends, then doing other stuff with other syscalls, then checking an output buffer is tainted correctly).

Something it might be worth trying is disabling tainted pointer with `-panda 'taint2:no_tp=true'`. It should taint far less data (you're tainting pointers after all), and may give you different results.

**Comment by evandowning** [comment]
This solution did work for me. The three tuples mentioned above now all have the different labels I expect. Thanks @vigliag :)
I was sure I had tried this solution before, but apparently I had not.

My reasoning behind why I did not enable this flag was because I thought it would reduce tainting accuracy if I did not taint pointers. Though I admit I'm limited in my knowledge of taint analysis.

I'll mark this issue as closed. If I find any more of my unit tests do not taint as I expect, I'll repost here and we can continue this discussion. Hopefully it will help your issue as well.

Cheers,
Evan

**Comment by moyix** [comment]
Tainted pointer covers the following case: if you dereference a pointer that is tainted, should the result be tainted? For example, suppose you have

`x = foo[i]`

where `i` is tainted (but `foo[i]` is *not* tainted) – should `x` be tainted? There isn't really a right answer, so we made it configurable.

**Comment by evandowning** [comment]
Yeah, I understand this better now.

As I think about it more it doesn't make sense to taint across dereferencing pointers for my particular use-case.

Thanks for all of your help.
