### ISSUE TITLE
replay failure when --usbdevice tablet is used during recording

### ISSUE THREAD

**Issue by StablelJay** [panda-re/panda#234]
I use Debian _7.0_i386 OS as VM but when I try to test the record and replay function, it failed to replay.
The reason is
qemu-system-i386: Unknown savevm section or instance '0000:00:01.2/uhci' 0
Failed to load vmstate
Failed to start replay
It could work well with Ubuntu and win_7 OS, could anyone offer some advice for this problem?
Could Panda2.0 support Debian OS well or not?
when I use record function
![_001](https://user-images.githubusercontent.com/18350996/32685488-38a0fba8-c6cd-11e7-83da-d8d126b79c21.png)

Then I try to replay, but it couldn't work.
![_002](https://user-images.githubusercontent.com/18350996/32685479-0ffbe88e-c6cd-11e7-95fd-7bebd7541ac6.png)

**Comment by moyix** [comment]
Do you get the same failure if you include the `--usbdevice tablet` argument when replaying?

**Comment by StablelJay** [comment]
I try to include  **`--usbdevice tablet`** when replaying. It could replay at first, but then it failed. 
![_003](https://user-images.githubusercontent.com/18350996/32695191-6a5e4606-c78f-11e7-886e-f408c9a9dadb.png)
Then I try not to include `--usbdevice tablet` when I record the trace, I could replay successfully. Perhaps replay function doesn't work well with `--usbdevice tablet`.

**Comment by moyix** [comment]
It sounds like that is the case – it would be good to track down why this is the case...

**Comment by MarkMankins** [comment]
I'm curious if this is still an issue.  I've been making recordings and replays using the "-usbdevice tablet" argument without encountering any issues.

**Comment by moyix** [comment]
It's possible that one of the recent fixes to the record/replay infrastructure has also fixed this! I'll close for now, thanks for checking on it.
