### ISSUE TITLE
Does panda require source code of a software in order to run analysis?

### ISSUE THREAD

**Issue by ericyey** [panda-re/panda#239]
Does panda require source code of a software in order to run analysis? Or only binary code format is enough?

**Comment by vigliag** [comment]
No, it doesn't require the source code. Panda takes advantage of QEMU's tcg (QEMU's "slow", not hardware-accelerated mode) to instrument and observe the code while it's running. You can also obtain the LLVM intermediate representation of the code that it's being executed, and add your own instrumentation to it.
