### ISSUE TITLE
the analysis result after using "scissors" plugin is different from the original one

### ISSUE THREAD

**Issue by gogolena** [panda-re/panda#250]
I have a plugin ( let's call it "**myplugin**", it is used to record the execution trace ) to perform analysis on the replayed execution, but it is too slow. So I think of using "**scissors**" plugin to extract two subsets of the replay.

The original replay file is “_origin-rr-snp, origin-rr-nondet.log_”, its total instruction number is 700000000. Then I used “`-panda scissors: name=subset1, start=0, end=350000000`” and got “_subset1-rr-snp, subset1-rr-nondet.log_”. Similarly, I set “`-panda scissors: name=subset1, start=350000000, end=700000000`” and got “_subset2-rr-snp, subset2-rr-nondet.log_”.

Then I use “**myplugin**” to perform analysis on “_origin-rr-snp, origin-rr-nondet.log_”, and get an execution trace ( let’s call it **ET** ). In the same way, I get an execution trace ( **ET1** ) through “_subset1-rr-snp, subset1-rr-nondet.log_” and get another execution trace ( **ET2** ) through “_subset2-rr-snp, subset2-rr-nondet.log_”.

By comparison, **ET1** exactly matches the front part of **ET**, but **ET2** does not match the latter part of **ET**.

I drew a picture here to help you understand what I said.
![image](https://user-images.githubusercontent.com/23730377/34549252-51e470dc-f142-11e7-939b-db67d4216030.png)

I don’t know why **ET2** is different. This problem has troubled me for a long time as it is not supposed to be like this. Hope someone can give me some advice. Thanks.

**Comment by moyix** [comment]
Because of the way scissors works, it can't always start and stop on the *precise* instruction you specify (it only checks at basic block boundaries). However, ET2 *should* be a subset of ET.

**Comment by gogolena** [comment]
I known the basic block boundry, so I adjust the start instruction of ET2. But, what puzzles me is ET2 has never been a subset of ET. ET2 is quite different from latter part of ET, and will missing some information.

But ET1 is always a subset of ET.

Is it because "scissors" plugin cannot be used to do this kind of analysis? But why the first part (ET1) is right?

**Comment by moyix** [comment]
Could you provide an example replay, along with your tracing plugin?

**Comment by gogolena** [comment]
Sure. I've send you a email, thank you very much.

**Comment by gogolena** [comment]
Sorry,  I sent the example replay and tracing plugin to your email - brendandg@nyu.edu, but you haven't replied me yet. Is it because I sent to the wrong email? Could you tell me how to send those files to you? Thanks.

**Comment by gogolena** [comment]
I have sent those files again using my hotmail just now,  have you received it? 
Or, maybe you can download them through the following link: https://1drv.ms/u/s!AmQRaBXntMUXg3vY0OVxDXvTYo_n

**Comment by moyix** [comment]
Yep, finally got it – thanks for being persistent! I'll have a look as soon as I can.

**Comment by gogolena** [comment]
Thanks, and if there are any questions you can contact me by email - anxinbuzi1994@outlook.com
