### ISSUE TITLE
plugin error

### ISSUE THREAD

**Issue by cat998** [panda-re/panda#252]
what should I do with the problem "os_intro.c:147: init_plugin :Assertion ‘！（panda_os_type == OST_UNKNOWN）’ failed"?

**Comment by moyix** [comment]
That means that the plugin was expecting you to specify the guest OS using the `-os` command line option. For Windows, the supported options are "windows-32-7", "windows-32-xpsp2", and "windows-32-xpsp3". For Linux many versions are supported, but you need to create a configuration entry for your specific kernel version. Details on how to do that can be found here:

https://github.com/panda-re/panda/blob/master/panda/plugins/osi_linux/USAGE.md

**Comment by cat998** [comment]
@moyix Thanks to your help, I've solved this problem.I have another question,I want to get the control flow of one particular process，should i judge the Pid before analysis each instruction，or there is a better way to do it?

**Comment by moyix** [comment]
It's probably more efficient to use the `PANDA_CB_ASID_CHANGED` callback, which will notify you each time the address space changes -- this indicates that it has switched from one process to the next. You should be able to check the current process from within that.

**Comment by cat998** [comment]
@moyix thanks for your advice,I'll try it.emm,one more problem,my mouse right-click doesn't work in qemu pc(all windows version) while it work in my host pc(ubuntu).
I guess the guest pc doesn't receive the right-click event(or handle it as other event).
my command is:" ~$ /panda/x86_64-softmmu/qemu-system-x86_64  /windows64.qcow2 -enable-kvm -m 2048 --monitor stdio" 
did I miss some args in the command or missing some configuration with my qemu？
