### ISSUE TITLE
taint2_labels_applied not implemented

### ISSUE THREAD

**Issue by m000** [panda-re/panda#256]
[taint2/USAGE.md](https://github.com/panda-re/panda/blob/a680657b7bab438f1bb6e6254c3624a53c2dcadc/panda/plugins/taint2/USAGE.md) mentions of a `taint2_labels_applied()` API call. However, this does not seem to be implemented.

**Comment by AndrewFasano** [comment]
This got removed from the docs at some point in the past. @m000 do you think we need whatever that function was doing? Or should we close this now that the docs are no longer wrong?
