### ISSUE TITLE
qemu-system-x86_64: Configuration section missing

### ISSUE THREAD

**Issue by GucciBawler** [panda-re/panda#265]
When running the command _x86_64-softmmu/qemu-system-x86_64 -m 1024 -replay record_ I get an error: _qemu-system-x86_64: Configuration section missing_. Anyone knows how to get the configuration right?

**Comment by m000** [comment]
Are you still in need of help here? If yes, it would help to provide some up to date information regarding your guest OS. Otherwise, just close the issue.

**Comment by moyix** [comment]
I'll close – please re-open if you are still having trouble!
