### ISSUE TITLE
Segmentation fault in file_taint and tainted_branch

### ISSUE THREAD

**Issue by davega996** [panda-re/panda#269]
Hello, i wanted to create a simple analysis with file_taint and tainted_branch but always runs into a segmentation fault error even before the tainting starts it seems

```
~/panda/build/x86_64-softmmu/qemu-system-x86_64 -replay ~/Records/record_calculator_five_computation -m 2G -os windows-32-7 -panda syscalls2:profile=windows7_x86 -panda callstack_instr -panda file_taint:first_instr:131811493,pos,filename=calc.exe -panda tainted_branch 
os_familyno=1 bits=32 os_details=[7]
PANDA[syscalls2] - adding argument profile=windows7_x86.
PANDA[file_taint] - adding argument first_instr:131811493.
PANDA[file_taint] - adding argument pos.
PANDA[file_taint] - adding argument filename=calc.exe.
Initializing plugin syscalls2
syscalls2: using profile for windows 7 x86 32-bit
Initializing plugin callstack_instr
Initializing plugin file_taint
taint_filename = [calc.exe]
positional_labels = 1
no_taint = 0
end_label = 1000000
first_instr = 0 
panda_require: osi
Initializing plugin osi
OSI grabbing Windows introspection backend.
panda_require: win7x86intro
Initializing plugin win7x86intro
panda_require: wintrospection
Initializing plugin wintrospection
panda_require: syscalls2
panda_load_plugin: /home/davega/panda/build/x86_64-softmmu/panda/plugins/panda_syscalls2.so already loaded
panda_require: wintrospection
panda_load_plugin: /home/davega/panda/build/x86_64-softmmu/panda/plugins/panda_wintrospection.so already loaded
panda_require: taint2
Initializing plugin taint2
taint2: Propagating taint through pointer dereference ENABLED
taint2: taint ops inlining DISABLED
panda_require: callstack_instr
panda_load_plugin: /home/ubuntuForPanda/panda/build/x86_64-softmmu/panda/plugins/panda_callstack_instr.so already loaded
taint2: taint2_enable_taint
taint2: Allocating small fast_shad (0 bytes) using malloc @ 562b681f7b90.
taint2: Allocating small fast_shad (12800000 bytes) using malloc @ 7f61e665e010.
taint2: Allocating small fast_shad (256 bytes) using malloc @ 562b681f8920.
taint2: Allocating small fast_shad (2048 bytes) using malloc @ 562b681f90e0.
taint2: Allocating small fast_shad (685568 bytes) using malloc @ 7f61e65b6010.
taint2: LLVM optimizations DISABLED
taint2: Linking taint ops from /home/davega/panda/build/x86_64-softmmu/panda/plugins/panda_taint2_ops.bc
taint2: Done initializing taint transformation.
Segmentation fault (core dumped)
```

I attached the snp file and the non-deterministic log file 
https://www.dropbox.com/s/n9m5575e19o4i6q/record_calculator_five_computation-rr-nondet.log?dl=0

https://www.dropbox.com/s/jr7ls84g2tsu3aq/record_calculator_five_computation-rr-snp.zip?dl=0

**Comment by moyix** [comment]
In your command line, `first_instr:131811493` should be `first_instr=131811493`. Currently it's getting set to the default value of 0, which tries to turn on taint at the very beginning of the replay, before (e.g.) RAM is available – this is something we should fix!

**Comment by m000** [comment]
@moyix I have some changes on my fork for the taint2 plugin that delay allocation of shadow memory until `taint2_enable_taint` is called. I will send a PR soonish.

**Comment by moyix** [comment]
@m000 You may want to have a look at this commit too? It adds a callback just after the machine is initialized but before any code runs, so it should be a safe place to do any kind of taint initialization. https://github.com/panda-re/panda/commit/20b6596ec9c67bdcbe7e91195e061669fe3f1920

**Comment by m000** [comment]
@moyix Already using it :-)

**Comment by davega996** [comment]
Sorry for the late response,  it works now but I encountered a new problem,  the analysis seems to terminate suddenly for some reason in midst of the analysis, simply outputs "Killed". So when I tried to view the result using plog_reader.py, the output is empty
[calculatorFileTaint.txt](https://github.com/panda-re/panda/files/1801081/calculatorFileTaint.txt)

**Comment by moyix** [comment]
`Killed` probably means you ran out of memory. Have a look at `dmesg` to confirm. Unfortunately taint analysis is quite memory-hungry. If possible, try lowering the amount of RAM you give the VM and re-recording.

**Comment by davega996** [comment]
Is there a way to calculate the system requirement of taint analysis in PANDA, with respect to the recording maybe? Currently I am running PANDA on a Ubuntu VMWare guest system with 20GB out of 24GB available in the host  Windows 7 system. My host system has an i7 3770 3.4GHz processor and I give the guest system 2 processor core.

In my last try I give the Windows 7 guest system running in my PANDA 256MB of memory and for the analysis of the recording I also give 256MB of memory, which still results in the oom-killer being invoked when viewing dmesg.

[dmesg log.txt](https://github.com/panda-re/panda/files/1832058/dmesg.log.txt)
