### ISSUE TITLE
panda for android

### ISSUE THREAD

**Issue by acaciaworld80** [panda-re/panda#276]
Do panda2 support android emulator cause i try to run it with pandroidconverted.py and runandroid.py just like the instruction and just get a black screen from the qemu emulator, i'm using android with api version 24, i can do telnet connection to the emulator but everytime i sent command it got crashed

command:

telnet 127.0.0.1 5554
Trying 127.0.0.1...
Connected to 127.0.0.1.
Escape character is '^]'.
Android Console: type 'help' for a list of commands
OK
help
Android console command help:

    help|h|?         print a list of commands
    event            simulate hardware events
    geo              Geo-location commands
    gsm              GSM related commands
    kill             kill the emulator instance
    power            power related commands
    quit|exit        quit control session
    redir            manage port redirections
    sms              SMS related commands
    qemu             QEMU-specific commands
    sensor           manage emulator sensors

try 'help <command>' for command-specific help
OK
event
allows you to send fake hardware events to the kernel

available sub-commands:
    send             send a series of events to the kernel
    types            list all <type> aliases
    codes            list all <code> aliases for a given <type>
    text             simulate keystrokes from a given text

KO: missing sub-command
event text 1234
Connection closed by foreign host.

the log file:

(process:25382): GLib-WARNING **: /build/glib2.0-prJhLS/glib2.0-2.48.2/./glib/gmem.c:483: custom memory allocation vtable not supported
emulator: registered 'boot-properties' qemud service
emulator: Adding boot property: 'dalvik.vm.heapsize' = '48m'
emulator: Adding boot property: 'qemu.sf.fake_camera' = 'both'
emulator: Adding boot property: 'qemu.hw.mainkeys' = '0'
goldfish_add_device: goldfish_device_bus, base ff001000 1000, irq 1 1
goldfish_device_bus: ff001000	 30
goldfish_add_device: goldfish_int, base ff000000 1000, irq 0 0
goldfish_int: ff000000	 38
goldfish_add_device: goldfish_timer, base ff003000 1000, irq 3 1
goldfish_timer: ff003000	 40
goldfish_add_device: goldfish_rtc, base ff010000 1000, irq 10 1
goldfish_rtc: ff010000	 48
goldfish_add_device: goldfish_tty, base ff002000 1000, irq 4 1
goldfish_tty: ff002000	 50
android_arm_init serial 1 2d5c080
serial_hds: 1
goldfish_add_device: goldfish_tty, base ff011000 1000, irq 11 1
goldfish_tty: ff011000	 58
android_arm_init serial 2 0
android_arm_init serial 3 0
goldfish_add_device: smc91x, base ff012000 1000, irq 12 1
goldfish_add_device: goldfish_fb, base ff013000 1000, irq 13 1
goldfish_fb: ff013000	 70
goldfish_add_device: goldfish_mmc, base ff005000 1000, irq 14 1
goldfish_mmc: ff005000	 78
goldfish_add_device: goldfish_memlog, base ff006000 1000, irq 0 0
goldfish_memlog: ff006000	 80
goldfish_add_device: goldfish-battery, base ff014000 1000, irq 15 1
goldfish-battery: ff014000	 88
goldfish_add_device: goldfish_events, base ff015000 1000, irq 16 1
goldfish_events: ff015000	 90
Using event IRQ
Invalid system partition size for non-QCOW image: 0emulator: geometry says there are 4194304 blocks

emulator: Dev size of ./system-pandroid.qcow2 is 80000000

Invalid data partition size for non-QCOW image: 0emulator: Dev size 0x0 came from argument

emulator: geometry says there are 1638400 blocks

emulator: Dev size of ./data-pandroid.qcow2 is 32000000

emulator: Dev size 0x0 came from argument

emulator: geometry says there are 135168 blocks

emulator: Dev size of ./cache-pandroid.qcow2 is 4200000

goldfish_add_device: goldfish_nand, base ff016000 1000, irq 17 1
goldfish_nand: ff016000	 98
goldfish_add_device: qemu_pipe, base ff017000 2000, irq 18 1
qemu_pipe: ff017000	 a0
emulator: control console listening on port 5554, ADB on port 5555
emulator: sent '0012host:emulator:5555' to ADB server
emulator: Realistic sensor emulation is not available, since the remote controller is not accessible:
 Success

thank you

**Comment by moyix** [comment]
PANDA 2.0 doesn't support Android emulation, no. It would be a pretty large amount of work to port over the necessary devices from the Android emulator – if you'd like to take on the task I'm sure it would be greatly appreciated, but we just don't have time.
