### ISSUE TITLE
TAINT2_DEBUG

### ISSUE THREAD

**Issue by MarkMankins** [panda-re/panda#286]
A recent change to the taint2 plugin Makefile defines the preprocessor symbol TAINT2_DEBUG.

If TAINT2_DEBUG is defined, taint2_enable_taint() attempts to create a file named /tmp/llvm-mod.bc.  If this file cannot be created, analysis aborts.

Should TAINT2_DEBUG be enabled by default?  If so, are there any dependencies on the filename that is passed to tcg_llvm_write_module() (taint2.cpp - line 179)?  If not, maybe we can do something to make the filename less likely to collide with an existing file?

**Comment by moyix** [comment]
Nope, that shouldn't be enabled by default. Thanks for letting us know.
