### ISSUE TITLE
fatal error: wireshark/config.h: no such file or directory compilation terminated

### ISSUE THREAD

**Issue by Kyomian** [panda-re/panda#299]
When compiling, I encounter this fatal error. Checked network.cpp under panda/plugins/network and realised that it included <wireshark/config.h>

How do I go about fixing this error?

**Comment by moyix** [comment]
You need to install `libwiretap-dev` and `libwireshark-dev`. These were recently added as dependencies (and are included automatically if you use `install_ubuntu.sh`) but if you upgraded from an older version of PANDA you'll need to get them.
