### ISSUE TITLE
Dynamic taint analysis for x86-64 and stdin support

### ISSUE THREAD

**Issue by BrieflyX** [panda-re/panda#300]
Noting that there is a comment in `taint_debian.py` script

```
# this only works for this arch (for now)
assert (arch_data.dir == 'i386-softmmu')
```

Does it mean panda haven't support taint for x86-64 yet? Will those implementations be developed in the future?

Also, I notice there seems no support for stdin input

```
# replay to figure out where to turn on taint
if stdin:
    raise ValueError("Actually, stdin taint not working?")
else: 
    # file input
    panda_args.extend(["-panda", "file_taint:filename=%s,notaint=y" % fileinput])
```

Does it mean we are only able to taint our input by given a file?

**Comment by m000** [comment]
Taint for x86_64 should be supported AFAIK. The i386 limitation must originate from the use of osi_linux by file_taint.

However, after the merge of #227, this limitation of osi_linux may no longer be relevant. But someone needs to try this to make sure.
