### ISSUE TITLE
After insn exec callback

### ISSUE THREAD

**Issue by leowweixiang** [panda-re/panda#304]
Hello, this is an idea rather than an issue. I'm writing something where I have to check the cpu state before and _after_ certain instructions are executed, similar to the callstack_instr plugin. To get the latter I'm doing the following: return true on insn_translate, then on insn_exec I set a flag if it is the kind of instruction I am looking for. On the next insn exec, if the flag is set, check the new cpu state. I don't know what the next instruction is, that's why I returned true for every translation.

This is very slow, so I am wondering if there are any better suggestions that let me filter immediately on insn_translate. I thought of fiddling with the callback code but am not confident of it, especially for insn_exec. Where should I look at if I were to modify it?

**Comment by moyix** [comment]
Yes, I think we probably do want an `after_insn_exec` callback! Right now the `insn_exec` callback is implemented in these places:

* During translation, we check the translate callback before translating each instruction and see if any of the callbacks return true. If so, we generate a call to a helper function that will run the exec callbacks: https://github.com/panda-re/panda/blob/master/target/i386/translate.c#L8485-L8488 (there is similar code in `target/arm` and `target/ppc`).
* The helper itself just does what you expect: loops over the registered `insn_exec` callbacks and invokes each one: https://github.com/panda-re/panda/blob/master/panda/include/panda/helper_impl.h It needs to be declared as a helper using QEMU's `DEF_HELPER` macro: https://github.com/panda-re/panda/blob/master/panda/include/panda/helper_defs.h
* It needs an enum (https://github.com/panda-re/panda/blob/master/panda/include/panda/plugin.h#L38-L39) and a function prototype (https://github.com/panda-re/panda/blob/master/panda/include/panda/plugin.h#L147-L185) declared in `panda/include/panda/plugin.h`

So, hopefully these things will help you implement an `after_exec` (and maybe `after_translate`?) callback. And if you do and find it's useful to you, please consider submitting a pull request!

**Comment by leowweixiang** [comment]
Hi moyix, thanks for the feedback. I've added the second and third points. The first however I don't know where to put the new gen_helper. I did the following:


    bool insn_trans = panda_callbacks_insn_translate(ENV_GET_CPU(env), pc_ptr);
    // PANDA: ask if anyone wants execution notification
    if (insn_trans) {
        printf("translate: before\n");
        gen_helper_panda_insn_exec(tcg_const_tl(pc_ptr));
    }
    target_ulong prev_pc_ptr = pc_ptr;
    pc_ptr = disas_insn(env, dc, pc_ptr);
    if (insn_trans) {
        printf("translate: after\n");
        gen_helper_panda_after_insn_exec(tcg_const_tl(prev_pc_ptr));
    }

In helper_impl.h:

    #include "panda/plugin.h"

    void helper_panda_insn_exec(target_ulong pc) {
        printf("helper: before\n");
        // PANDA instrumentation: before basic block
        panda_cb_list *plist;
        for(plist = panda_cbs[PANDA_CB_INSN_EXEC]; plist != NULL; plist = panda_cb_list_next(plist)) {
            plist->entry.insn_exec(first_cpu, pc);
        }
    }
    void helper_panda_after_insn_exec(target_ulong pc) {
        printf("helper: after\n");
        // PANDA instrumentation: after basic block
        panda_cb_list *plist;
        for(plist = panda_cbs[PANDA_CB_AFTER_INSN_EXEC]; plist != NULL; plist = panda_cb_list_next(plist)) {
            plist->entry.insn_exec(first_cpu, pc);
        }
    }

    #endif


"translate: after" is printed but not "helper: after", the registered after_insn_exec never gets called

**Comment by HighW4y2H3ll** [comment]
Ahh, just found out this open issue. Is there any PR for this? I'm kinda half way there and probably duplicated. :) #336
