### ISSUE TITLE
load_plugin: arguments with whitespace

### ISSUE THREAD

**Issue by leowweixiang** [panda-re/panda#305]
Hello, I have the following problem. I can do the following when launching PANDA: "-panda plugin:string=a b c d e". However when trying to do "load_plugin plugin string=a b c d e" in the monitor during emulation, the whitespaces cause a parsing error. Currently I've worked around it using "string=a|b|c|d|e" and replacing the delimiters during init_plugin, but is there is a better solution?

**Comment by moyix** [comment]
Hmm, does `load_plugin plugin "string=a b c d e"` work?

**Comment by leowweixiang** [comment]
Yes it does! Thanks!
