### ISSUE TITLE
Difference between AFTER_BLOCK_TRANSLATE and BEFORE_BLOCK_EXEC?

### ISSUE THREAD

**Issue by Kyomian** [panda-re/panda#307]
So, basically, I need to get the eip at the start of a block.

But `tb->pc` at `AFTER_BLOCK_TRANSLATE` and `tb->pc` at `BEFORE_BLOCK_EXEC` are different, so I do not know which `pc` points at the start of a block.

So, what's the difference between the two?

**Comment by moyix** [comment]
`AFTER_BLOCK_TRANSLATE` is called after qemu *translates* a block of code – if you want to get `eip` when the block is executed you want `BEFORE_BLOCK_EXEC`.

**Comment by Kyomian** [comment]
@moyix Thank you for the reply and patience. I have a follow-up question: A block that has been _translated_ **will** be executed right? Or are there cases in which translated blocks will not be executed?

**Comment by moyix** [comment]
Generally QEMU translates a single block and then executes it right afterward. However, I believe in between translation and execution it *can* be interrupted (e.g., by a hardware interrupt) – and in this case it's possible that the block won't end up getting executed right away.

In addition, once a block is translated, it gets cached, so it may be executed many times without being translated again.
