### ISSUE TITLE
Network Taint Questions

### ISSUE THREAD

**Issue by LauraLMann** [panda-re/panda#308]
We'd like to implement network taint, but have a few questions.
First, I noticed that the taint shadow in taint1 for io (which network taint uses) is a SdDir64, as were several other shadows.  In taint2, the shadows (at least the ones that are actually used) have become FastShads.  Is there a reason the io shadow was not updated to be FastShad in taint2, or should the io shadow also become a FastShad once the port is complete?  (I can't find any documentation that tells me what the intention was for the person doing the original port.)
Second, the taint2 documentation mentions that the preferred arrangement is to have taint2 just deal with taint propagation, and have separate plugins be used for introducing taint, and for querying taint (unlike in taint1 where, at least for network taint, that was all handled in the taint plugin itself).  If we went the separate plugins route, I think we would need to add taint2 API to introduce network taint and to query for it.  There was never any API for dealing with the IO shadow, so I'm not sure if creating API to add and query for IO taint is considered an appropriate thing to do.  Would it expose too many internals to downstream plugin writers to add such API?
Thanks.

**Comment by LauraLMann** [comment]
Given the comments on @nathanjackson 's refactoring of the shadows to implement hard drive taint, I think that part of my question above is answered - use Nathan's shadows.
That just leaves the question about where to put the various network taint related activities in the plugins:
PANDA_CB_REPLAY_HANDLE_PACKET, if it was separate from taint2, would require an API be added to apply a label in the IO shadow, and to query the IO shadow for taint.  I wasn't sure this would fit with the decisions of others on how much of the taint internals to expose to downstream plugins.  But, it would provide a natural place to add additional options like how wordy you want the taint query output to be.
PANDA_CB_REPLAY_NET_TRANSFER (and PANDA_CB_REPLAY_BEFORE_DMA I think too) seem to fit more naturally in the taint2 plugin itself, as (like in the old taint) I envision them always propagating taint, even if the options to label incoming traffic or query outgoing traffic aren't on.
But more knowledgable parties are welcome to redirect me.

**Comment by LauraLMann** [comment]
oops, just meant to comment, not close

**Comment by moyix** [comment]
I think adding APIs specifically for network taint to `taint2` is fine. We already have specific APIs to query and set labels on RAM and registers, so this seems like a natural extension of those APIs. Unfortunately I'm not very familiar with how things look on the network taint side of things – how would one specify a network taint source to label or a sink to query?

**Comment by LauraLMann** [comment]
A PANDA_CB_HANDLE_PACKET call is made for PANDA_NET_RX when a packet is received.  If interested, one can then apply taint to the io shadow for the buffer address specified.
A PANDA_CB_HANDLE_PACKET call is made for PANDA_NET_TX when a packet is about to be sent out.  If interested, one can query the IO shadow for the address specified to see if any tainted data is about to be sent out.

**Comment by moyix** [comment]
OK, that sounds like a great place to do it then!

**Comment by LauraLMann** [comment]
As #341 has been accepted, this issue can be closed.
