### ISSUE TITLE
i386: xmm registers off

### ISSUE THREAD

**Issue by leowweixiang** [panda-re/panda#314]
Hello, I was running some instructions and noticed that the xmm registers were 16 bytes off. Here is the code and a sample (eax = 3857049061) :

Code

    int exec_callback(CPUState * env, target_ulong pc) {
    ...
    CPUX86State* _env = ((CPUX86State*)env->env_ptr);
    printf("%s\n", disasm);
    printf("%p: ", &(_env->xmm_regs[0]));
    for (uint8_t j = 0; j < 16; j++) {
        printf("%lu ", _env->xmm_regs[0].ZMM_L(j));
    }
    printf("\n");
    printf("%p: ", (char*) _env->xmm_regs - 16);
    char * a = (char *)_env->xmm_regs - 16;
    ZMMReg* z = (ZMMReg *) a;
    for (uint8_t j = 0; j < 16; j++) {
        printf("%lu ", z->ZMM_L(index));
    }
    printf("\n");

Sample

    movd	xmm0, eax
    0x55f7ff226478: 0 0 0 0 0 0 0 0 0 0 0 0 4294967295 4294967295 0 771929684 
    0x55f7ff226468: 3857049061 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0

**Comment by moyix** [comment]
Are you sure this is a bug? the `xxm_regs` array is defined as an array of `ZMMReg`s, each of which represents a 512-bit register – couldn't this just be a result of how QEMU has decided to lay that register out internally?

**Comment by leowweixiang** [comment]
Hi, I think it's an issue with this QEMU than the panda instrumentation, but in case anyone needs to retrieve the xmm registers' data in their plugin, this is how they have to get it instead of calling xmm_regs[i]

**Comment by moyix** [comment]
If this is a bug in QEMU, it should probably be reported upstream, and then we can pull their changes in.
