### ISSUE TITLE
where is makefile.example?

### ISSUE THREAD

**Issue by cat998** [panda-re/panda#327]
I need makefile.example to learn how to write panda plugin,but can not find it.

**Comment by m000** [comment]
How about these?

https://github.com/panda-re/panda/tree/master/panda/plugins/cppskeleton
https://github.com/panda-re/panda/tree/master/panda/plugins/cskeleton

M.

Στις Τρί, 14 Αυγ 2018 στις 10:33 π.μ., ο/η cat998 <notifications@github.com>
έγραψε:

**Comment by cat998** [comment]
thanks for your advice
