### ISSUE TITLE
Segfault when deleting a memory subregion

### ISSUE THREAD

**Issue by toomanybananas** [panda-re/panda#330]
`rr_memory_region_find_parent` can return NULL, on line 1013 of [rr_log.c](https://github.com/panda-re/panda/blob/master/panda/src/rr/rr_log.c) that is called, and then passed to memory_region_del_subregion which dereferences the parent, causing a segfault. No NULL check is performed.

I have no idea what it is about my replay that causes it to segfault in this way but there's a bug here.

I can't share the trace but I'm running `panda/build/x86_64-softmmu/qemu-system-x86_64 -fda some_dos_image.img -m 128 -replay test1`, operating system being run is DOS.

**Comment by moyix** [comment]
Any chance you could find a public DOS image that shows this problem?

**Comment by toomanybananas** [comment]
Sorry for the super late reply, but here's the image in question (which is now public):
Password is 'infected' (not malware, CTF challenge).

[suspicious_floppy_v1.0.zip](https://github.com/panda-re/panda/files/2542877/suspicious_floppy_v1.0.zip)
