### ISSUE TITLE
osi_linux: Process ID or Thread ID?

### ISSUE THREAD

**Issue by nathanjackson** [panda-re/panda#360]
If I call `get_current_process(...)` when using `osi_linux`, do I get the PID of the current kernel task or do I get the PID of the current process? In other words, when I call `get_current_process(...)` am I actually getting the current thread?

**Comment by moyix** [comment]
`get_current_process` retrieves the current `thread_info`, which lives at the bottom of the kernel stack, and then pulls out the pointer to the `task_struct`; my understanding is that each userland process gets a single `task_struct`, and the PID from that should correspond to the PID of the process.

**Comment by nathanjackson** [comment]
A `task_struct` can belong to either a thread or process.

According to this file in `osi_linux` (https://raw.githubusercontent.com/panda-re/panda/master/panda/plugins/osi_linux/kernel_structs.html): get_task_struct can return either a task struct for a process or thread. What is not clear to me is whether or not these lines get the task struct for the process or thread.

```
target_ptr_t kernel_esp = panda_current_sp(env);
target_ptr_t ts = get_task_struct(env, (kernel_esp & THREADINFO_MASK));
```

My assumption was that threads while they share an address space within a process, they have their own stacks. Retrieving the current stack pointer should then return the current thread's stack?

What would be ideal is to be able to get both. I'm hoping that I can get both the process ID and the thread ID.

**Comment by nathanjackson** [comment]
It looks like the task struct used in `get_current_process(...)` can be a thread.

Here's some sample code to demonstrate:

```
#include <pthread.h>
#include <sys/syscall.h>
#include <sys/types.h>
#include <unistd.h>

#include <stdio.h>

void t2(void *ptr) {
  pid_t tid = syscall(SYS_gettid);
  printf("thread id (spawn) = %d\n", tid);
}

int main()
{
  pthread_t spawn;
  if (pthread_create(&spawn, NULL, (void *)&t2, NULL)) {
    fprintf(stderr, "error creating thread\n");
    return 1;
  }
  pid_t tid = syscall(SYS_gettid);
  printf("thread id (main) = %d\n", tid);
  if (pthread_join(spawn, NULL)) {
    fprintf(stderr, "join thread failed\n");
    return 2;
  }
  return 0;
}
```

A plugin to demonstrate:

```
void gettid_return(CPUState *cpu, target_ulong pc)
{
#ifdef TARGET_I386
    CPUArchState *env = (CPUArchState *)cpu->env_ptr;
    printf("eax = %u\n", (uint32_t)env->regs[R_EAX]);

    OsiProc *proc = get_current_process(cpu);
    printf("pid = %u\n", (uint32_t)proc->pid);
#endif
}

bool init_plugin(void *self) {
    panda_require("syscalls2");
    panda_require("osi");
    assert(init_osi_api());
    panda_require("osi_linux");
    assert(init_osi_linux_api());

#ifndef TARGET_PPC
    PPP_REG_CB("syscalls2", on_sys_gettid_return, gettid_return);
#endif

    return true;
}

void uninit_plugin(void *self) { }
```

Output:

```
eax = 1005
pid = 1005
eax = 1006
pid = 1006
```

**Comment by moyix** [comment]
Do you want to try putting together something that exposes the `tgid` field and see what it returns for your example?

**Comment by nathanjackson** [comment]
`sys_getpid()` in fact does refer to `tgid`. I should be able to make  PR for that and add a function to report thread ID. I've got a function to retrieve thread ID in Windows as well. Should I add a get current thread ID function to the OSI layer? I will provide implementations for `osi_linux` and `wintrospection`.

**Comment by nathanjackson** [comment]
A newer link to the Linux cross reference: https://elixir.bootlin.com/linux/v4.4.160/source/kernel/sys.c#L832

**Comment by moyix** [comment]
Yes, I think a get current thread function for OSI would be great. There are quite a few cases where having this information available would be useful (e.g. in the callstack plugin it would allow separating callstacks out by thread ID).

**Comment by m000** [comment]
Yes, you are right. This is an inconsistency compared to what `getpid()` would return.

This started because there was no support for thread information in osi api at the time when `get_current_process()` was implemented. This left some room of interpretation on what the function should return: for most purposes the kernel will not handle the thread group leader any different than the other threads.

I can see your PR adds a thread id field to `OsiProc` which seems to be the proper solution.

**Comment by nathanjackson** [comment]
Actually, its just a typedef on `uint64_t`. I didn't add the field to `OsiProc`. Should it be? My thought was that requesting threads and processes should take different paths.

**Comment by m000** [comment]
Yes, I skimmed through the code and (of course) read it incorrectly.

If we have the implementation for both windows and linux, maybe it would be a good idea to also add the thread id to OsiProc?

@moyix ?

**Comment by nathanjackson** [comment]
Are you thinking we should not have a `get_current_thread_id(...)` function and instead, we'd just return the thread ID inside `OsiProc`?

**Comment by moyix** [comment]
Hmm, I think it makes sense to keep them separate; if we want to eventually add an API to get all current threads of a process it will confusing to have them all be OsiProcs. One small point on naming – to match OsiProc maybe the thread struct should just be OsiThread?

**Comment by nathanjackson** [comment]
Having `OsiThread` is more consistent, but I only read the thread id and nothing else at the moment hence `OsiThreadId`. Going the `OsiThread` route could also be more useful too. Are there other fields that I should return along with the thread ID? Probably at the very least the process id the thread is associated with.

**Comment by moyix** [comment]
PID is a good one, yes. I can't think of others at the moment but it's something we can expand in the future.

**Comment by m000** [comment]
@moyix @nathanjackson I guess this can be closed now?

Issue tracker needs a cleanup. It's getting harder to find what you're looking for :)

**Comment by nathanjackson** [comment]
Closing.
