### ISSUE TITLE
Build failure(network.cpp)

### ISSUE THREAD

**Issue by kburova** [panda-re/panda#363]
Hello,

I'm trying to build panda and getting these error, which I'm not sure how to resolve..

`
.....

~/projects/panda/panda/plugins/network/network.cpp: In function ‘int handle_packet(CPUState*, uint8_t*, int, uint8_t, uint64_t)’:
~/projects/panda/panda/plugins/network/network.cpp:102:24: error: aggregate ‘handle_packet(CPUState*, uint8_t*, int, uint8_t, uint64_t)::wtap_pkthdr header’ has incomplete type and cannot be defined
     struct wtap_pkthdr header;
                        ^
~/projects//panda/panda/plugins/network/network.cpp:107:27: error: ‘wtap_phdr_init’ was not declared in this scope
     wtap_phdr_init(&header);
                           ^
~/projects/panda/panda/plugins/network/network.cpp:134:30: error: ‘wtap_phdr_cleanup’ was not declared in this scope
     wtap_phdr_cleanup(&header);
                              ^
~/projects/panda/rules.mak:97: recipe for target 'panda/plugins/network/network.o' failed
make[2]: *** [panda/plugins/network/network.o] Error 1
/~/projects/panda/panda/Makefile.panda.target:42: recipe for target 'plugin-network' failed
make[1]: *** [plugin-network] Error 2
make[1]: *** Waiting for unfinished jobs....
  CXX     x86_64-softmmu/panda/plugins/stringsearch/stringsearch.o
  PLUGIN  x86_64-softmmu/panda/plugins/panda_scissors.so 
........
`

And it happens multiple times, and recipes for targets 'panda/plugins/network/network.o', 'subdir-arm-softmmu', 'subdir-ppc-softmmu', 'subdir-i386-softmmu' and others fail. Any hints would be helpful as originally I tried to make 'lava' project work, but installation failed because of 'panda'. 

Thanks!

**Comment by moyix** [comment]
You need to install the wireshark developent headers. On Ubuntu that's `libwiretap-dev` and `libwireshark-dev`. This should be done for you if you run the `install_ubuntu.sh` script.

**Comment by nathanjackson** [comment]
This hit me too. It looks like the Ubuntu 16.04 packages were upgraded.

**Comment by nathanjackson** [comment]
A temporary workaround is to comment out the network plugin in `panda/plugins/config.panda`.

**Comment by kburova** [comment]
So, I do get the same error when running `install_ubuntu.sh`. Both, `libwiretap-dev` and `libwireshark-dev` are installed on my machine though. Commenting out the network plugin in `panda/plugins/config.panda` did work for now. Thanks.

**Comment by nathanjackson** [comment]
@kburova I have a PR in to address this issue.

Would you mind testing and letting me know if it fixes the build? https://github.com/nathanjackson/panda/tree/network-fixes

**Comment by kburova** [comment]
@nathanjackson, it worked. I ran `install_ubuntu.sh` and `build.sh` with no issues.

**Comment by moyix** [comment]
Great, since we've merged that I'll close this issue. Thanks for the help @nathanjackson!
