### ISSUE TITLE
PANDA plugins documentation

### ISSUE THREAD

**Issue by 0xcpu** [panda-re/panda#374]
Hello,

Is the documentation for [syscall plugin](https://github.com/panda-re/panda/blob/master/panda/docs/PANDA.md) updated?

For example, after a successful build I don't have any `qemu` directory in which to place the `Makefile` and plugin's source code.

Thank you!

**Comment by moyix** [comment]
That particular document is a bit outdated – you should be looking at the manual instead:

https://github.com/panda-re/panda/blob/master/panda/docs/manual.md

Each plugin also has its own set of documentation in USAGE.md, for example here's the syscalls2 documentation:

https://github.com/panda-re/panda/blob/master/panda/plugins/syscalls2/USAGE.md

**Comment by 0xcpu** [comment]
Ok, thank you!
