### ISSUE TITLE
Taint2 broken with Time-Travel Debug Support

### ISSUE THREAD

**Issue by nathanjackson** [panda-re/panda#377]
A recent commit that introduces time-travel debugging support broke taint 2 for us.

```
PANDA[core]:os_familyno=1 bits=32 os_details=2000
PANDA[stringsearch]:adding argument str=cftaint6.
PANDA[core]:initializing stringsearch
PANDA[core]:loading required plugin callstack_instr
PANDA[core]:initializing callstack_instr
PANDA[core]:initializing tstringsearch
PANDA[core]:loading required plugin stringsearch
PANDA[core]:panda_stringsearch.so already loaded
PANDA[core]:loading required plugin taint2
PANDA[core]:initializing taint2
PANDA[taint2]:propagation via pointer dereference ENABLED
PANDA[taint2]:taint operations inlining DISABLED
PANDA[taint2]:llvm optimizations DISABLED
PANDA[taint2]:taint debugging DISABLED
PANDA[taint2]:detaint if control bits 0 DISABLED
PANDA[taint2]:maximum taint compute number (0=unlimited) 0
PANDA[taint2]:maximum taintset cardinality (0=unlimited) 0
PANDA[core]:loading required plugin callstack_instr
PANDA[core]:i386-softmmu/panda/plugins/panda_callstack_instr.so already loaded
loading snapshot
... done.
opening nondet log for read :   ./w2k-cftaint6-trim-rr-nondet.log
./w2k-cftaint6-trim-rr-nondet.log:     1264160 instrs total.
w2k-cftaint6-trim:       12643 (  1.00%) instrs.    0.13 sec.  0.27 GB ram.
READ Match of str 0 at: instr_count=15847 :  77fa15d3 804b7599 00000000
enabling taint at instr count 15847
PANDA[taint2]:taint2_enable_taint
taint2: Allocating large fast_shad (17179869184 bytes).
taint2: Allocating small fast_shad (12800000 bytes) using malloc @ 7fa974dca010.
taint2: Allocating small fast_shad (256 bytes) using malloc @ 7fa968708c90.
taint2: Allocating small fast_shad (512 bytes) using malloc @ 7fa9681fee20.
taint2: Allocating small fast_shad (656384 bytes) using malloc @ 7fa976f5f010.
PANDA[taint2]:LLVM optimizations DISABLED
taint2: Linking taint ops from i386-softmmu/panda/plugins/panda_taint2_ops.bc
taint2: Done initializing taint transformation.
qemu-system-i386: panda/plugins/taint2/llvm_taint_lib.cpp:890: bool llvm::PandaTaintVisitor::isCPUStateAdd(llvm::BinaryOperator*): Assertion `AI->getOpcode() == Instruction::Add' failed.
Aborted (core dumped)
```

`git bisect` revealed that this commit to introduced the problem: 1a3b1149c904020f91c2463a31f297e952726719

**Comment by moyix** [comment]
I can't seem to reproduce this locally. Here's what I tried (with current master):

1. Create a recording with `../scripts/run_debian.py ls /usr`
2. Replay with `stringsearch`, `tstringsearch`, and `tainted_instr`:
    `i386-softmmu/qemu-system-i386 -replay replays/ls/ls -panda stringsearch:str="root" -panda tstringsearch -panda tainted_instr -pandalog foo.plog`

Using those steps the replay finishes fine and produces a valid pandalog.

Could you try removing your build directory and rebuilding from an clean directory? I think there is some part of the build system that is not tracking dependencies properly when you just do a `git pull` and then `make`.

**Comment by nathanjackson** [comment]
So I wiped my build directory to start from scratch. I'm still getting the same error.

One thing different that I'm doing is I'm using a recording that I've made prior to this change. I am not creating a recording with the time travel.

Another potential problem I have seen is that if you are building against a release build of LLVM, I think it ends up disabling assertions. I have a debug build that explicitly has the assertions enabled.

**Comment by nathanjackson** [comment]
I think assertions might be disabled some how on your end. I used the run_debian script to perform the same steps as you and I got the assertion error (again with a clean build).

```
i386-softmmu/qemu-system-i386 -replay replays/ls/ls -panda stringsearch:str="root" -panda tstringsearch -panda tainted_instr -pandalog foo.plog
PANDA[stringsearch]:adding argument str=root.
pandalogging to [foo.plog]
PANDA[core]:initializing stringsearch
PANDA[core]:loading required plugin callstack_instr
PANDA[core]:initializing callstack_instr
PANDA[core]:initializing tstringsearch
PANDA[core]:loading required plugin stringsearch
PANDA[core]:panda/build/i386-softmmu/panda/plugins/panda_stringsearch.so already loaded
PANDA[core]:loading required plugin taint2
PANDA[core]:initializing taint2
PANDA[taint2]:propagation via pointer dereference ENABLED
PANDA[taint2]:taint operations inlining DISABLED
PANDA[taint2]:llvm optimizations DISABLED
PANDA[taint2]:taint debugging DISABLED
PANDA[taint2]:detaint if control bits 0 DISABLED
PANDA[taint2]:maximum taint compute number (0=unlimited) 0
PANDA[taint2]:maximum taintset cardinality (0=unlimited) 0
PANDA[core]:loading required plugin callstack_instr
PANDA[core]:panda/build/i386-softmmu/panda/plugins/panda_callstack_instr.so already loaded
PANDA[core]:initializing tainted_instr
PANDA[core]:loading required plugin taint2
PANDA[core]:panda/build/i386-softmmu/panda/plugins/panda_taint2.so already loaded
PANDA[core]:loading required plugin callstack_instr
PANDA[core]:panda/build/i386-softmmu/panda/plugins/panda_callstack_instr.so already loaded
tainted_instr full mode
loading snapshot
... done.
opening nondet log for read :   replays/ls/ls-rr-nondet.log
replays/ls/ls-rr-nondet.log:     3284907 instrs total.
ls:       32851 (  1.00%) instrs.    0.09 sec.  0.14 GB ram.
READ Match of str 0 at: instr_count=48325 :  c103d113 b75d1efc 07ae4000
enabling taint at instr count 48325
PANDA[taint2]:taint2_enable_taint
taint2: Allocating large fast_shad (2147483648 bytes).
taint2: Allocating small fast_shad (12800000 bytes) using malloc @ 7f343cbca010.
taint2: Allocating small fast_shad (256 bytes) using malloc @ 7f343111fd20.
taint2: Allocating small fast_shad (512 bytes) using malloc @ 7f34304499a0.
taint2: Allocating small fast_shad (656384 bytes) using malloc @ 7f343f55f010.
PANDA[taint2]:LLVM optimizations DISABLED
taint2: Linking taint ops from panda/build/i386-softmmu/panda/plugins/panda_taint2_ops.bc
taint2: Done initializing taint transformation.
qemu-system-i386: panda/panda/plugins/taint2/llvm_taint_lib.cpp:892: bool llvm::PandaTaintVisitor::isCPUStateAdd(llvm::BinaryOperator*): Assertion `AI->getOpcode() == Instruction::Add' failed.
Aborted (core dumped)
```

**Comment by moyix** [comment]
Ah, that makes sense, I usually keep around the Release build. I'll take a look.

**Comment by moyix** [comment]
I *think* in this case that assert is simply wrong. But it's mysterious to me why this is only showing up now. The assert is failing because it's trying to ensure that the argument of a `cast` is an `add` instruction. But the LLVM instruction is:

``` 
%or72.c = inttoptr i64 %or72 to %struct.Object*
```

Which lives in `do_inject_x86_mce`. Helper functions do contain a lot of code we don't normally have to deal with since they're lowered from C rather than TCG, but I don't know why this wasn't showing up before now.

Changing `PandaTaintVisitor::isCPUStateAdd` in `panda/plugins/taint2/llvm_taint_lib.cpp` to read:

```
bool PandaTaintVisitor::isCPUStateAdd(BinaryOperator *AI) {
    return (AI->getOpcode() == Instruction::Add) && isEnvPtr(AI->getOperand(0));
}
```

Fixes this issue and is, I think, more correct. But I'm still mystified as to why it only showed up now.

**Comment by nathanjackson** [comment]
Your solution makes sense to me.

The assertion does appear to go away when I revert 1a3b1149c904020f91c2463a31f297e952726719. Could it be the changes to `hw/i386/translate.c`? I'm not sure the changes are wrong, but rather I just want to understand what's going on and adjust my expectations if need be.

**Comment by moyix** [comment]
The other possible culprit is these fields which were added to the CPU state:

https://github.com/panda-re/panda/blob/1a3b1149c904020f91c2463a31f297e952726719/include/qom/cpu.h#L394-L398

I don't have any more time to debug this today, but you could try making those globals and see if that changes things.

**Comment by nathanjackson** [comment]
Thanks @moyix!
