### ISSUE TITLE
taint2 generates taint change reports for untainted data

### ISSUE THREAD

**Issue by LauraLMann** [panda-re/panda#378]
The taint2 plugin always calculates new bit masks (controlled bits, zeros, ones) when a taint operation comes in, even if the byte in question isn't really tainted (has no labels).  As some LLVM instructions put a constant into some part of one or more masks, this can cause a taint change report to be generated.  (For example, LLVM SHL will put some ones in the lower bits of the zero mask.)
This erroneous taint change report messes up the ability of tainted_instr to quit early (using the num argument), as it considers consecutive changes for the same PC to be one instruction, only increments the counter when the byte has taint labels, but updates the last-seen-PC regardless if any labels were found.  So, if the first taint 'change' is for unlabeled data, the last-seen-PC is updated, and then if the next taint change is for taint-with-labels on the same PC, the counter will not be incremented.  Thus, tainted_instr won't quit at the limit requested, but some time later.
Although it would be easy to work around this issue in tainted_instr, wouldn't it be better to fix taint2 to not calculate bit masks on untainted data?

**Comment by moyix** [comment]
Yes, I think that makes sense. Do you want to make a PR for it?

**Comment by LauraLMann** [comment]
Yes, I would like to make a PR for this problem.  But, until #377 is resolved (or time-travel debug support is backed out of master) it won't be very useful.  It won't even be testable, which is why I hesitate.

**Comment by moyix** [comment]
That shouldn't block testing (there's a workaround listed in the comments of that issue; we're just not applying it until we're sure we understand what's going on). I'll have another look at it today.

**Comment by moyix** [comment]
#377 is fixed now! :)

**Comment by LauraLMann** [comment]
The problem with update_cb updating masks on untainted data is only part of the problem causing tainted_instr to miscount the tainted 'instructions' it has seen.  (It's really counting tainted blocks, but that's another matter.)  Tainted_instr doesn't account for the fact that when taint_delete is called on a tainted item that a taint change report will also be generated.  So, tainted_instr shouldn't note the PC and ASID for the most recently seen tainted 'instruction' unless the current change report is actually for a tainted item.  It's easy enough to fix this too, so I will do so.  (I will fix it in tainted_instr of course, in case some other plugin wants to know about taint that is deleted.)

**Comment by wangray** [comment]
Fixed by #390 , closing unless indicated otherwise.
