### ISSUE TITLE
taint2 may generate taint for a constant

### ISSUE THREAD

**Issue by LauraLMann** [panda-re/panda#381]
I'm using the i386 build of PANDA, which uses helper functions to calculate condition codes.  One such helper function, helper_cc_compute_c_llvm, if it is provided an CC operation for LOGICB/W/L, CLR or POPCNT, takes the default case in the switch statement in the helper.  This means when taint_select is run in the last block, that the return value (0) is not copied into LLVM, as the return value is a constant.  However, a taint_copy does copy from the (unused) destination in the LLVM taint shadow to the Ret shadow.  Sometimes I get a taint report from this copy.
Is this just leftover taint from the previous time this frame in the LLVM shadow was used?  (The taint_push and taint_pop don't clear taint from the new (for push) or abandoned (for pop) frame, but just change the pointer into the list of TaintData objects.)  It doesn't seem right - shouldn't the helper clear the taint from the destination in LLVM if a constant is returned?

**Comment by AndrewFasano** [comment]
Sounds like this was fixed by #405- if anyone runs into this issue again in the future we can reopen. Thanks for identifying the bug and submitting the fix!
