### ISSUE TITLE
`update_cb` is often incorrectly setting `last_literal` in taint_ops.cpp

### ISSUE THREAD

**Issue by wangray** [panda-re/panda#387]
`last_literal` should be the argument of an LLVM instruction that determines the bitmask applied to another operand.

There are two bugs in how `last_literal` is being calculated, which affects how taint is propagated with controlled bits. 

One: In the case of the LLVM instruction `shl i32 1000000000, %tmp1_v9`, last_literal is set to the first constant observed while iterating the arguments, i.e. 1000000000. So the assertion 
` tassert(last_literal < 64);` fails at `update_cb_switch.h:159`. 

I observe this issue regardless of `TAINT2_DEBUG` option — taint does not work at all for me. 

Two: https://github.com/panda-re/panda/issues/371

**Comment by wangray** [comment]
Example replay where I see an assertion failure 

https://www.dropbox.com/s/95qj8arfajxes7v/test-decode-to-global-rr-nondet.log?dl=1
https://www.dropbox.com/s/na499jygzm52qj2/test-decode-to-global-rr-snp?dl=1

**Comment by nathanjackson** [comment]
@wangray are you building against a debug build of LLVM? Something about debug builds messes with the C-library assertion (I assume an LLVM header ends up defining NDEBUG somewhere when in release mode). If you've built against a debug build, that probably explains why you see the assert regardless of the `TAINT2_DEBUG` option.

I've gotten around this by not using a debug build, but that's definitely not a long term solution as sometimes you have to use a debug build for testing.

**Comment by wangray** [comment]
Yes, I'm using a debug build of LLVM. But the assert makes sense, so the bug still affects taint correctness.
