### ISSUE TITLE
handling of clone from syscalls2

### ISSUE THREAD

**Issue by m000** [panda-re/panda#392]
It seems that clone (and possibly other?) system calls are not handled properly by `syscalls2`. Specifically, no return callback is invoked. This is what I see when analyzing my trace:

1. We have the `agetty` process.
```
taskd    asid     pid/ppid name
d7766900 1793c8a0 1872:1   agetty
```

2. The process runs several syscalls. There are one `on_all_sys_enter2` and one `on_all_sys_return2` hooked. Additionally, there is one `on_sys_clone_return` return callback hooked. Only `on_all_sys_enter2` is invoked for clone.

```
PANDA[osi_pse]:D> SYS0  sys_ioctl               d7766900 1793c8a0
PANDA[osi_pse]:D> SYSR  sys_ioctl               d7766900 1793c8a0
PANDA[osi_pse]:D> SYS0  sys_rt_sigprocmask      d7766900 1793c8a0
PANDA[osi_pse]:D> SYSR  sys_rt_sigprocmask      d7766900 1793c8a0
PANDA[osi_pse]:D> SYS0  rt_sigaction            d7766900 1793c8a0
PANDA[osi_pse]:D> SYSR  rt_sigaction            d7766900 1793c8a0
PANDA[osi_pse]:D> SYS0  sys_ioctl               d7766900 1793c8a0
PANDA[osi_pse]:D> SYSR  sys_ioctl               d7766900 1793c8a0
PANDA[osi_pse]:D> SYS0  sys_clone               d7766900 1793c8a0
PANDA[osi_pse]:D>
```

3. A couple of context switched later, a new `agetty` process appears. The new process has the first one as parent. Which implies that clone succeeded but somehow the callbacks were missed.
```
taskd    asid      pid/ppid    name
d7762300 18231d80  1878:1872   agetty
```

Note that the callbacks are invoked normally in other cases. So this is probably some corner case that is missing (?). Not sure where to start looking, so any hints are appreciated. I can also upload the trace for anyone interested.

**Comment by m000** [comment]
A demonstration for this can be made with #395. I ran it for a short trace and at the end of the analysis, `running_syscalls` contained the following entries: 
```
      1 sys_clone
      1 sys_futex
      1 sys_poll
      1 sys_rt_sigreturn
      1 sys_rt_sigtimedwait
      1 sys_select
      2 sys_nanosleep
      2 sys_write
      5 sys_epoll_wait
    208 sys_sigreturn
    596 sys_execve
    794 sys_exit_group
```

There seem to be two distinct problems with the current implementation of `syscalls2`:
  - There is no support for syscalls that do not return, such as `sys_execve` or `sys_exit_group`. This results in amassing entries in the `running_syscalls` map over time. Should be straightforward to fix with some sort of whitelisting.
  - Occasionally the return of syscalls is missed. This is the which was reported initially, but the problem is not isolated to `sys_clone`. I'm not sure what causes this, or how to solve it.

**Comment by moyix** [comment]
Yes, I think we can just mark some things like sigreturn and execve as "noreturn" in some metadata struct for each syscall and indicate that we shouldn't expect them to return.

I'm not sure what's going on with the others. Clone makes a certain amount of sense as it could have two returns (one in the parent and one in the child). But for things like select(), poll(), etc. I'm not sure why they aren't returning where we expect. Perhaps we can write a few small test programs that use those system calls and then step through them using QEMU/PANDA's gdb stub to figure out what's going on?

**Comment by m000** [comment]
I will try to use scissors to trim my trace to the infringing part, and also log the expected return address and the first instruction of the process which was actually executed.

Note that a few of the not-returned system calls may actually still be running at the end of the trace.
