### ISSUE TITLE
PANDA_CB_VMI_PGD_CHANGED callback name/documentation

### ISSUE THREAD

**Issue by m000** [panda-re/panda#41]
PANDA_CB_VMI_PGD_CHANGED callback works, but is not documented anywhere.
A rename of the callback should also be considered (i.e. remove "VMI" from its name).

**Comment by gitttt** [comment]
I saw this callback in asidstory.cpp and was wondering what it does. So I would also appreciate a bit documentation.

**Comment by moyix** [comment]
It is now documented. Search for `after_PGD_write` in docs/manual.md. Sorry it's not easier to find. We've been intending to split the docs back out into sections to make things easier to find, but just haven't found the time :(
