### ISSUE TITLE
qemu-system-x86_64: Length mismatch: pc.ram: 0x100000000 in != 0x8000000: Invalid argument

### ISSUE THREAD

**Issue by WangWenshuo** [panda-re/panda#410]
when I using replay get this error:

loading snapshot
qemu-system-x86_64: Length mismatch: pc.ram: 0x100000000 in != 0x8000000: Invalid argument
qemu-system-x86_64: error while loading state for instance 0x0 of device 'ram'
Failed to load vmstate
Failed to start replay

**Comment by moyix** [comment]
You need to provide PANDA with the amount of RAM to use (and it must be the same as you used when making the recording). In this case it looks like you used 4G when creating the recording, so you need to use `-m 4G`.

**Comment by moyix** [comment]
I've added a note to the FAQ about this since it's something that people run into frequently:

https://github.com/panda-re/panda/blob/master/panda/docs/manual.md#faq
