### ISSUE TITLE
pirate_utils not ported to panda2

### ISSUE THREAD

**Issue by mohamadkav** [panda-re/panda#414]
In the README for taint2, it specifies that "For Windows guests, the utilities included in panda/qemu/panda_tools/pirate_utils can be used to label files", but no such file exists. This README needs to be updated; or pirate utils need to be ported to panda2.

**Comment by moyix** [comment]
I believe the hypercall system has been changed a bit since PANDA 1.0, so it's probably best to just update the README. It would be nice to have these guest utilities again, but for now `file_taint` is a pretty good substitute.

**Comment by bridgeythegeek** [comment]
@mohamadkav, did you get `taint2` to work? I can't.
I get a list of issues:

#### 1. `taint2_ext.h` doesn't exist in the taint2 folder.
I know it's generated on build in the respective `panda\build` folder, but I had to symlink to the file in the relevant `panda/build` folder from the `panda/panda/plugins/taint2` folder for Make to find it.
```
# ln -s /panda/build/i386-softmmu/panda/plugins/taint2/taint2_ext.h /panda/panda/plugins/taint2/taint2_ext.h
```
#### 2. `panda_taint2.so` only existed in `/panda/build/...` so another symlink.
```
# ln -s /panda/build/i386-softmmu/panda/plugins/panda_taint2.so /panda/i386-softmmu/panda/plugins/panda_taint2.so
```
#### 3. `undefined symbol: tcg_llvm_ctx`
```
PANDA[core]:loading required plugin taint2
Failed to load /panda/i386-softmmu/panda/plugins/panda_taint2.so: /panda/i386-softmmu/panda/plugins/panda_taint2.so: undefined symbol: tcg_llvm_ctx
PANDA[core]:FAILED to load required plugin taint2 from /panda/i386-softmmu/panda/plugins/panda_taint2.so
```
Haven't been able to fix this one yet.
`taint2.cpp` does `#include "panda/tcg-llvm.h"` and the file exists.

**Comment by moyix** [comment]
@bridgeythegeek Is taint2 not building for you under PANDA? It ought to be built automatically when you build the rest of PANDA (as long as LLVM 3.3 is installed).

**Comment by bridgeythegeek** [comment]
Hi @moyix. Oh, well that's awkward. I evidently wasn't providing the llvm options to `./configure`.
Now, with:
```
./configure --enable-llvm --with-llvm=/usr/lib/llvm-3.3
```
everything seems fine.

Thanks for the pro-tip!

**Comment by mohamadkav** [comment]
@bridgeythegeek Yeah I used the file_taint plugin to label my file, and using tainted_net "query_outgoing_traffic" I could get the taint analysis result of the file which was being sent out over the network
