### ISSUE TITLE
Where does taint2 allocate memory? [Dev Question]

### ISSUE THREAD

**Issue by jaschoepfer** [panda-re/panda#416]
I am currently modifying the taint2 plugin for a research project, and wanted to ask for help from someone who knows more about how it works. Essentially i am extracting logs about certain events (via PandaLog) and do not need any storage of taint labels.

So far, I replaced the Shadow memories defined in "shad.h" with dummies, but the plugin is still extremely RAM-hungry. Does someone know where else taint2 allocates large amounts of memory?

**Comment by jaschoepfer** [comment]
TIL that PandaLog doesn't free the objects you give to it. I was memory leaking PANDA to death.
Closing Question in shame

**Comment by moyix** [comment]
Whoops. Is there a way we can make this clearer? Perhaps we can modify the C++ PandaLog interface to handle the details of allocation and deletion somehow?

**Comment by jaschoepfer** [comment]
I don't think the interface is at fault. Nested customizable protobuffer messages can get pretty complex are probably best handled by the plugin (though it might not impossible to generalize).

I made a rookie mistake and once something began munching up my RAM the taint engine became the obvious first suspect.
