### ISSUE TITLE
Can't access www.rrshare.org

### ISSUE THREAD

**Issue by jinyu00** [panda-re/panda#430]
```
# curl http://www.rrshare.org/
curl: (7) Failed connect to www.rrshare.org:80; Connection timed out
```

**Comment by moyix** [comment]
Sorry about this – we need to migrate it to a new host and I haven't found the time yet :( In the meantime you can find the raw RR logs here:

http://panda-13.mit.edu/~brendan/rrlogs/

**Comment by aikata10** [comment]
can't access either www.rrshare.org or panda-13.mit.edu/~brendan/rrlogs
