### ISSUE TITLE
Instruction missed when doing instruction level recording

### ISSUE THREAD

**Issue by vancaho** [panda-re/panda#431]
Hi, I want to use PANDA as the basic platform for doing instruction level recording for windows applications(mark the instructions to be recorded in ```before_insn_translate(callback for PANDA_CB_INSN_TRANSLATE)``` and do record in ```before_insn_exec(callback for PANDA_CB_INSN_EXEC)```. However I find that some instructions are missed. 
For example, when recording the executing for notepad++.exe, after looking deep into the instruction trace, I found that the instructions are missed between ```1966791277``` and ```1966764751```.

![image](https://user-images.githubusercontent.com/15372990/57193622-9bf3a600-6f6f-11e9-9b72-83d4d520d8ac.png)

According the controlflow the instruction after ```1966791277``` should be ```1966764726```. So the instructions between ```1966764726```  and ```1966764751``` are missed. 

To solve the problem, I debugged PANDA, and set a breakpoint in ```before_insn_translate``` when the ```eip``` is ```1966791277``` and returns ```true``` and continues running. The next time the breakpoint is hit, I found that ```eip``` equals ```1966764751```. I don't know why.

However there is a strange phenomenon: if I use ```scissors``` plugin to scissor the replay file to a shorter one and then record the instructions in the shorter one, the instructions between ```1966764726```  and ```1966764751``` are not missed, as shown in the following figure.

![image](https://user-images.githubusercontent.com/15372990/57193604-6bac0780-6f6f-11e9-8766-98adf1969652.png)

**Comment by nathanjackson** [comment]
Are you calling `panda_do_flush_tb()` somewhere? If not, it seems like that might be why your instrumentation code isn't running. See: https://github.com/panda-re/panda/blob/master/panda/docs/manual.md#qemu-translation-control

**Comment by vancaho** [comment]
Hi, thanks for your reply. After debugging panda, I found why the longer replay loses instructions. That is because the instructions are executed in other processes which I do not  want to record.So I return false for before_insn_trans when the undesired process exexutes the instructions. As same basic blocks are only translated only once, when the desired process executes the missing instructions, the before_insn_translate function will not be invoked. It causes that the before_insn_exec function will not be invoked neither. So the instructions are missed.
But in the trancated replay, the instructions are not translated or executed before, so we can record it.
