### ISSUE TITLE
How can I get the process of taint2 on insturction level?

### ISSUE THREAD

**Issue by xiaoxiongwang** [panda-re/panda#438]
Hello!
I was trying to get the process of taint2 on instruction level, but I only found Shad::copy function in the callback replay_hd_transfer_callback, on_replay_net_transfer and on_replay_before_dma. I was wondering how can I get the taint2 process on insrtuction level especially for float insrtuction tained.

Thanks for any help.

**Comment by moyix** [comment]
I'm not quite sure what you're asking – are you trying to figure out where taint transfers are implemented in the code?

**Comment by xiaoxiongwang** [comment]
> I'm not quite sure what you're asking – are you trying to figure out where taint transfers are implemented in the code?

yes!!!
I was trying to figure out where taint transfers are implemented in the code but failed.
Thanks again for any help.

**Comment by moyix** [comment]
PANDA implements taint transfers by lifting everything (including C helper functions) to LLVM and then instrumenting the LLVM to add taint transfers using this code:

https://github.com/panda-re/panda/blob/master/panda/plugins/taint2/llvm_taint_lib.cpp

If you want a little more detail, you can read this:

https://repository.library.northeastern.edu/files/neu:1345/fulltext.pdf

which describes the full architecture.

**Comment by xiaoxiongwang** [comment]
> PANDA implements taint transfers by lifting everything (including C helper functions) to LLVM and then instrumenting the LLVM to add taint transfers using this code:
> 
> https://github.com/panda-re/panda/blob/master/panda/plugins/taint2/llvm_taint_lib.cpp
> 
> If you want a little more detail, you can read this:
> 
> https://repository.library.northeastern.edu/files/neu:1345/fulltext.pdf
> 
> which describes the full architecture.

Thank you very much for your help!!!I will try to learn it.
