### ISSUE TITLE
Can I debug the plugin taint2 using gdb with symbol?

### ISSUE THREAD

**Issue by xiaoxiongwang** [panda-re/panda#444]
I want to debug the plugin taint2 to see the taint transfers for every instruction and figure out which functions are called. I can do the time-travel debugging according to the document [time-travel debugging](https://github.com/panda-re/panda/blob/master/panda/docs/time-travel.md) but there is no symbol . Is there a way for me to load the symbol table? Could it be possible to give me some suggestions?
Thanks very much for any help!

**Comment by moyix** [comment]
Are you trying to debug the taint plugin itself, or code running inside the guest virtual machine? For the former, you should simply be able to build PANDA with `--enable-debug` and then attach gdb to the QEMU process.

For the latter, you will need to tell gdb where the symbols for the program you're interested in are. Ray's blog post on time travel debugging has more details on how to do this for the Linux kernel:

https://raywang.tech/2018/11/14/Time-Travel-Debugging-in-PANDA/
