### ISSUE TITLE
Infinited loop detected sometimes when starting the record with the VM paused

### ISSUE THREAD

**Issue by Quentin01** [panda-re/panda#447]
Might be related to #322 and #329 but I'm not sure.
The version used is one compiled from the commit 85002fb (current master at this time).

The issue is that I'm getting a `detect_infinite_loops: Assertion 'false' failed.` right at the beginning of the replay. (with `rr_guest_instr_count = 0`)

You can download the record from here: https://drive.google.com/file/d/1VTb8SqoYUGcvUiarnIPUTM93UscfP6PK/view?usp=sharing.

The record was done with an old version of Windows 10 x64 (Threshold 2) which was lightened as the guest OS, `2048M` of RAM and the option `-usbdevice tablet`.

Here is how the record was started/stopped: breaking the VM at a RIP (from GDB), starting the record, resuming it, breaking at another RIP and then stopping the record. 

The issue happens only with a 2% rate, so it's not really that common but still significant.

Here is the start of the [log file](https://github.com/panda-re/panda/files/3304715/printed_log.txt):
```
{guest_instr_count=0}
	RR_INTERRUPT_REQUEST_16 from RR_CALLSITE_CPU_HANDLE_INTERRUPT_BEFORE
{guest_instr_count=1}
	RR_INTERRUPT_REQUEST_2 from RR_CALLSITE_CPU_HANDLE_INTERRUPT_AFTER
{guest_instr_count=1}
	RR_INPUT_4 209 from RR_CALLSITE_CPU_HANDLE_INTERRUPT_INTNO
{guest_instr_count=1}
	RR_INTERRUPT_REQUEST_0 from RR_CALLSITE_CPU_HANDLE_INTERRUPT_AFTER
{guest_instr_count=66}
	RR_INPUT_8 2413000119575 from RR_CALLSITE_RDTSC
{guest_instr_count=122}
	RR_INPUT_8 2413000874064 from RR_CALLSITE_RDTSC
...
```

It looks like the replay is expecting an APIC interrupt at the first instruction and that it won't come (`cpu->interrupt_request` value is `CPU_INTERRUPT_POLL` which will poll the APIC for an irq).

When logging `rr_num_instr_before_next_interrupt()` in `cpu-exec.c:cpu_exec` it is 0 at first and then 1 after the call to `cpu_handle_interrupt`.

I don't understand how to resolve the issue and/or how to mitigate it.

If you need more information about this record/issue you can just ask me.

**Comment by nathanjackson** [comment]
This might seem weird, but can you try cherry-picking this commit to see if recording and replay works?

e6e5c34388dd4117a2e19483415ae29d04aad18f

This fix was applied at one point, but later backed out because it broke old recordings. It seems like it might fix your problem. However if it works, since we can't break old recordings I'm not sure what to do in the short run.

**Comment by Quentin01** [comment]
It's worse than before when just cherry-picking this commit on master. 

I still have the infinite loop (but with different logs) and I also have an assert failing frequently in `rr_log.c:rr_replay_input_4` mainly at the end of a replay (but sometimes in the middle of it).

`detect_infinite_loops`
---

Here is the beginning of the logs:
```
{guest_instr_count=0}
	RR_INPUT_4 2 from RR_CALLSITE_CPU_HANDLE_INTERRUPT_POLL
{guest_instr_count=0}
	RR_INTERRUPT_REQUEST_2 from RR_CALLSITE_CPU_HANDLE_INTERRUPT_AFTER
{guest_instr_count=0}
	RR_INPUT_4 209 from RR_CALLSITE_CPU_HANDLE_INTERRUPT_INTNO
{guest_instr_count=0}
	RR_INTERRUPT_REQUEST_0 from RR_CALLSITE_CPU_HANDLE_INTERRUPT_AFTER
{guest_instr_count=65}
	RR_INPUT_8 2418277084966 from RR_CALLSITE_RDTSC
...
```

 `rr_replay_input_4`
---

The end of the logs:
```
...
{guest_instr_count=2068643}
	RR_INPUT_8 2417460642 from RR_CALLSITE_IO_READ_ALL
{guest_instr_count=2068717}
	RR_INTERRUPT_REQUEST_16 from RR_CALLSITE_CPU_HANDLE_INTERRUPT_BEFORE
{guest_instr_count=2068718}
	RR_END_OF_LOG
```

The logs displayed by Panda:
```
RR rr_assertion `current_item' failed at panda/panda/src/rr/rr_log.c:976
Current log point:
<queue empty>
Current replay point:
{guest_instr_count=2068717}
Aborted
```

When displaying the backtrace with GDB I can see that the failed call to `rr_replay_input_4` is the one introduced by your commit when executing `x86_cpu_exec_interrupt` with `interrupt_request=16`.

**Comment by nathanjackson** [comment]
Did you recreate your recording after cherry picking, it looks like you re-used the same replay? This is why the change was later backed out - recordings made without this commit would no longer replay.

**Comment by Quentin01** [comment]
I didn't re-use the previous record, they are fresh new records created and replayed by the same version of Panda.

**Comment by nathanjackson** [comment]
Hmm, well it was worth a shot. Sorry that didn't help.

For debugging purposes, we've used Mozilla RR and the panda's `diverge.py` script before in `panda/panda/scripts/diverge.py`. Unfortunately, there's not much else you can do besides use that to try and figure out why the replay fails.
