### ISSUE TITLE
detect_infinite_loops errors when using monitor commands during recording replay

### ISSUE THREAD

**Issue by LauraLMann** [panda-re/panda#454]
If I replay a recording with plugins and the -monitor stdio option and then use a script sent through a pipe to provide input to the monitor prompt, I frequently get the detect_infinite_loops error from cpu-exec.c.  (I haven't seen it yet when I manually enter monitor commands while replaying a recording, but of course that's not a very consistent way to test something, so I'd rather use a script.)  This happens even with trivial little commands like "info pic" or "info network".
A simple example is:
#!/bin/bash -x
pipe=/tmp/panda_pipe
trap "rm -f $pipe" EXIT
if [ ! -p "$pipe" ] ; then
    mkfifo $pipe
fi
/changed/to/protect/the/innocent/i386-softmmu/qemu-system-i386 -monitor stdio \
    -m 2G \
    -net nic -net user \
    -os linux-32-.+ \
    -panda osi \
    -panda osi_linux:kconf_file=mykernelinfo.conf,kconf_group=UbuntuServer \
    -replay myrecording \
    -panda callstack_instr:stack_type=threaded \
    -panda file_taint:filename=positional.bin,pos=true \
    -panda tainted_instr -pandalog linux_mt_sf_ti_pandanet.plog < $pipe &
( sleep 3
echo "info pic"
sleep 3
echo "info network"
sleep 3
echo "info irq"
sleep 3
echo "help info"
sleep 3
) > $pipe
wait

Of course, I really want more interesting stuff in the script - I switched to the trivial stuff to determine if the more interesting commands were the problem - they aren't.
Exactly what command the script is on when PANDA issues the detect_infinite_loops error varies - usually it's the "info pic", but sometimes it produces the appropriate output for that and dies on the "info network".

**Comment by AndrewFasano** [comment]
From what I understand, interacting with a replay via the monitor is unsupported in panda. I think this was an intentional design decision and maybe we should raise an error when a monitor is connected during a replay execution so this is more clear in the future.

During a replay, the only supported way to interact with the guest is through plugins and callbacks.

**Comment by LauraLMann** [comment]
Yep, if interacting with a replay via the monitor is unsupported in PANDA, I fully agree that an error should be raised if one attempts to do so.  Mentioning this in the PANDA documents would be helpful too - I don't recall seeing such a warning anywhere.
