### ISSUE TITLE
make fails on for loop

### ISSUE THREAD

**Issue by bridgeythegeek** [panda-re/panda#457]
I'm using the latest version of the pandare/panda docker image.
I've replayed a recording to demonstrate that panda was working - which was successful.
And I ran the `asidstory` plugin - which was successful.

However, I now wanted to recompile so I could include my own plugin.

My `./configure` worked fine:
```
./configure --target-list=i386-softmmu --extra-plugins-path=/panda_working/
```

But on `make` I get unexpected errors with `for` loops in panda code (not mine!):
```
root@be2f9eaec072:/panda# make
	CHK version_gen.h
  CC      i386-softmmu/panda/src/callbacks.o
/panda/panda/src/callbacks.c: In function 'panda_get_plugin_by_name':
/panda/panda/src/callbacks.c:225:5: error: 'for' loop initial declarations are only allowed in C99 mode
     for (int i = 0; i < nb_panda_plugins; i++) {
     ^
/panda/panda/src/callbacks.c:225:5: note: use option -std=c99 or -std=gnu99 to compile your code
```
The same complaint about for loop declarations is repeated several times.

I have read the error and I see that adding c99/gnu99 support would solve this, but:

1. How come I need to change this? How did panda EVER compile without this option in the makefile?
2. How/where do I make the change?

Thanks!
btg

**Comment by bridgeythegeek** [comment]
FYI/BTW, I was able to get past this by manually editing each of the for loops that were complained about to declare the variable immediately before.

For example:
```
for (int i=0; i<10; i++) { ... }
```
becomes:
```
int i;
for (i=0; i<10; i++) { ... }
```

**Comment by nathanjackson** [comment]
What distro\compiler are you using? I've compiled PANDA with whatever gcc comes with Ubuntu 16.04 and a custom built clang (version 6 or 7 I believe) and didn't have this issue.

**Comment by bridgeythegeek** [comment]
Hi @nathanjackson, I'm using the [pandare docker](https://hub.docker.com/r/pandare/panda), so:
```
root@afeb82912b03:/# uname -a
Linux afeb82912b03 5.0.0-23-generic #24~18.04.1-Ubuntu SMP Mon Jul 29 16:12:28 UTC 2019 x86_64 GNU/Linux

root@afeb82912b03:/# gcc --version
gcc (Debian 6.3.0-18+deb9u1) 6.3.0 20170516
Copyright (C) 2016 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

root@afeb82912b03:/# make --version
GNU Make 4.1
Built for x86_64-pc-linux-gnu
Copyright (C) 1988-2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

**Comment by nathanjackson** [comment]
Well its complaining about an issue related to the C standard verson. The GCC version you're using is getting old, I would think it would still work.

Could the panda source in that Docker image be out of date? I've never used it, so I'm not sure who manages it.

**Comment by m000** [comment]
@bridgeythegeek I guess that everyone is using `build.sh` instead of manually configuring. The script sets compatibility level to gnu11 for gcc<5.
https://github.com/panda-re/panda/blob/master/build.sh#L22-L40

**Comment by bridgeythegeek** [comment]
Yeah, seems like the pandare docker is not ideal (or at least not up to date).
Made my own `Dockerfile` (see below) to prepare an `ubuntu:16.04` environment.
Just need to run `./install_ubuntu.sh` once the container is running.

```
FROM ubuntu:16.04
RUN apt update
RUN echo >>/etc/apt/sources.list
RUN echo 'deb-src http://archive.ubuntu.com/ubuntu/ xenial main restricted' >>/etc/apt/sources.list
RUN echo 'deb-src http://archive.ubuntu.com/ubuntu/ xenial-updates main restricted' >>/etc/apt/sources.list
RUN apt update
RUN apt upgrade
RUN apt install -y wget vim tmux sudo lsb-release flex bison
RUN wget https://raw.githubusercontent.com/panda-re/panda/master/panda/scripts/install_ubuntu.sh
RUN chmod +x install_ubuntu.sh
WORKDIR /
CMD ["bash"]
```
