### ISSUE TITLE
snapshots version 0x00000004

### ISSUE THREAD

**Issue by volth** [panda-re/panda#475]
I found that many snapshots on rrshare.org ([archive version](http://web.archive.org/web/*/http://www.rrshare.org/content/rrlogs/*)) are stored in format with `QEMU_VM_FILE_VERSION 0x00000004`.

`panda` built from this repo fails to load them with error "Unsupported migration stream version".

Does it mean there was a `panda` built against a newer version of `qemu` ?

**Comment by moyix** [comment]
The images on rrshare are for PANDA 1.0, and are not compatible with PANDA 2.0 (this repository). The older images can still be replayed using PANDA 1.0, which is available here:

https://github.com/moyix/panda
