### ISSUE TITLE
PANDA_CB_GUEST_HYPERCALL not implemented for ARM

### ISSUE THREAD

**Issue by m000** [panda-re/panda#489]
While working on #488, I noticed that the code required for implementing the feature on ARM was missing. I open this issue as a reminder.

Since the documentation mentions many implementation details for ARM, this has probably been implemented in some branch or in PANDA-1, but not merged with the mainline.

**Comment by moyix** [comment]
Looks like it's in here:

https://github.com/moyix/panda/blob/9d63be65425d1a76dc963e45b753246654a3ae4d/qemu/panda_tools/pirate_utils/linux/pirate_mark.h#L49-L74

**Comment by m000** [comment]
Thanks for the pointers! I've updated #488 to include the implementation of the callback for ARM. I don't have anything in hand to test it, but it's a start. A review + feedback would be appreciated.
