### ISSUE TITLE
Build failed due to ambiguous type

### ISSUE THREAD

**Issue by ajgay** [panda-re/panda#490]
Building on Manjaro 4.19.69 via the install_arch.sh script, during which, build.sh fails due to a series of ambiguous type errors in several plugins. I cannot copy and paste from the build server but the errors are occuring in the below files:

`panda/panda/plugins/callstack_instr/callstack_instr.cpp:212
panda/panda/plugins/callstack_instr/callstack_instr.cpp:211
panda/panda/plugins/callstack_instr/callstack_instr.cpp:211
panda/panda/plugins/callstack_instr/callstack_instr.cpp:196
`
Errors are occuring due to ambiguity with the `target_*` types and the `abs()` function.

This affects the following plugins:
- panda_libfi
- panda_coverage
- panda_asidstory

**Comment by m000** [comment]
Hey ajgay. PR #487 contains several fixes for similar issues. Can you try building with it?

**Comment by ajgay** [comment]
This seems to have fixed it. Thank you for the quick response!
