### ISSUE TITLE
memory callback implementation

### ISSUE THREAD

**Issue by m000** [panda-re/panda#493]
I was looking in the implementation of the memory callbacks and I found something I couldn't make sense of: Why are `&result`/`&val` used when invoking registered callbacks from the helper functions? This is the address of a local variable. What is the use case for this? Unless I'm missing some detail, it would make more sense to instead pass `ram_ptr` to the user callback.

 https://github.com/panda-re/panda/blob/f0a64a1b3fe009a6ca55bdfb372444ae91fa5586/panda/src/callback_support.c#L207-L264

**Comment by moyix** [comment]
Yes, I think this was a botched attempt to allow callbacks to modify the value that was read from / written to memory. I vaguely recall a branch that fixed it, but unfortunately it's lost to time.

If you would like to try to make this work, I'd be happy to accept the PR.

**Comment by m000** [comment]
What would be the best fix for this? I can see a few options.

- Just run the callbacks with `ram_ptr`.
- Modify the API to add the original value as an argument. Let the plugins use what they see fit.
- Also modify the API so that plugins return e.g. `1` when they modify the memory. This value can be supplied to the plugins following in the list, so that they know if the memory has been modified without checking.

**Comment by AndrewFasano** [comment]
@tnballo and I have modified some callbacks lately to behave like what you describe @m000. One of us can try changing the after_mem_read callback and submit a PR
