### ISSUE TITLE
Debug Builds are Broken

### ISSUE THREAD

**Issue by nathanjackson** [panda-re/panda#500]
Sorry @m000, we just ran into another issue but this time with the RR API changes. I didn't try a debug build until now but we're getting a compilation error if you pass `--enable-debug` to the configure script.

```
panda/cpu-exec.c:717:9: error: ‘rr_on’ is static but used in inline function ‘debug_checkpoint’ which is not static [-Werror]
     if (rr_on() && cpu->rr_guest_instr_count >> 17 > counter_128k) {
```

**Comment by m000** [comment]
Just opened a new PR. Declaring `debug_checkpoint()` as `static inline` should be enough.  Thanks for the extensive testing!

**Comment by nathanjackson** [comment]
Thank you!
