### ISSUE TITLE
panda/testing should be moved to a separate repository

### ISSUE THREAD

**Issue by m000** [panda-re/panda#502]
While the testing framework is a very welcome addition, I don't thing it should be part of the main PANDA repository because of the size of the included replays:
```
% du -sh  panda/testing
565M	panda/testing
```

This is already more than the full history of the main QEMU repo, weighing ~460MB. Moreover, big files in a git repo is considered a bad practice. Even github warns you against this when you push one:
```
remote: warning: GH001: Large files detected. You may want to try Git Large File Storage - https://git-lfs.github.com.
remote: warning: See http://git.io/iEPt8g for more information.
remote: warning: File panda/testing/replays/scissors/netstat-rr-snp is 80.68 MB; this is larger than GitHub's recommended maximum file size of 50.00 MB
...
```

Purging the big files from the repo will require a history rewrite, so it should be done the soonest possible, with a short advance warning.

**Comment by jnmartin84** [comment]
Handling this now, should impact a small number of recent commits (from Oct 18 through today, 23 commits).

**Comment by m000** [comment]
@jnmartin84 Here are the steps:

**Preparation:**
1. Make a backup copy of the branch: `git branch master.old`.
2. Use `git log panda/testing` and write down the commits you want to purge.
3. Use `git show <commit_hash>` for each of the commits individually. Make note of any files outside `panda/testing` that are added/modified.

**Execution:**
1. If the earliest commit you want to purge is e.g. `abcdef`, do `git rebase -i abcdef~1`.
2. An editor will open with a list of all commits from `abcdef` and onwards. For the commits that you've written down, change `pick` to `drop`. Save and quit.
3. The rebase should complete successfully. If it doesn't abort (`git rebase --abort`) and send me the conflict message.

**Finalize:**
1. Compile PANDA locally to make sure everything runs.
2. Force push to master to rewrite the recent history: `git push -f origin`.

**Comment by jnmartin84** [comment]
so it looks like if I try to do this, it will lose 2 commits, 

```
commit e9f49162eb2867a9aa7255cbe2ff0ee87955223c
Merge: c2b4397 1a50574
Author: Brendan Dolan-Gavitt <brendandg@gatech.edu>
Date:   Sun Nov 3 13:07:12 2019 -0600

    Merge pull request #497 from m000/callbacks-cleanup
    
    Cleanup for PANDA callbacks + RR control API

commit c2b43976ca5546ce640e70663a8a478ce0464cbc
Merge: f0a64a1 d3ea928
Author: Brendan Dolan-Gavitt <brendandg@gatech.edu>
Date:   Fri Nov 1 10:03:06 2019 -0500

    Merge pull request #499 from rquarry/patch-1
    
    Update Manual Section "plugin zoo"

```


The "f0a64a1" is one of the commits to drop. Any advice?

**Comment by m000** [comment]
I'm not sure I understand. Why would you lose them? Dropping a commit means that history of the branch will be rewritten as if the commit never happened. The rest of the commits will remain unaffected.

Checking the current master, I believe you need to do:
`git rebase -i 41b191d69e04ba77f6551b932c5e00e5e57f0f1d~1`

And edit the rebase todo file to look like this:
```
**drop** 41b191d69e Changes for PANDA continuous integration and test server. Fixed asidstory PANDA plugin parameter string in asidstory1 test so test works. Modified set of enabled tests in regression test config. Added blessed regression test output along with replays that generated the outputs to panda/testing (regression test) directory.
**drop** f0a64a1b3f updated, validated replay and blessed test output for panda/jenkins integration
pick d3ea928979 Update Section "plugin zoo"
pick 3c7a67db68 PANDA callbacks: Restructuring of callback definitions.
pick 811448d0d0 PANDA callbacks: More type fixes for callback definitions in cb-defs.h.
pick 7f46e8cff7 PANDA callbacks: Annotated callbacks in cb-defs.h with the location the corresponding helper is invoked.
pick de52137ec5 PANDA callbacks: Generated cb-support.h from cb-defs.h.
pick ee20926d1f PANDA callbacks: Callback helper functions fixed to match cb-support.h header.
pick ff54e32629 PANDA core: Added calls for starting/stopping recording.
pick 34f08aaf9d PANDA core: Moved items related to controling rr to a separate header.
pick 649017cee2 PANDA core: Changed type of CPUState.panda_guest_pc to vaddr.
pick 0d5d3956cf PANDA core: Updated call names and header locations to match cb-support.h.
pick f546d4f72a PANDA core: Updated header locations to match cb-support.h.
pick b53c13a04c PANDA plugins: Fix PANDA plugin functions to match cb-defs.h.
pick 56687cba4d taint2: Fix to match cb-defs.h.
pick f3f90b46c8 mmio_trace: Fix to match cb-defs.h.
pick 93ac3aedd0 PANDA core: Eliminated rr_mode global and friends.
pick 114e9e562b PANDA core: Don't include cb-support.h in arm/ppc helper files.
pick 15c1336681 PANDA core: Removed obsolete callback_support.h header.
pick 3b1c0debf2 scripts: Added build-check.sh script for checking plugins for missing symbols.
pick 9b21399351 taint2: Fixed signature of on_replay_net_transfer().
pick 1a50574425 PANDA core: Fix for panda_callbacks_after_machine_init().
**drop** f662bd6808 removing replays for history rewrite.
```

Rebasing completes cleanly, and `panda/testing` is back to 148K:
```
% du -sh panda/testing                                                                                                                                               148K	panda/testing
```

**Comment by m000** [comment]
Ah... I see what you mean now.
The commits you mentioned no longer show up in the history. But that shouldn't be a problem. Those are the merge commits. The individual commits pulled in the history will still be there.

**Comment by jnmartin84** [comment]
ok, fingers crossed

**Comment by m000** [comment]
If you haven't forced push yet, you can diff your edited branch with origin/master to verify that thing are as intended.

**Comment by jnmartin84** [comment]
everything looked as expected after I double-checked given your last comment, push looks good

**Comment by jnmartin84** [comment]
Thank you for your help, from now on I'm staying out of the repo.

**Comment by m000** [comment]
Glad it worked. I believe the issue can be closed now. Thanks for the quick response!
