### ISSUE TITLE
osi_linux: cannot generate kernelinfo.conf for ARM target

### ISSUE THREAD

**Issue by kasperis7** [panda-re/panda#506]
I was generating kernelinfo.conf for a Debian 10 kernel of armvirt target.
output:
```
root@debian:~/kernelinfo# make
make -C /lib/modules/4.19.0-5-armmp-lpae/build M=/root/kernelinfo modules
make[1]: Entering directory '/usr/src/linux-headers-4.19.0-5-armmp-lpae'
  CC [M]  /root/kernelinfo/kernelinfo.o
/root/kernelinfo/kernelinfo.c: In function ‘init_module’:
/root/kernelinfo/kernelinfo.c:158:71: error: ‘current_task’ undeclared (first use in this function); did you mean ‘current_umask’?
 rintk(KERN_INFO "task.current_task_addr = %llu\n", (u64)(uintptr_t)&current_task);
                                                                     ^~~~~~~~~~~~
                                                                     current_umask
/root/kernelinfo/kernelinfo.c:158:71: note: each undeclared identifier is reported only once for each function it appears in
make[4]: *** [/usr/src/linux-headers-4.19.0-5-common/scripts/Makefile.build:315: /root/kernelinfo/kernelinfo.o] Error 1
make[3]: *** [/usr/src/linux-headers-4.19.0-5-common/Makefile:1539: _module_/root/kernelinfo] Error 2
make[2]: *** [Makefile:146: sub-make] Error 2
make[1]: *** [Makefile:8: all] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-4.19.0-5-armmp-lpae'
make: *** [Makefile:4: all] Error 2
```
kernel information:
```
root@debian:~/kernelinfo# uname -a
Linux debian 4.19.0-5-armmp-lpae #1 SMP Debian 4.19.37-5+deb10u1 (2019-07-19) armv7l GNU/Linux
```
`current_task` is an export symbol in /arch/x86/kernel/cpu/common.c. As for arm target, this symbol doesn't exist.

**Comment by m000** [comment]
Yes, the location of the `current_task` seems to be arch-specific. So we need to adapt the plugin for this. If you are familiar with ARM, can you come up with a PR? Maybe check how Volatility3 gets this information.

**Comment by jmcarter9t** [comment]
I ran into this as well. I believe the replacement is `current` for ARM.  Both `current` and `current_task` are `task_struct *`.  `current.h` for ARM is a surrogate for `asm-generic/current.h`. `asm-generic/current.h` defines `current <- current_thread_info()->task`.  Not 100\%, but this seems close

**Comment by AndrewFasano** [comment]
OSI arm now works after we merged #653- but you have to generate the kernelinfo using debug symbols with [this technique](https://github.com/panda-re/panda/tree/master/panda/plugins/osi_linux/utils/kernelinfo_gdb).

This is still a valid issue though because the normal approach to generating kernelinfo.conf files by compiling the module in the guest is still unsupported for arm.

**Comment by kasperis7** [comment]
Well, eventually I patched the code (changed `current_task` to `current`, and removed SMP-related part) and used the normal approach to generate the profile. I complied the kernel module with kernel source code in the host.

the kernelinfo_gdb method have some problems, although most of the time you will not encounter any of them:
* The script doesn't work when the kernel version string contains symbols (e.g. the "4.1.17+" kernel from raspbian). This is actually pretty easy to fix.
* When the linux kernel is compiled for multiple targets, the generated profile (obviously, you can get only one profile if you use this method) would not be suitable for every target. I compiled a kernel that supports both `virt` and `vexpress-a15`. As the result, the profile works for `vexpress-a15` but not for `virt`. As far as I know, at least their `init_addr` and `page_offset` are different on these two machines.

What's more, no matter which method i use(the normal one or the gdb one), I just cannot generate a working profile for `virt`.

**Comment by AndrewFasano** [comment]
Thanks for pointing out those problems - they're certainly things we want to fix!

PR #620 hopefully has all the fixes required to use the normal-method for generating OSI profiles for ARM guests. And I just pushed a commit there to fix the problem with kernel version that end with a `+`.

Your point about generating profiles for kernels that support multiple targets is something I've never considered before. @lacraig2 - do you have any ideas on how we could get the GDB method to work there?

Getting OSI working with the virt machine is something we're very interested but probably haven't tried. What kind of error/failures were you getting? The assertion about not being able to find the current task struct?

**Comment by kasperis7** [comment]
yes, it says:
```
panda-system-arm: /panda/panda/plugins/osi_linux/osi_linux.cpp:221: void on_first_syscall(CPUState*, target_ulong, target_ulong): Assertion `can_read_current(cpu) && "Couldn't find current task struct at first syscall"' failed.
```
I enabled `osi`,`osi_linux` and `osi_test`. The kernel I use:
```
root@debian:~/kernelinfo# uname -a
Linux debian 4.19.0-5-armmp-lpae #1 SMP Debian 4.19.37-5+deb10u1 (2019-07-19) armv7l GNU/Linux
```
