### ISSUE TITLE
appendix-a-callback-list is wrong

### ISSUE THREAD

**Issue by jxzhxch** [panda-re/panda#508]
![图片](https://user-images.githubusercontent.com/5178662/68843490-29743780-0703-11ea-9050-df6d13641bf5.png)

**Comment by moyix** [comment]
Thanks! Do you want to submit a quick PR to fix the documentation issue?

**Comment by jxzhxch** [comment]
> 
> 
> Thanks! Do you want to submit a quick PR to fix the documentation issue?
