### ISSUE TITLE
Tainted_Instr plugin file viewer

### ISSUE THREAD

**Issue by DOT850** [panda-re/panda#510]
I believe in order to examine *.plog files from the tainted_instr pluging requires "tainted_instr.cpp" to be built. However the docs seem to be copied over from Panda 1 and the tainted_instr.cpp file does not exist in Panda 2?

Any recommendations on how to proceed? I'm in the process of building up Panda 1 to see how it is supposed to work but having compatibility issues.

**Comment by moyix** [comment]
To view plog files, you can use `plog_reader.py`:

https://github.com/panda-re/panda/blob/master/panda/scripts/plog_reader.py

**Comment by DOT850** [comment]
Thanks. Kind of emabrassing that I missed that!

**Comment by nathanjackson** [comment]
@DOT850 You can also use the {{ida_taint2}} plugin. The plugin is called {{ida_taint2}}, but its output is just a CSV file. I've found that's occasionally easier to use unless you need a callstack.
