### ISSUE TITLE
error: XDG_RUNTIME_DIR not set in the environment. gtk initialization failed

### ISSUE THREAD

**Issue by am1250** [panda-re/panda#513]
```bash
root@0d5bd56cc124:/panda/panda/scripts/panda/build# ./qemu-img create -f qcow2 winXP_tiny.img 10G
Formatting 'winXP_tiny.img', fmt=qcow2 size=10737418240 encryption=off cluster_size=65536 lazy_refcounts=off refcount_bits=16
root@0d5bd56cc124:/panda/panda/scripts/panda/build# x86_64-softmmu/panda-system-x86_64 -m 2G winXP_tiny.img -cdrom /am1250/TinyXP.iso 
error: XDG_RUNTIME_DIR not set in the environment.
gtk initialization failed
```

I can successfully use `qemu-img` to create a `.qcow2` or `.img` file , however, when I tried to use `panda-system-x86_64` or `panda-system-i386` to install system into it, the error **" XDG_RUNTIME_DIR not set in the environment.
gtk initialization failed "** came out. 

System : Ubuntu 14.04 LTS(using the official docker image)
and Panda was successfully built by `install_ubuntu.sh` without error. 

Please give me some advices to solve this problem, thank you very much!

**Comment by moyix** [comment]
It looks like you may be trying to run PANDA inside of a docker container. You have to do some extra work to get anything that uses a GUI to work inside Docker:

http://fabiorehm.com/blog/2014/09/11/running-gui-apps-with-docker/

Alternatively, you can tell PANDA to just use a VNC display with `-vnc localhost:0` and then forwarding port 5900 into the container. Or, if the image you're trying to run doesn't need a GUI (though based on the name winXP I suppose it probably does), you can use `-display none` to disable graphics.
