### ISSUE TITLE
Problems with signal-handling for threaded panda.run() (pypanda)

### ISSUE THREAD

**Issue by mariusmue** [panda-re/panda#540]
Hi all,

I'm banging my head against this since yesterday, and have no good solution available (yet), hence this issue.
When running the run() function from pypanda inside a thread, a SIGINT (ctrl+c) will not lead to termination of the process.
Small script to reproduce (modified version of an old unicorn.py, working on current master):
```python                                                               
#!/usr/bin/env python3

import capstone
from sys import argv
from os import path, remove as os_remove
import threading
import time

from panda import Panda, ffi
from panda.arm.helper import dump_regs, registers


code = [ # While true, inc R0. With a nop because I'm bad at shellcoding
    b"\x01\x00\x80\xe2", # add r0, #1
    b"\x01\x10\xa0\xe1", # mov r1, r1 (NOP)
    b"\x10\xf0\x4f\xe2", # sub r15, #16
]
ARM_CODE = b"".join(code)


config_path = "/tmp/config_panda.json"
def make_config(addr=0x1000, size=0x1000):
    # TODO: for each user-specified memory mapping, make it

    # Always make a new config file
    if path.isfile(config_path):
        os_remove(config_path)

    with open(config_path, "w") as f:
        f.write("""{{"memory_mapping": [ {{
          "is_special": false, "is_symbolic": false, "forwarded": false,
          "permissions": "rwx", "name": "mem1", "size": 4096,
          "address": {addr}}} ],
      "entry_address": {addr},
      "kernel": "/dev/null"
    }}""".format(addr = addr))

# Setup memory mappings file
ADDRESS = 0x8000000
make_config(ADDRESS)

# Initialize emulator
args = ["-M", "configurable",
        "-kernel", config_path,
        "-nographic"]
panda = Panda(arch="arm", extra_args=args)

# On machine init, setup reg_writes and mem_writes
@panda.cb_after_machine_init
def my_init(env):
    # Map code into memory
    panda.physical_memory_write(ADDRESS, ARM_CODE)

    # Set registers
    env.env_ptr.regs[registers['R0']] = 0
    env.env_ptr.pc = ADDRESS


# VMI: before each block, print disassembly
md = capstone.Cs(capstone.CS_ARCH_ARM, capstone.CS_MODE_ARM)
block_count = 0
@panda.cb_before_block_exec
def before_block(env, tb):
    global block_count
    print(f"Block 0x{block_count:x}")

    pc = panda.current_pc(env)
    code_buf = ffi.new("char[]", tb.size)
    code = panda.virtual_memory_read(env, tb.pc, tb.size)

    for i in md.disasm(code, tb.pc):
        print("0x%x:\t%s\t%s" %(i.address, i.mnemonic, i.op_str))

    if block_count == 10:
        print("After 10 blocks, R0 = ", hex(env.env_ptr.regs[registers['R0']]))
        #panda.end_analysis()
    block_count += 1

t = threading.Thread(target=panda.run, daemon=True) # daemon or not doesn't make a difference here
t.start()

# Simulate bunch of other operations in main thread
while True:
    time.sleep(1)
print("Finished emulation")
```

When sending SIGINT/SIGTERM/SIGHUB to the process, it hangs, instead of terminating.
My intuition is it that it is related to the way QEMU handles those signals, as it registers its own signal-handler for it, potentially overwriting the ones from python.

I know that running pypanda from a thread is not the intended way of using it, however, in the context of avatar2, execution is driven asynchronously and pypanda is not only interfaced via python, but also via QEMUs gdbstub and QMP (which, impressively, works out of the box).
Hence, please let me know if you are interested in solving this issue, or whether I have to look out for an avatar-local workaround.

Suggested solutions/workaround:
- In `os-posix.c:os_setup_signal_handling`, an additional check whether we are in library mode could be added. If so, don't register QEMUs signal handler. This would break the currently pypanda.was_aborted() functionality, but allows "proper" signal handling from python.
- Introduction of a non-blocking version of pypanda.run(), so that it can be called from the mainthread.

Side observation:
While digging into this, I also noticed that pypandas athread is not stopped by default on end_analysis(). While this is not a problem due to the daemonic nature of that thread, it may be worth considering stopping it as well?

//edit: typo fix

**Comment by AndrewFasano** [comment]
I'm going to take a look at this and try to get it fixed for you - sorry for the delay

**Comment by AndrewFasano** [comment]
I've been pursuing your first suggestion and ran into a non-trivial issue with it. When the PANDA/qemu signal handlers are disabled, CFFI seems to consume the KeyboardInterrupt exceptions, print a warning, and then it drops them without giving us a chance to respond. 

For example, a script with a before block exec that prints a message every 0x100000 blocks behaves as follows:

```
Running
Basic_blocks executed = 0x0
Basic_blocks executed = 0x100000
^CFrom cffi callback <bound method Panda.__main_loop_wait_cb of <pandare.panda.Panda object at 0x7ff691a79ac8>>:
Traceback (most recent call last):
  File "/home/andrew/git/panda/panda/python/core/pandare/panda.py", line 229, in __main_loop_wait_cb
    def __main_loop_wait_cb(self):
KeyboardInterrupt
Basic_blocks executed = 0x200000
Basic_blocks executed = 0x300000
```

It looks like the exception is being raised where we want, but it never triggers the try/catch in the `__main_loop_wait_cb` function so I think it's happening within CFFI somewhere.

Anyone have ideas? @lacraig2?

**Comment by lacraig2** [comment]
Sure. I've got some ideas. @mariusme made a great suggestion in `os-posix.c:os_setup_signal_handling`. Instead of adding a different case there I've added `panda_setup_signal_handling` to panda_api.c so that a custom python handler can be used (on #779).

This script below allows us to terminate at any point. Whether or not it is actually doing the right thing and cleaning up isn't entirely clear.

I think we'd likely add a panda method that would do something similar below and then call the setup after initialization.

```python
#!/usr/bin/env python3

import capstone
from sys import argv
from os import path, remove as os_remove
import threading
import time
import signal

from pandare import Panda, ffi

code = [ # While true, inc R0. With a nop because I'm bad at shellcoding
    b"\x01\x00\x80\xe2", # add r0, #1
    b"\x01\x10\xa0\xe1", # mov r1, r1 (NOP)
    b"\x10\xf0\x4f\xe2", # sub r15, #16
]
ARM_CODE = b"".join(code)


config_path = "/tmp/config_panda.json"
def make_config(addr=0x1001, size=0x1000):
    # TODO: for each user-specified memory mapping, make it

    # Always make a new config file
    if path.isfile(config_path):
        os_remove(config_path)

    with open(config_path, "w") as f:
        f.write("""{{"memory_mapping": [ {{
          "is_special": false, "is_symbolic": false, "forwarded": false,
          "permissions": "rwx", "name": "mem1", "size": 4096,
          "address": {addr}}} ],
      "entry_address": {addr},
      "kernel": "/dev/null"
    }}""".format(addr = addr))

# Setup memory mappings file
ADDRESS = 0x8000000
make_config(ADDRESS)

# Initialize emulator
args = ["-M", "configurable",
        "-kernel", config_path,
        "-nographic"]
panda = Panda(arch="arm", extra_args=args)

# On machine init, setup reg_writes and mem_writes
@panda.cb_after_machine_init
def my_init(env):
    # Map code into memory
    panda.physical_memory_write(ADDRESS, ARM_CODE)

    # Set registers
    env.env_ptr.regs[panda.arch.registers['R0']] = 0
    env.env_ptr.pc = ADDRESS

@ffi.callback("void(int,void*,void*)")
def SigTest(SIG,a,b):
    print("SIGINT Caught")
    import os
    os._exit(0)

# VMI: before each block, print disassembly
md = capstone.Cs(capstone.CS_ARCH_ARM, capstone.CS_MODE_ARM)
block_count = 0

ffi.cdef("void panda_setup_signal_handling(void (*f) (int,void*,void*));")

@panda.cb_before_block_exec
def before_block(env, tb):
    panda.libpanda.panda_setup_signal_handling(SigTest)
    global block_count
    if block_count % 0x100000 == 0:
        print(f"Block_count = 0x{block_count:x}")

    if block_count == 0x100000*10:
        print("Failure - ending explicitly")
        panda.end_analysis()
    block_count += 1


try:
    panda.run()
except KeyboardInterrupt:
    print("Killed")

print("Finishing...")
```

**Comment by AndrewFasano** [comment]
I think we can get this to work without having to explicitly call a function from the pypanda script. Maybe something between our two PRs would work - if in library mode, we setup signal handlers with your `panda_setup_signal_handling` and then it should (hopefully) just work.

**Comment by lacraig2** [comment]
> I think we can get this to work without having to explicitly call a function from the pypanda script.

I want to clarify that this would be something that the panda.py setup methods would call and not an individual pypanda script.

I think this works a lot better as an API call. That is to say if you can `panda_setup_signal_handling` you have decided to take ownership of the signals and handle them with your own methodology in your own function.

That is not to say that some combination of these PRs wouldn't work, but I have some concerns with your method in #776. In particular, I don't know that always blocking PANDA from setting up signal handlers is a good idea. I also don't know what the default signal handlers would be in a situation like we have when we call a new thread from a cffi context in python. I really think the default should be that PANDA has signal handlers set up and that we can take ownership of them through the API. I'd expect the pypanda implementation to automatically take them over after setup.

@AndrewFasano Thoughts?

**Comment by mariusmue** [comment]
I agree that taking ownership of signals should happen exactly once, as deregistering already registered signal handlers in the C-world could be error-prone. Another idea (opposed to adding more logic to the initialization of pypanda) could be an additional environment variable which is set by the parent process gets only checked in os_setup_signal_handling.

(This would need additional documentation, but is straight forward from implementation side)

**Comment by lacraig2** [comment]
@mariusmue I ended up doing something similar to this in my PR (#779). I have an API side which allows a custom function to be handed over to C. Then in `osi-posix.c` I can check whether or not this function has been set. If it has the function is re-installed. I believe this may be necessary in our threading model.

Anyhow that PR does a bunch of stuff in python. It makes us handle both signals and exceptions properly.
