### ISSUE TITLE
Documentation out of date. Can't run osi_linux example.

### ISSUE THREAD

**Issue by janbbeck** [panda-re/panda#548]
I am following the documentation to run osi_linux as given here:
[https://github.com/panda-re/panda/tree/master/panda/plugins/osi_linux](url)

For testing I spun up a ubuntu-18.04.3-desktop-amd64.iso image in live modeas a guest:

`./panda/build/x86_64-softmmu/panda-system-x86_64 -m 3G -cdrom 'ubuntu-18.04.3-desktop-amd64.iso' -monitor stdio`

Recording works fine, and so does the replay with replaymovie. Next, I wanted to try the osi_linux as per the instructions above. I created a new kernelconf.info entry as described in the readme:

```
[my_kernel_info]
name = 5.0.0-23-generic|#24~18.04.1-Ubuntu SMP Mon Jul 29 16:12:28 UTC 2019|x86_64
version.a = 5
version.b = 0
version.c = 15
task.per_cpu_offsets_addr = 18446744071846983712
task.per_cpu_offset_0_addr = 18446616393938894848
task.current_task_addr = 89088
task.init_addr = 18446744071849473856
#task.per_cpu_offsets_addr = FFFFFFFF90FB7820
#task.per_cpu_offset_0_addr = 0xFFFF8BE03CA00000
#task.current_task_addr = 0x00015C00
#task.init_addr = 0xFFFFFFFF91217740
task.size = 9152
task.tasks_offset = 1960
task.pid_offset = 2216
task.tgid_offset = 2220
task.group_leader_offset = 2280
task.thread_group_offset = 2392
task.real_parent_offset = 2232
task.parent_offset = 2240
task.mm_offset = 2040
task.stack_offset = 24
task.real_cred_offset = 2624
task.cred_offset = 2632
task.comm_offset = 2640
task.comm_size = 16
task.files_offset = 2712
cred.uid_offset = 4
cred.gid_offset = 8
cred.euid_offset = 20
cred.egid_offset = 24
mm.size = 1032
mm.mmap_offset = 0
mm.pgd_offset = 80
mm.arg_start_offset = 304
mm.start_brk_offset = 280
mm.brk_offset = 288
mm.start_stack_offset = 296
vma.size = 208
vma.vm_mm_offset = 64
vma.vm_start_offset = 0
vma.vm_end_offset = 8
vma.vm_next_offset = 16
vma.vm_flags_offset = 80
vma.vm_file_offset = 160
fs.f_path_dentry_offset = 24
fs.f_path_mnt_offset = 16
fs.f_pos_offset = 104
fs.fdt_offset = 32
fs.fdtab_offset = 40
fs.fd_offset = 8
qstr.size = 16
qstr.name_offset = 8
path.d_name_offset = 32
path.d_iname_offset = 56
path.d_parent_offset = 24
path.d_op_offset = 96
path.d_dname_offset = 72
path.mnt_root_offset = 0
path.mnt_parent_offset = -16
path.mnt_mountpoint_offset = -8
```
The instruction in the readme then states to run
`panda-system-x86_64 -m 3G -replay ch28 -panda osi -panda osi_linux:kconf_file=kernelinfo.conf,kconf_group=my_kernel_info -panda osi_test`

which fails

```
PANDA[osi_linux]:adding argument kconf_file=kernelinfo.conf.
PANDA[osi_linux]:adding argument kconf_group=my_kernel_info.
PANDA[core]:initializing osi
panda-system-x86_64: /home/ubuntu/panda/panda/scripts/panda/panda/plugins/osi/os_intro.c:128: init_plugin: Assertion `!(panda_os_familyno == OS_UNKNOWN)' failed.
Aborted (core dumped)
```
**What I have tried (1):**
A bit of digging around in os_intro.c and using google yielded some progress when adding the -os option:
`
panda-system-x86_64 -m 3G -replay ch28 -panda osi -panda osi_linux:kconf_file=kernelinfo.conf,kconf_group=my_kernel_info -panda osi_test -os linux-64-ubuntu`

but it still fails:
```
PANDA[osi_linux]:adding argument kconf_file=kernelinfo.conf.
PANDA[osi_linux]:adding argument kconf_group=my_kernel_info.
PANDA[core]:os_familyno=2 bits=64 os_details=ubuntu
PANDA[core]:initializing osi
PANDA[core]:loading required plugin osi_linux
PANDA[core]:initializing osi_linux
PANDA[osi_linux]:E:osi_linux.cpp(init_plugin)> Failed to read group my_kernel_info from kernelinfo.conf.
PANDA[core]:FAILED to load required plugin osi_linux from /home/ubuntu/panda/panda/scripts/panda/build/x86_64-softmmu/panda/plugins/panda_osi_linux.so
Aborted (core dumped)
```
**What I have tried (2):**
I found that when changing the name of the configuration to be closer to the existing ones, then it goes even further, i.e.:
`[my_kernel_info]`
to
`[ubuntu:5.0.0-23-generic:64]`

then it almost works:

```
panda-system-x86_64 -m 3G -replay ch28 -panda osi -panda osi_linux:kconf_group=ubuntu:5.0.0-23-generic:64 -os linux-64-ubuntu
PANDA[osi_linux]:adding argument kconf_group=ubuntu:5.0.0-23-generic:64.
PANDA[core]:os_familyno=2 bits=64 os_details=ubuntu
PANDA[core]:initializing osi
PANDA[core]:loading required plugin osi_linux
PANDA[core]:initializing osi_linux
PANDA[osi_linux]:W> kernelinfo bytes [20-23] not read
PANDA[osi_linux]:W> kernelinfo bytes [124-127] not read
PANDA[core]:/home/ubuntu/panda/panda/scripts/panda/build/x86_64-softmmu/panda/plugins/panda_osi_linux.so already loaded
loading snapshot
... done.
opening nondet log for read :	./ch28-rr-nondet.log
PANDA[osi_linux]:E:osi_linux.cpp(init_per_cpu_offsets)> Unable to update value of ki.task.per_cpu_offset_0_addr.
panda-system-x86_64: /home/ubuntu/panda/panda/scripts/panda/panda/plugins/osi_linux/osi_linux.cpp:522: void init_per_cpu_offsets(CPUState*): Assertion `false' failed.
Aborted (core dumped)
```

I have now run out of ideas, and would like it if you could either point out my error or update the example in the documentation.

Thanks for taking the time to read this.

**Comment by m000** [comment]
Attempt one seems strange. My guess is that you just happened to not have kernelinfo.conf in the right directory. There's no special message printed for that AFAICS.

The second attempt is more interesting. Note that AFAIK linux 5 has not been tested by anyone. Personally, I'm still stuck to linux 4.4.0.
I'm not sure whether linux 5 has any boot-time/runtime address space randomization enabled by default. This would be something we're not accounting for. Can you reboot your VM and extract your kernel profile again? Are the printed task-addresses the same?

**Comment by janbbeck** [comment]
> Attempt one seems strange. My guess is that you just happened to not have kernelinfo.conf in the right directory. There's no special message printed for that AFAICS.
> 
> The second attempt is more interesting. Note that AFAIK linux 5 has not been tested by anyone. Personally, I'm still stuck to linux 4.4.0.
> I'm not sure whether linux 5 has any boot-time/runtime address space randomization enabled by default. This would be something we're not accounting for. Can you reboot your VM and extract your kernel profile again? Are the printed task-addresses the same?

Thanks for the reply! As you said, address randomization was to blame. If I pull the randomized kernelinfo from the machine before recording, and then use it to replay - it works. But only when including the -os option:
`./panda/build/x86_64-softmmu/panda-system-x86_64 -m 3G -replay myrecord -panda osi -panda osi_linux:kconf_group=ubuntu:5.0.0-23-generic:64 -os linux-64-ubuntu`

it then looks at the kernelinfo.conf included with panda at
`panda/panda/scripts/panda/build/x86_64-softmmu/panda/plugins/osi_linux`

where should kernelinfo.conf be?

**Comment by janbbeck** [comment]
I would like to bump this one more time. Can you tell me if I am doing something wrong, or if the documentation has to be changed? I am glad to fix the docs to reflect what works for me (using the -os switch) and make a pull request. But it would be silly to do if I am not running the software correctly.

**Comment by m000** [comment]
- Location of `kernelinfo.conf`, I remember that the search locations for the file were reasonable, and never had an issue missing it. It should be fairly easy to trace why your file wasn't picked up by adding a couple of debug printouts.
You could send a PR which makes the fail message more informative, or expand the list of search locations if some "reasonable" search location is missing. And perhaps add some information in `README.md` of `osi_linux` about the location where `kernelinfo.conf` is searched for.

- The `-os` QEMU option is required by the `osi` plugin. Documentation can be improved though, to (a) make clear that the option is required for `osi` to work, and (b) to clarify that `-os` is parsed as a QEMU option, unlike options for other plugins.
In principle, it should be possible to make `-os` option a regular plugin option. But this should also require changes in the initialization of some plugins that use `osi`.

**Comment by m000** [comment]
Last but not least, it's great to hear that `osi_linux` works with linux 5. I can see two (different) additions that would be helpful here:
- See if runtime randomization can be disabled by a boot-time flag. If yes, extract a kernel profile and append it to `kernelifno.conf`. Expand `README.md` with details of how the profile can be used (i.e. what is the required boot-time flag).
- Maybe check if kernel address space randomization can be defeated by leaking additional information in `kernelinfo.conf`? E.g. if a randomization seed is kept at a fixed address, leaking the address should be a step towards making `osi_linux` with kernel address space randomization. (Disclaimer: I haven't read about the implementation of the feature on linux. I may be completely off here.)

**Comment by janbbeck** [comment]
Ok, the boot parameter to disable KASLR is `nokaslr`

I fixed the documentation, by adding a new example. I also added kernel parameters to `kernelinfo.conf` for the kernels that come with Ubuntu 18.04.3 and 18.04.4

I put in a pull request for this at #559

**Comment by anafsah** [comment]
I bumped into a similar problem when using the osi_linux option for ARM architecture. 

`/home/.../panda/build/arm-softmmu/panda-system-arm -M versatilepb -kernel /home/.../vmlinuz-3.2.0-4-versatile -initrd /home/.../initrd.img-3.2.0-4-versatile -hda /home/.../debian_wheezy_armel_standard.qcow2 -append 'root=/dev/sda1' -net nic -net user,hostfwd=tcp::10029-:22 -monitor stdio -replay capture1 -panda osi -panda osi_linux:kconf_file=kernelinfo.conf,kconf_group=debian:3.2.0-4-versatile:32 -os linux-32-arm -panda osi_test`

This is the error message that I see.
`PANDA[osi_linux]:adding argument kconf_file=kernelinfo.conf.`
`PANDA[osi_linux]:adding argument kconf_group=debian:3.2.0-4-versatile:32.`
`PANDA[core]:os_familyno=2 bits=32 os_details=arm`
`PANDA[core]:initializing osi`
`PANDA[core]:loading required plugin osi_linux`
`PANDA[core]:initializing osi_linux`
`PANDA[osi_linux]:E:osi_linux.cpp(init_plugin)> Failed to read group debian:3.2.0-4-versatile:32 from kernelinfo.conf.`
`PANDA[core]:FAILED to load required plugin osi_linux from /home/.../panda/build/arm-softmmu/panda/plugins/panda_osi_linux.so`
`Aborted (core dumped)`

I have the configurations in kernelinfo.conf file under `./panda/build/arm-softmmu/panda/plugins` directory. Seeing that it picks from a shared object file, I tried make in the arm-softmmu directory but the error didn't change.

Where am I going wrong?

**Comment by anafsah** [comment]
I gave the error another try,  and put the full path of kernelinfo.conf file which has the configuration.
It successfull loads the osi plugins and runs to error at loading the snapshot.

`PANDA[osi_linux]:adding argument kconf_group=debian:3.2.0-4-versatile:32.`
`PANDA[core]:os_familyno=2 bits=32 os_details=arm`
`PANDA[core]:initializing osi`
`PANDA[core]:loading required plugin osi_linux`
`PANDA[core]:initializing osi_linux`
`PANDA[osi_linux]:W> kernelinfo bytes [20-23] not read`
`PANDA[osi_linux]:W> kernelinfo bytes [124-127] not read`
`PANDA[core]:/home/afsah/tryingPanda/panda/build/arm-softmmu/panda/plugins/panda_osi_linux.so already loaded`
`PANDA[core]:initializing osi_test`
`PANDA[core]:loading required plugin osi`
`PANDA[core]:/home/afsah/tryingPanda/panda/build/arm-softmmu/panda/plugins/panda_osi.so already loaded`
`QEMU 2.9.1 monitor - type 'help' for more information`
`(qemu) audio: Could not init oss' audio driver`
`loading snapshot`
`panda-system-arm: /home/.../panda/panda/plugins/osi_linux/default_profile.cpp:12: target_ptr_t default_get_current_task_struct(CPUState*): Assertion err == struct_get_ret_t::SUCCESS && "failed to get current task struct"' failed.`
`Aborted (core dumped)`

**Comment by AndrewFasano** [comment]
Hi anafsah, Have you tried the latest version of the code? We recently fixed a bug related to OSI and restoring from snapshots in #569

**Comment by anafsah** [comment]
Now, it isn't able to find the path to osi plugin.
`PANDA[osi]:Failed to resolve path for plugin.`

**Comment by anafsah** [comment]
Hi Andrew,
I tried the it (95fb1a9) today. The error is resolved, but I get this error now.
`QEMU 2.9.1 monitor - type 'help' for more information`
`(qemu) audio: Could not init `oss' audio driver`
`loading snapshot`
`panda-system-arm: Missing section footer for sd-card`
`Failed to load vmstate`
`Failed to start replay`

**Comment by AndrewFasano** [comment]
I’m sorry you’re running into all these errors! Hopefully this is the last
one. I made a change fairly recently that has (temporarily) broken our
ability to restore from arm snapshots that were taken before the fix. It’s
slightly described in issue #560. For now could you try regenerating  the
snapshot if it’s one you created. Or if you’re trying to use the root
snapshot of the generic Debian qcow provided by moyix, you can download a
newer version (that I think shouldn’t have this issue) from
http://panda-re.mit.edu/qcows/linux/debian/7.3/arm/

Does that work for you?

**Comment by anafsah** [comment]
I see that the fix 7c647d3 was committed on Jan 16 13:28:11 2018. I have been recording in the past 4 days using qcow from https://people.debian.org/~aurel32/qemu/armel/. I am at 492ee10. But I am still not able to use osi or debug.
 
I tried changing the qcow to the one provided by moyix and it didn't change anything

Also, I tried using osi for i386, and it failed as well.
```
QEMU 2.9.1 monitor - type 'help' for more information
(qemu) loading snapshot
... done.
opening nondet log for read :	./snap_0aa7adbbfbaf641b2dd011f2e94c22c7-rr-nondet.log
RR rr_assertion `current_item' failed at /home/afsah/tryingPanda/panda/panda/src/rr/rr_log.c:977
Current log point:
{guest_instr_count=340}
Next log entry type: RR_INPUT_8
Current replay point:
{guest_instr_count=337}
Aborted (core dumped)
```

**Comment by AndrewFasano** [comment]
That commit was merged into our master branch three weeks ago in #555  - it was a fix from upstream qemu that we backported to fix an old qemu bug where snapshotting wasn't working on arm guests with SD cards. Unfortunately ARM snapshots taken before that patch (both for upstream qemu and for panda) cannot be loaded using builds from after it was applied. We're trying to fix that, but for now, that's the way it is. It sounds like your recordings were taken before that patch but then you tried 95fb1a9d0b189168d89ebb19765c35f1a9847756 after the patch so you got the error about the sd-card.

Can you open a new issue for the problem you're having with i386 and any other problems you're having. This isn't really related to janbbeck's issue anymore.

**Comment by anafsah** [comment]
I see. Thank you for the efforts and apologies for the inconvenience caused.

**Comment by hanetzer** [comment]
I'm having similar issue with windows-32-7 vm. Invocation is like so:
```
./bin/panda-system-x86_64 img.qcow2 -monitor stdio -m 4096 -os windows-32-7
begin_rec vst2
<do stuff>
end_rec
shutdown
./bin/panda-system-i386 -m 4096 -os windows-32-7 -replay vst2 -panda \
    stringsearch:name=known,callers=2
PANDA[core]:os_familyno=1 bits=32 os_details=7
PANDA[stringsearch]:adding argument name=known.
PANDA[stringsearch]:adding argument callers=2.
PANDA[core]:initializing stringsearch
PANDA[core]:loading required plugin callstack_instr
PANDA[core]:initializing callstack_instr
callstack_instr:  setting up threaded stack_type
PANDA[core]:loading required plugin osi
PANDA[core]:initializing osi
PANDA[core]:loading required plugin wintrospection
PANDA[core]:initializing wintrospection
PANDA[core]:loading required plugin win7x86intro
PANDA[core]:initializing win7x86intro
search strings file [known_search_strings.txt]
stringsearch: added string of length 32 to search set
stringsearch: added string of length 16 to search set
loading snapshot
panda-system-i386: Missing section footer for cpu
Failed to load vmstate
Failed to start replay

```

**Comment by hanetzer** [comment]
Note that this recording was taken on the same commit as the attempted playback:
9b97a6b9b1d5e5e6db1c9e88de0bc37b72fae50f

**Comment by hanetzer** [comment]
Oh. I think that was my mistake. I could have miscopied, but as you can see,
record binary is panda-system-x86_64 and playback is panda-system-i386.
