### ISSUE TITLE
How to trace only specific process

### ISSUE THREAD

**Issue by kingsleyluoxin** [panda-re/panda#551]
Hello, I am trying to use PANDA to record and replay how wget handles packets. So I only need to taint the received network data with wget. When replaying, how can I turn off the taint2 plugin when wget exits?

**Comment by nathanjackson** [comment]
I don't think there is an easy way to turn off taint2 when a program exits, but you could use asidstory + scissors to trim your recording.

**Comment by kingsleyluoxin** [comment]
Thanks for your suggestion. I will try it.

**Comment by kingsleyluoxin** [comment]
I have tried to use asidstory+scissors to trim the recording. It did work. However, I found the trimmed recording did not include the whole process of  network data. (I used plugin -panda network to get pcap file from the trimmed recording and found it had lost the communication data.) @nathanjackson

**Comment by nathanjackson** [comment]
In that case I would generate a pcap file from your replay and note the desired packet's instruction count (which can be found under packet comments in Wireshark). Use this number as your start instruction count. Then use the end instruction count you found from asidstory.

You can further reduce the amount data that gets tainted by using the packets\bytes arguments for `tainted_net`.

**Comment by kingsleyluoxin** [comment]
Thanks a ton. This really helps a lot. Actually, I have tried tainted_net with filtered packets and bytes. I also tried to use stringsearch to locate the received data during replay. This also gives me useful information.

**Comment by kingsleyluoxin** [comment]
Hello, I am actually applying PANDA to protocol reverse engineering. I am trying to mark the received network data as taint source. What I need to do is recording instructions dealing with each tainted bytes. Now, with the help of tainted_net, I can mark the received data. But I am wondering how I can  stop the taint engine so that I can output the instruction traces. Will it be applicable to unload taint2 plugin at the appropriate points, e.g., the point where some specific syscall happens?
