### ISSUE TITLE
osi_linux: profile creation error on ARM and PPC machine

### ISSUE THREAD

**Issue by anafsah** [panda-re/panda#573]
I am trying to build the kernel.conf file on ARM and PPC guest as outlined in the documentation.

`root@debian-armel:~/kernelinfo# make`
`make -C /lib/modules/3.2.0-4-versatile/build M=/root/kernelinfo modules`
`make[1]: Entering directory /usr/src/linux-headers-3.2.0-4-versatile`
`  CC [M]  /root/kernelinfo/kernelinfo.o`
`/root/kernelinfo/kernelinfo.c: In function ‘init_module’:`
`/root/kernelinfo/kernelinfo.c:156:74: error: ‘__per_cpu_offset’ undeclared (first use in this function)`
`/root/kernelinfo/kernelinfo.c:156:74: note: each undeclared identifier is reported only once for each function it appears in
/root/kernelinfo/kernelinfo.c:158:71: error: ‘current_task’ undeclared (first use in this function)`
`make[4]: *** [/root/kernelinfo/kernelinfo.o] Error 1`
`make[3]: *** [_module_/root/kernelinfo] Error 2`
`make[2]: *** [sub-make] Error 2`
`make[1]: *** [all] Error 2`
`make[1]: Leaving directory /usr/src/linux-headers-3.2.0-4-versatile`
`make: *** [all] Error 2`

System information:
`root@debian-armel:~/kernelinfo# uname -a`
`Linux debian-armel 3.2.0-4-versatile #1 Debian 3.2.51-1 armv5tejl GNU/Linux
`

**Comment by AndrewFasano** [comment]
I think this is the same as #506, though that was arm specific. There's a PR pending that might fix it for arm- #564. If you'd like to try that out and let us know if it works, that would help us get it merged faster

**Comment by anafsah** [comment]
Hi Andrew. Thank you for the heads up. I tried the fix for #506 . It is picking up the values correctly. But now, I then got a different set of errors.

`make -C /lib/modules/3.2.0-4-versatile/build M=/root/kernelinfo modules`
`make[1]: Entering directory `/usr/src/linux-headers-3.2.0-4-versatile'`
`  CC [M]  /root/kernelinfo/kernelinfo.o`
`/root/kernelinfo/kernelinfo.c: In function ‘init_module’:`
`/root/kernelinfo/kernelinfo.c:179:70: error: lvalue required as unary ‘&’ operand`
`/root/kernelinfo/kernelinfo.c:197:75: error: lvalue required as unary ‘&’ operand`
`make[4]: *** [/root/kernelinfo/kernelinfo.o] Error 1`
`make[3]: *** [_module_/root/kernelinfo] Error 2`
`make[2]: *** [sub-make] Error 2`
`make[1]: *** [all] Error 2`
`make[1]: Leaving directory `/usr/src/linux-headers-3.2.0-4-versatile'`
`make: *** [all] Error 2`

Upon checking it seemed that `current` (used in line 179 and 197) is a temporary value. 
`printk(KERN_INFO "task.current_task_addr = %llu\n", (u64)(uintptr_t)&current);`
So, I just prepended current with '*current' which makes is `&*current` not. And it compiled successfully.

`root@debian-armel:~/kernelinfo# make`
`make -C /lib/modules/3.2.0-4-versatile/build M=/root/kernelinfo modules`
`make[1]: Entering directory `/usr/src/linux-headers-3.2.0-4-versatile'`
`  CC [M]  /root/kernelinfo/kernelinfo.o`
`  Building modules, stage 2.`
`  MODPOST 1 modules`
`  CC      /root/kernelinfo/kernelinfo.mod.o`
`  LD [M]  /root/kernelinfo/kernelinfo.ko`
`make[1]: Leaving directory `/usr/src/linux-headers-3.2.0-4-versatile'`

Upon digging, it seems that the handling of temporary values is compiler dependent [Reference: C++ Error: lvalue required as unary '&' operand](https://stackoverflow.com/questions/30187682/c-error-lvalue-required-as-unary-operand). Apparently, some compilers keep a copy of temporary values (and may be that's why the previous cases had passed).

SUCCESS: For ARM. Will try PPC and report how it goes.

**Comment by anafsah** [comment]
Hi Andrew. Thank you for the heads up. I tried the fix for #506 . It is picking up the values correctly. But now, I then got a different set of errors.

`make -C /lib/modules/3.2.0-4-versatile/build M=/root/kernelinfo modules`
`make[1]: Entering directory /usr/src/linux-headers-3.2.0-4-versatile'`
`  CC [M]  /root/kernelinfo/kernelinfo.o`
`/root/kernelinfo/kernelinfo.c: In function ‘init_module’:`
`/root/kernelinfo/kernelinfo.c:179:70: error: lvalue required as unary ‘&’ operand`
`/root/kernelinfo/kernelinfo.c:197:75: error: lvalue required as unary ‘&’ operand`
`make[4]: *** [/root/kernelinfo/kernelinfo.o] Error 1`
`make[3]: *** [_module_/root/kernelinfo] Error 2`
`make[2]: *** [sub-make] Error 2`
`make[1]: *** [all] Error 2`
`make[1]: Leaving directory /usr/src/linux-headers-3.2.0-4-versatile'`
`make: *** [all] Error 2`

Upon checking it seemed that `current` (used in line 179 and 197) is a temporary value. 
`printk(KERN_INFO "task.current_task_addr = %llu\n", (u64)(uintptr_t)&current);`
So, I just prepended current with '*current' which makes is `&*current` not. And it compiled successfully.

`root@debian-armel:~/kernelinfo# make`
`make -C /lib/modules/3.2.0-4-versatile/build M=/root/kernelinfo modules`
`make[1]: Entering directory /usr/src/linux-headers-3.2.0-4-versatile'`
`  CC [M]  /root/kernelinfo/kernelinfo.o`
`  Building modules, stage 2.`
`  MODPOST 1 modules`
`  CC      /root/kernelinfo/kernelinfo.mod.o`
`  LD [M]  /root/kernelinfo/kernelinfo.ko`
`make[1]: Leaving directory /usr/src/linux-headers-3.2.0-4-versatile'`

Upon digging, it seems that the handling of temporary values is compiler dependent [Reference: C++ Error: lvalue required as unary '&' operand](https://stackoverflow.com/questions/30187682/c-error-lvalue-required-as-unary-operand). Apparently, some compilers keep a copy of temporary values (and may be that's why the previous cases had passed).

SUCCESS: For ARM. Will try PPC and report how it goes.

**Comment by AndrewFasano** [comment]
Thanks for the feedback. We'll try to fix that in the PR and then merge it soon!

**Comment by anafsah** [comment]
Hi Andrew. Make fails for PPC because of `current_task`.

```
root@debian-powerpc:~/kernelinfo# make
make -C /lib/modules/3.2.0-4-powerpc/build M=/root/kernelinfo modules
make[1]: Entering directory `/usr/src/linux-headers-3.2.0-4-powerpc'
  CC [M]  /root/kernelinfo/kernelinfo.o
/root/kernelinfo/kernelinfo.c: In function ‘init_module’:
/root/kernelinfo/kernelinfo.c:181:71: error: ‘current_task’ undeclared (first use in this function)
/root/kernelinfo/kernelinfo.c:181:71: note: each undeclared identifier is reported only once for each function it appears in
make[4]: *** [/root/kernelinfo/kernelinfo.o] Error 1
make[3]: *** [_module_/root/kernelinfo] Error 2
make[2]: *** [sub-make] Error 2
make[1]: *** [all] Error 2
make[1]: Leaving directory `/usr/src/linux-headers-3.2.0-4-powerpc'
make: *** [all] Error 2
```
