### ISSUE TITLE
collect_code plugin crashes with malloc() error

### ISSUE THREAD

**Issue by janbbeck** [panda-re/panda#574]
I tried to use the collect_code plugin, and it just crashed with an error
```
./panda-system-x86_64 -m 4096 -replay ch32_1char -os linux-64-ubuntu -panda osi -panda osi_linux:kconf_group=ubuntu:5.3.0-28-generic:64 -panda collect_code
```
results in
```
PANDA[core]:os_familyno=2 bits=64 os_details=ubuntu
PANDA[osi_linux]:adding argument kconf_group=ubuntu:5.3.0-28-generic:64.
PANDA[core]:initializing osi
PANDA[core]:loading required plugin osi_linux
PANDA[core]:initializing osi_linux
PANDA[osi_linux]:W> kernelinfo bytes [20-23] not read
PANDA[osi_linux]:W> kernelinfo bytes [124-127] not read
PANDA[core]:/home/jan/Downloads/panda/panda/scripts/panda/build/x86_64-softmmu/panda/plugins/panda_osi_linux.so already loaded
PANDA[core]:initializing collect_code
loading snapshot
... done.
opening nondet log for read :	./ch32_1char-rr-nondet.log
malloc(): corrupted top size
Aborted (core dumped)
```
This system is not using llvm, but gcc (Ubuntu too new). To test if that is the issue, I spun up another machine with an older ubuntu and when using llvm, the result is the same, except that the text
```
opening nondet log for read :	./ch32_1char-rr-nondet.log
malloc(): corrupted top size
Aborted (core dumped)
```
changes to
```
opening nondet log for read :	./ch32_1char-rr-nondet.log
Aborted (core dumped)
```
There is only one call to malloc in the plugin, fwiw.

```
bb.code = (uint8_t *) malloc(bb.size);
panda_virtual_memory_read(env, pc, bb.code, bb.size);
```

**Comment by AndrewFasano** [comment]
Hey, this is a fairly new plugin so it's not as stable as it should be, sorry. I think I'm able to reproduce this issue (or at least some other issue causing a segfault in this plugin) with just
```
panda-system-i386 -replay my_replay -panda collect_code
```
I'll investigate and hopefully have a fix shortly

**Comment by AndrewFasano** [comment]
That was surprisingly quick- the plugin is assuming you've set a pandalog file with `-pandalog some_name` and when you don't it fails. Can you try running with that argument and see if your crash goes away?

I'll update the plugin to print an error instead of segfaulting.

**Comment by janbbeck** [comment]
That was fast! Thanks!
yeah, that worked. Also, interestingly, when running panda compiled with gcc-9, I get better warnings as to what went wrong:
```
opening nondet log for read :	/media/jan/80669BBB669BB080/ch34_1char-rr-nondet.log
panda-system-x86_64: /home/jan/Downloads/panda/panda/scripts/panda/panda/src/plog-cc.cpp:272: void PandaLog::write_current_chunk(): Assertion `this->chunk.zbuf != NULL' failed.

```
but maybe I just enabled more warnings when doing configure ?

**Comment by AndrewFasano** [comment]
Glad to hear it. I'll merge the fix shortly.

And that is interesting. I bet the newer compiler is somehow making the first error non-fatal (plog-cc.cpp:266) and then it makes it far enough to hit an assert with an actual error message.
