### ISSUE TITLE
memsavp: make new dump every so often automatically?

### ISSUE THREAD

**Issue by hanetzer** [panda-re/panda#581]
Searching for keyfiles in a memory dump. Pretty sure they're volatile and leave
memory as fast as possible, so doing memdumps every percent or so. However,
it starts me back at 1.00% each time, so each dump the wait gets longer. Perhaps
there's some option I'm not seeing or I'm using it wrong, but this could get painful
fast.

**Comment by AndrewFasano** [comment]
The best approach here might be for you to just modify the memsavep function directly since this seems like this is part of a one-off analysis. You could just modify the code at 
https://github.com/panda-re/panda/blob/b43d37df73e8766859508a141919595eb216f629/panda/plugins/memsavep/memsavep.c#L52-L55
to run the `dump_memory()` function every time the percentage increments and then just make it generate unique output filenames.

If you know anything about the keyfile (e.g., a specific header string or some system calls that will be issued around when it's in memory), you could look at some of the other plugins (e.g., stringsearch + scissors) and try reducing the length of your recording to a shorter period where the data of interest is in memory.

**Comment by hanetzer** [comment]
Yeah, I've been tinkering with file_taint and tainted_instr as well. Once again, while I have a person
looking at this, is there *somewhere* folks can chat about this? #panda-re on freenode exists, fairly
sure it may be the official one since @moyix set the topic, but I've not seen a single soul speak in
the time I've been in there (other than me). Reason I ask is some of the instructions in the readme's
seem either incomplete or out of date.

**Comment by hanetzer** [comment]
Anyways. I've figured some more stuff out via trial and error (currently using the docker image
since I can't get llvm33 to build on my machine for the juicy extra useful plugins; that was fun
itself) and I've decided this is not the tack to take.

**Comment by m000** [comment]
Hi @hanetzer. If you know which process writes the keys, maybe a more robust approach would be to (a) enable memory callbacks when the process is scheduled, (b) use memory callbacks to log memory accesses, (c) disable callbacks when process is scheduled out to reduce runtime overhead. Good luck!

**Comment by hanetzer** [comment]
@m000 interesting. Is there any relevant documentation for this procedure?
On another note I've been looking into adapting the stringsearch code (or at
least depending on it) to create a plugin that looks for crypto signatures (eg
rsa private keys in der format usually start with the bytes '30:82' and use libssl
to verify if that blob of memory is a key (if an rsa key starts with 30:82, then the
next two bytes describe how long the key is (plus the original 30:82:xx:xx). Could
be quite useful.

**Comment by m000** [comment]
I believe the manual and the plugin README files cover everything. 

In summary:
* Use osi_linux to get the asid of the process you're interested into.
* Use PANDA_CB_ASID_CHANGED callback to notify you when the process will run.
* Use the [memory callbacks](https://github.com/panda-re/panda/blob/master/panda/docs/manual.md#memory-access) to track reads/writes for the process.

If you know which library handles the keys you're looking for, you can further reduce the granularity of your checks.
* Use osi_linux to get the asid of the process you're interested into and its memory mappings (get_libraries interface).
* Use PANDA_CB_ASID_CHANGED callback to notify you when the process will run.
* Turn on memory tracing only when the next basic block to be executed belongs to a specific library.

**Comment by hanetzer** [comment]
Well, its a windows proc, but I suppose the same process in general?

**Comment by m000** [comment]
Yes, it should be.
