### ISSUE TITLE
osi_linux init_per_cpu_offsets fails

### ISSUE THREAD

**Issue by Toizi** [panda-re/panda#582]
I am on version `07aa3078963effd1917941fdce5d112f8b9fb0bf` on an xubuntu18.04 host trying to get any of the taint examples to run.

I used the `bionic-server-cloudimg-amd64-noaslr.qcow2` image from http://panda-re.mit.edu/qcows/linux/ubuntu/1804/x86_64/ to generate a recording by booting with the following cmdline
`build/x86_64-softmmu/panda-system-x86_64 -boot c -m 4096 -hda ~/dev/qemu_disks/bionic-server-cloudimg-amd64-noaslr.qcow2 -monitor stdio`

Now when I replay the recording with
`build/x86_64-softmmu/panda-system-x86_64 -m 4096 -replay cat_test2 -os linux-64-ubuntu:4.15.0-72-generic` it loads the snapshot just fine and everything appears to be working.

However once I add the `osi` plugin, I get an assertion error
```
build/x86_64-softmmu/panda-system-x86_64 -m 4096 -replay cat_test2 -panda osi -os linux-64-ubuntu:4.15.0-72-generic
PANDA[core]:os_familyno=2 bits=64 os_details=ubuntu:4.15.0-72-generic
PANDA[core]:initializing osi
PANDA[core]:loading required plugin osi_linux
PANDA[core]:initializing osi_linux
PANDA[osi_linux]:W> kernelinfo bytes [20-23] not read
PANDA[osi_linux]:W> kernelinfo bytes [124-127] not read
loading snapshot
PANDA[osi_linux]:E:osi_linux.cpp(init_per_cpu_offsets)> Unable to update value of ki.task.per_cpu_offset_0_addr.
panda-system-x86_64: /home/user/dev/panda/panda/plugins/osi_linux/osi_linux.cpp:522: void init_per_cpu_offsets(CPUState*): Assertion `false' failed.
[1]    14961 abort (core dumped)  build/x86_64-softmmu/panda-system-x86_64 -m 4096 -replay cat_test2 -panda osi
```

Presumably the assertion fails because of the previous error
`PANDA[osi_linux]:E:osi_linux.cpp(init_per_cpu_offsets)> Unable to update value of ki.task.per_cpu_offset_0_addr.`

Is there anything I'm doing wrong?

**Comment by AndrewFasano** [comment]
I first thought the issue might be that you weren't using the kernel config for the -noaslr qcow you have, but even when I use the same kernel config, I'm able to reproduce this bug.

It looks like when go into `struct_get` to load `ki.task.per_cpu_offset_0_addr`, it's failing to read the guest's virtual memory at that address which leads to the assertion failing

https://github.com/panda-re/panda/blob/b43d37df73e8766859508a141919595eb216f629/panda/plugins/osi_linux/osi_linux.h#L52-L56

I wonder if the kernelinfo for this qcow might be incorrect... I'll keep looking into this but if anyone wants to help, I'm not the best at debugging osi

**Comment by janbbeck** [comment]
I am not familiar with your build. Did it disable kaslr or only aslr?

**Comment by AndrewFasano** [comment]
@tleek built it- I think kaslr was disabled

**Comment by janbbeck** [comment]
Ok. I asked because the problem was similar to what I saw on newer kernels before turning off kaslr.

@Toizi : Try to turn off kaslr in your guest. You have to do this before taking your kernel configuration and then again every time you boot that guest.

**Comment by AndrewFasano** [comment]
But if @Toizi is using the prebuilt qcow with KASLR disabled and a kernelinfo.conf we provided, then there shouldn't be a need to regenerate the OSI config or change KASLR settings.

Unless of course the config we provided was wrong which might be the case.

**Comment by tleek** [comment]
Hi!  OSI can't really work during boot -- there is no operating system into which to introspect.  You will have more success if you revert to the "root" snapshot which was taken after boot and after logging in to a root shell.  At that point, if you take a recording of something happening and then replay with something like asidstory you should see OSI working.  You'll have to use that kernelinfo-noaslr.conf and set -os linux-64-ubuntu:4.15.0-72-generic-noaslr

**Comment by janbbeck** [comment]
> But if @Toizi is using the prebuilt qcow with KASLR disabled and a kernelinfo.conf we provided, then there shouldn't be a need to regenerate the OSI config or change KASLR settings.
> 
> Unless of course the config we provided was wrong which might be the case.

Correct me if I am wrong, but I think the qcow has aslr disabled, not kaslr.

**Comment by Toizi** [comment]
I redid my experiment with the new `bionic-server-cloudimg-amd64-noaslr-nokaslr.qcow2` image and `kernelinfo-noaslr-nokaslr.conf` from http://panda-re.mit.edu/qcows/linux/ubuntu/1804/x86_64/bionic-server-cloudimg-amd64-noaslr-nokaslr.qcow2 and everything is working as expected now.
So I assume it had something to do with the image config. Thanks for the help
