### ISSUE TITLE
osi_linux: fails for Intel 80386 architecture

### ISSUE THREAD

**Issue by anafsah** [panda-re/panda#583]
I tried using the osi_linux plugin for i386. It loads the snapshot successfully, but then it fails at some instruction count.

```
QEMU 2.9.1 monitor - type 'help' for more information
(qemu) loading snapshot
... done.
opening nondet log for read :	./snapshot1-rr-nondet.log
RR rr_assertion `current_item' failed at /home/.../panda/panda/src/rr/rr_log.c:977
Current log point:
{guest_instr_count=340}
Next log entry type: RR_INPUT_8
Current replay point:
{guest_instr_count=337}
Aborted (core dumped)
```

**Comment by m000** [comment]
A few questions:
* Why would you categorize this as an osi_linux failure?
* Has the trace been captured with the same PANDA build you are using for replay?
* Can you compile PANDA with `-g` and provide a stack trace?

**Comment by AndrewFasano** [comment]
@anafsah Can you answer those questions and/or provide more information about the guest and commands you were running? Otherwise there's no way we'll be able to help debug this.
