### ISSUE TITLE
spotify example: tapdump missing?

### ISSUE THREAD

**Issue by hanetzer** [panda-re/panda#584]
Following along with [this](http://moyix.blogspot.com/2014/07/breaking-spotify-drm-with-panda.html), and I can't seem to locate a tapdump plugin? Was it renamed, removed, or
not ported from the old panda yet?

**Comment by AndrewFasano** [comment]
I believe it's now called [textprinter](https://github.com/panda-re/panda/blob/master/panda/plugins/textprinter/README.md) though I'm not sure why

**Comment by hanetzer** [comment]
Ah, so it is. Ok, cool beans.
