### ISSUE TITLE
panda_require'd plugin args

### ISSUE THREAD

**Issue by hanetzer** [panda-re/panda#585]
Is it possible to set the arguments for a panda_require'd plugin?
If I wanted to, for example, write a plugin expanding on stringsearch
(say an xml parser or something) I could require stringsearch with
a str parameter of '<?xml'?

**Comment by m000** [comment]
Not sure if you can make a quick hack for this. The proper way would be to use a [plugin-to-plugin call](https://github.com/panda-re/panda/blob/master/panda/docs/manual.md#plugin-plugin-interaction), either existing or one that you'll add to stringsearch plugin.

Note: This is a question. Not an issue. It's probably better to use the [PANDA mailing list](https://mailman.mit.edu/mailman/listinfo/panda-users) for questions.

**Comment by hanetzer** [comment]
True enough. Thanks for the info, however.
