### ISSUE TITLE
How do I extract a process' base address in a plugin?

### ISSUE THREAD

**Issue by janbbeck** [panda-re/panda#589]
I am writing a plugin right now and in a `PANDA_CB_BEFORE_BLOCK_EXEC` callback function I use `process = get_current_process()` to get the process name (via `process->name`).
Similarly I use the `TranslationBlock` passed to the callback function to get the address of the PC

This works well.
I also need to emit the base address of the process.  Surely that is accessible somewhere via OSI?

Thanks for taking the time to read this.

**Comment by lacraig2** [comment]
OSI has`get_libraries(cpu, current)`. This is a bit of a misnomer as it just iterates all `vm_area_structs` in a process. Included in that will be regions mapped for the process. You should be able to derive the base address of the process from that information.

See here for an example on `get_libraries`: https://github.com/panda-re/panda/blob/9efe8741d6a8d488a8b123f7ca5b64b8cf3714a6/panda/plugins/osi_test/osi_test.c#L72

**Comment by janbbeck** [comment]
Thank you for your help!
That works!

My unasked-for 2 cents:
I think I should point out that having to look up all the libraries with get_libraries() just to get the module name slows down processing by about a factor of 50 for me.
I can, of course, build a name-to-base-address cache myself - and probably will.  But as you say 'get_libraries()' is kind of a misnomer. Maybe there should be a 'get_module()'

Thanks again, you saved me a lot of time.

Jan

**Comment by m000** [comment]
@janbbeck We have partially done the work for more lightweight access to process information. We have `OsiProcHandle` which contains just enough information to get you started with retrieving information about a specific process. However, this is only used by a single API call at the moment:

```
// gets the process pointed to by the handle
OsiProc *get_process(CPUState *cpu, const OsiProcHandle *h);
```

Feel free to add a new API call for the specific piece of information you need and send a PR. E.g.
```
// gets the process pointed to by the handle
OsiProc *get_libraries(CPUState *cpu, const OsiProcHandle *h);
```

This should be only a matter of exposing the existing functions of the OSI plugins.

Also, since there is a consensus that `get_libraries()` is a misnomer, you can send a second PR renaming the call and fix all the core plugins that may use it. `get_mmaps()` or `get_mmappings()` would be more accurate I think. @lacraig2 may want to weigh-in.

**Comment by lacraig2** [comment]
@m000 I think either `get_process_mappings()` or `get_mappings()` would work best. It's OS agnostic and states exactly what you have and what you're getting.

@janbbeck If you want the base address of the program to be part of the `OsiProc` struct you can add it as a symbol you find as an offset. Shouldn't be that hard given that it's part of the same struct we look up `vm_area_structs` in. Under `task_struct` the struct `mm_struct *mm` has the member `start_code`. This is likely what you want.

https://elixir.bootlin.com/linux/v4.15/source/include/linux/mm_types.h#L420

**Comment by janbbeck** [comment]
Thank you very much for all that information! I was able to work around the need for the base addresses, and I think there are other more pressing things at the moment (Ubuntu 20.04 support) that I want to work on before this.

**Comment by DOT850** [comment]
I am trying to do something similar and need the base address as well. Not having luck implementing it. It seems this would be an nice feature for Panda.

I added start_code_offset to the configuration file. Then I added start_code to the struct. Here is what I added to osi_linux.cpp:
```
void fill_osiproc(CPUState *cpu, OsiProc *p, target_ptr_t task_addr) {
    struct_get_ret_t UNUSED(err);
    memset(p, 0, sizeof(OsiProc));

    // p->asid = taskd->mm->pgd (some kernel tasks are expected to return error)
	err = struct_get(cpu, &p->start_code, task_addr, {ki.task.mm_offset, ki.mm.start_code_offset});
...
```

When I try to read p->start_code in the osi_test plugin. The memory range doesn't make sense. In addition, the ASID (pgd) value doesn't make sense either if I add a printf to check it from osi_linux.cpp.

In osi_test.c:
```
void before_block_exec(CPUState *cpu, TranslationBlock *tb) {
    OsiProc *current = get_current_process(cpu);
    if(current) {
        printf("Current process: %s PID:" TARGET_PID_FMT " PPID:" TARGET_PID_FMT "\n", current->pid > 0 ? current->name : "N/A", current->pid, current->ppid);
    } else {
        printf("Cannot get current process details.\n");
    }
    
    printf("\n");

    GArray *ps = get_processes(cpu);
    if (ps == NULL) {
        printf("Process list not available.\n");
    } else {
        printf("Process list (%d procs):\n", ps->len);
        for (int i = 0; i < ps->len; i++) {
            OsiProc *p = &g_array_index(ps, OsiProc, i);
            printf("  %-16s\t" TARGET_PID_FMT "\t" TARGET_PID_FMT "\t" TARGET_PID_FMT "\n" , p->name, p->pid, p->ppid, p->start_code);
        }
    }
...
```

I check my kernel version code to make sure the offsets look okay.
