### ISSUE TITLE
tainted_net from localhost

### ISSUE THREAD

**Issue by JackPepper** [panda-re/panda#622]
Hi !
I'm currently trying to reproduce CVE 2013-2028 (nginx server overflow) and get a list of tainted instructions from the network. To do that i'm using the taint_instructions plugin as well as tainted_net plugin. However no tainted instruction is written to my pandalog file even though I used the label_incoming_network=true option. Am I using wrongly or is there a bug of any kind ?

**Comment by AndrewFasano** [comment]
Can you post the command you're running and the output?

I believe the tainted_net plugin applies the taint labels as the traffic flows through the E1000 network card - If you're loading the page at localhost, maybe the traffic doesn't ever hit the network card? I'm not positive. Maybe try issuing the connection from your host machine and seeing if things change.

**Comment by JackPepper** [comment]
Hi !
Sorry for long delay response.
Here is the command i am running :
`/opt/panda/build/i386-softmmu/panda-system-i386 -m 4096 -netdev user,id=mynet -device rtl8139,netdev=mynet -replay /opt/snapshots/nginx -panda tainted_net:label_incoming_network=true -m 4096 -panda ida_taint2 -os windows_32_xpsp3`

It gives me the following output:
`[
{
  "pc": "18446744073709551615", 
  "instr": "18446744073709551615"
}
]`

It seems like no instruction is tainted. I will try to issue the connection from the host machine. Do you happen to have any ressource explaining how to perform such a configuration and connection from a linux to a windows host? My actual netdev configuration doesn't allow me to do that and I couldn't find how.

Also, this is a completely how of scope question, but do you happen to know if there is a way to revert this "pc" and "instr" numbers to actual assembly instruction ?

Thanks a lot

**Comment by AndrewFasano** [comment]
Can you try using the E1000 network card instead of the rtl8139 and see if that helps? I think our network taint code only handles the E1000 nic.  Also it might be worth trying to use 3gb of ram instead of 4- we're still working on a fix for #607 which is a bug in our taint system that shows up when using more than 3gb ram.

You'll have to re-generate the recording before the analysis, but if you change your command line to use `m 3G` and `-netdev user,id=mynet -device e1000,netdev=mynet` then I think things should work.

**Comment by JackPepper** [comment]
Hi @AndrewFasano 
Is there any other network card that I can use? I'm currently using windows XP 32bit as guest host and it seems that the E1000 netword card doesn't have the drivers installed. And I cannot find these drivers anywhere

**Comment by AndrewFasano** [comment]
Thanks for that tip! That will certainly help someone in the future. Next time we're updating the docs, I'll try to get that link added in there.
