### ISSUE TITLE
Base address for executable

### ISSUE THREAD

**Issue by DOT850** [panda-re/panda#623]
I am trying to do something similar as a previous issue and need the base address as well. Not having luck implementing it. It seems this would be an nice feature for Panda.

I added start_code_offset to the configuration file. Then I added start_code to the struct. Here is what I added to osi_linux.cpp:
```
void fill_osiproc(CPUState *cpu, OsiProc *p, target_ptr_t task_addr) {
    struct_get_ret_t UNUSED(err);
    memset(p, 0, sizeof(OsiProc));

    // p->asid = taskd->mm->pgd (some kernel tasks are expected to return error)
	err = struct_get(cpu, &p->start_code, task_addr, {ki.task.mm_offset, ki.mm.start_code_offset});
...
```

When I try to read p->start_code in the osi_test plugin. The memory range doesn't make sense. In addition, the ASID (pgd) value doesn't make sense either if I add a printf to check it from osi_linux.cpp.

In osi_test.c:
```
void before_block_exec(CPUState *cpu, TranslationBlock *tb) {
    OsiProc *current = get_current_process(cpu);
    if(current) {
        printf("Current process: %s PID:" TARGET_PID_FMT " PPID:" TARGET_PID_FMT "\n", current->pid > 0 ? current->name : "N/A", current->pid, current->ppid);
    } else {
        printf("Cannot get current process details.\n");
    }
    
    printf("\n");

    GArray *ps = get_processes(cpu);
    if (ps == NULL) {
        printf("Process list not available.\n");
    } else {
        printf("Process list (%d procs):\n", ps->len);
        for (int i = 0; i < ps->len; i++) {
            OsiProc *p = &g_array_index(ps, OsiProc, i);
            printf("  %-16s\t" TARGET_PID_FMT "\t" TARGET_PID_FMT "\t" TARGET_PID_FMT "\n" , p->name, p->pid, p->ppid, p->start_code);
        }
    }
...
```

I checked the kernel source to make sure the offsets look okay.

In the other thread regarding this, it was suggested to use OsiProcHandle which is populated in fill_osiprochandle. I tried this as well with no luck either:

```
static void fill_osiprochandle(CPUState *cpu, OsiProcHandle *h,
        target_ptr_t task_addr) {
    struct_get_ret_t UNUSED(err);

    // h->asid = taskd->mm->pgd (some kernel tasks are expected to return error)
    err = struct_get(cpu, &h->asid, task_addr, {ki.task.mm_offset, ki.mm.pgd_offset});
	err = struct_get(cpu, &h->start_code, task_addr, {ki.task.mm_offset, ki.mm.start_code_offset});

    // Convert asid to physical to be able to compare it with the pgd register.
    h->asid = panda_virt_to_phys(cpu, h->asid);
    h->taskd = kernel_profile->get_group_leader(cpu, task_addr);
}
```

The value stored in start_code seems to be two 32-bit uints as opposed to a 64-bit uint, so I think that value is wrong. The ASID is also wrong since it is also a very larger 32-bit value.

_Originally posted by @DOT850 in https://github.com/panda-re/panda/issues/589#issuecomment-614288734_

**Comment by AndrewFasano** [comment]
From what I understand, the prior issue was talking about implementing a more efficient way to do this. I briefly tried that myself before giving up. However, I was able to identify the base module of a function by using the following logic in OSI without adding that optimization. I did this using the python interface so I'll just share some pseduocode:

```
current = osi.get_current_process(cpu)
mappings = osi.get_libraries(cpu, current)
for proc_mapping in mappings:
    print(proc_mapping.base, proc_mapping.name)
```

From there it was pretty clear where each process was loaded.
