### ISSUE TITLE
callstack_instr: fails to work in Ubuntu 18.04 for ARM targets

### ISSUE THREAD

**Issue by bellma** [panda-re/panda#641]
The version of libcapstone on Ubuntu 18.04 (v3.0.4) doesn't classify ARM instructions well. The latest version (v4.0.1) appears to do a better job with ARM. I didn't track down when they actually resolved the issue, but I did find a bug report that may be related.

Potentially related: https://github.com/aquynh/capstone/issues/1072

Regarding panda sources, the if statement at line 353 within in callstack_instr.cpp, is never reached. Specifically, `cs_insn_group(handle, end, CS_GRP_CALL)` at line 295 is never true.

References to source code:

https://github.com/panda-re/panda/blob/master/panda/plugins/callstack_instr/callstack_instr.cpp#L295

https://github.com/panda-re/panda/blob/master/panda/plugins/callstack_instr/callstack_instr.cpp#L353

I wrote the following simple application to verify that capstone would classify
correctly. It will print "call" on success and "not call" on failure. Compiled
with `gcc -Wall -lcapstone main.c`.

```
#include <stdio.h>
#include <capstone/capstone.h>
#include <capstone/arm.h>

int main(){
    csh handle;
    unsigned char buf[4] = {0x56,0x34,0x00,0xeb}; /* BL	#0xD160 */
    int size = 4;
    cs_insn *insn;

    if (cs_open(CS_ARCH_ARM, (cs_mode)CS_MODE_LITTLE_ENDIAN, &handle) != CS_ERR_OK)
        return false;

    cs_option(handle, CS_OPT_MODE, CS_MODE_ARM);
    cs_option(handle, CS_OPT_DETAIL, CS_OPT_ON);

    cs_disasm(handle, buf, size, 0x1000, 0, &insn);

    printf("capstone version: %d.%d\n", CS_API_MAJOR, CS_API_MINOR);

    if (cs_insn_group(handle, insn, CS_GRP_CALL)) {
        printf("call\n");
    } else {
        printf("not call\n");
    }
}
```

Output on Ubuntu 18.04 (v3.0.5):
```
$ ./a.out
capstone version: 3.0
not call
```

Output with latest release (4.0.1):
```
$ ./a.out
capstone version: 4.0
call
```

**Comment by jmcarter9t** [comment]
Confirmed this issue. Some cautions:
1) Capstone built and installed from github source COULD place it in a different directory (`/usr/lib`) than the previous version of libcapstone (`/usr/lib/x86_64-linux-gnu`).  `ldconfig` and `LD_LIBRARY_PATH` and path updates are helpful.
2) Make sure both the `panda-system-arm` and all plugin modules are recompiled to pickup the new library.  `ldd` will help with each to ensure things are resolving right.

**Comment by AndrewFasano** [comment]
I added an explicit error when you try loading callstack_instr for an arm guest and your capstone version is < 4.0.0. I think that's the best fix we can do here other than building libcapstone from source which probably isn't worth it.
