### ISSUE TITLE
For Arm systems, panda_current_asid() returns an incorrect value

### ISSUE THREAD

**Issue by bellma** [panda-re/panda#668]
panda_current_asid() does not agree with the asid_changed callback. The asid_changed callback returns TTBR whereas panda_current_asid() returns `TTBR | (pc & 0x3ffc)`.

I believe line 389 of common.c should be removed (https://github.com/panda-re/panda/blob/master/panda/src/common.c#L89):
```
table |= (address >> 18) & 0x3ffc;
```

Compare with how the asid_changed callback is called: https://github.com/panda-re/panda/blob/master/target/arm/helper.c#L2591.

**Comment by AndrewFasano** [comment]
Just merged in a fix. I didn't have a great way to test it so I just assumed what you said was correct 🤞
