### ISSUE TITLE
Why is it sometimes wrong to use the parameter "-machine pc-1.0" for record,replay?

### ISSUE THREAD

**Issue by ClearLove27149** [panda-re/panda#669]
Why is it sometimes wrong to use the parameter "-machine pc-1.0" for record,replay?

record_instr_count != replay_instr_count

**Comment by AndrewFasano** [comment]
For x86, PANDA is only really tested on the `pc-i440fx-2.8` machine (used by default). I wouldn't be surprised if it would require some debugging to make record and replay work with older i386 machines.

Are you unable to use the newer machine type for some reason?
