### ISSUE TITLE
OSI Support for MIPS

### ISSUE THREAD

**Issue by AndrewFasano** [panda-re/panda#707]
OSI doesn't currently work for mips. PR #683 is a WIP trying to fix that but it's a hard problem so it deserves an issue too

**Comment by AndrewFasano** [comment]
Added MIPS support to OSI for little-endian mips in #683 and big-endian in #716 🎊

**Comment by yinfeidi** [comment]
I still want to know the specific command to run the osi-linux plugin for mips.
When I run
 ```
-panda osi -panda osi_linux:kconf_file=kernelinfo.conf,kconf_group=my_kernel_info \
    -panda osi_test > ositest.txt\
```
It throw such an error:
```
PANDA[osi_linux]:adding argument kconf_file=kernelinfo.conf.
PANDA[osi_linux]:adding argument kconf_group=my_kernel_info.
PANDA[core]:initializing osi
panda-system-mips: /home/Desktop/panda/panda/plugins/osi/os_intro.c:128: init_plugin: Assertion `!(panda_os_familyno == OS_UNKNOWN)' failed.
```

**Comment by AndrewFasano** [comment]
@yinfeidi normally OSI uses the OS name to determine the kconf_group which is why it's complaining. But since you're providing those fields, it shouldn't need it. To work around that bug, you can just set a junk value for the OS name with something like `-os linux-64-ubuntu:4.15.0-72-generic`. It needs to pass a regex and I don't recall exactly what it's checking, but I that string should work.

If you'd like, feel free to open an issue for that bug, it's gross but easy to get around which is why we haven't fixed it yet.
