### ISSUE TITLE
How to send http request from host to guest and analyze the tainted incoming network

### ISSUE THREAD

**Issue by 1wc** [panda-re/panda#723]
Hello, I want to do record-replay analyze on a webserver applicaton. After I start the server in the guest, I want to send http request from host and record how the server process it. But it seems PANDA's network related plugins must be used with config `-net nic-net user` and in that way, it is hard to request from host. Can I use `-net tap` instead? Or any other good suggestions about this issue. 
Thanks for help!

**Comment by AndrewFasano** [comment]
Hi, the discussion in #622 might help you get started. Something like `-netdev user,id=mynet -device e1000,netdev=mynet`.

You'll need to use the e1000 nic because the code to capture network traffic for recording/replay is (for now) only implemented in there.

**Comment by 1wc** [comment]
@AndrewFasano Thanks! I can close this issue now.
