### ISSUE TITLE
Callback PANDA_CB_PHYS_MEM_AFTER_WRITE sometimes receives wrong address

### ISSUE THREAD

**Issue by giomasce** [panda-re/panda#729]
Callback `PANDA_CB_PHYS_MEM_AFTER_WRITE` sometimes receive a wrong address. For example, in an execution trace of mine the following instructions appear:
```
ffffffff8d664379:  mov   qword ptr [rdi], r8                                    # 4c 89 07
ffffffff8d66437c:  mov   qword ptr [rdi + 8], r9                                # 4c 89 4f 08
ffffffff8d664380:  mov   qword ptr [rdi + 0x10], r10                            # 4c 89 57 10
ffffffff8d664384:  mov   qword ptr [rdi + 0x18], r11                            # 4c 89 5f 18
```
Since `RDI` does not change in the meantime and we do not cross a page boundary (here `RDI = ffff9c6e42fec780`), they should access four consecutive physical quadwords. However I have a plugin that dumps `PANDA_CB_PHYS_MEM_AFTER_WRITE` events, and it shows:
```
 > PHYS_WRITE match with instr_count=79, size = 8, addr=202fec780, pc=ffffffff8d664379, asid=2354fc000, in_kernel=1
 > PHYS_WRITE match with instr_count=80, size = 8, addr=1c2fec788, pc=ffffffff8d66437c, asid=2354fc000, in_kernel=1
 > PHYS_WRITE match with instr_count=81, size = 8, addr=1c2fec790, pc=ffffffff8d664380, asid=2354fc000, in_kernel=1
 > PHYS_WRITE match with instr_count=82, size = 8, addr=1c2fec798, pc=ffffffff8d664384, asid=2354fc000, in_kernel=1
```
First line is correct (I can see by dumping the memory that physical addresses `202fec780-202fec7a0` are modified), but the others receive an incorrect address (although the correct memory locations are updated).

Unfortunately I cannot share the trace publicly, but I will make it available to @AndrewFasano.

**Comment by Quentin01** [comment]
@giomasce can I ask you how many RAM your record has? 

It looks like I stumbled on a similar issue (or the same?) with my record but only with more than 3GB of RAM and it looks like the physical address sent to the callback isn't necessarily the same one given by the MMU but an "internal xlat address" used to reference where the RAM block is. 

I don't have all the details, I will investigate the issue by looking at how Panda is managing its RAM to understand what is really this "internal xlat address". 

I don't know if I will be able to get more details or fix it.

**Comment by Quentin01** [comment]
Also, could you try this diff to see if it fix your issue:

```diff
diff --git a/panda/src/cb-support.c b/panda/src/cb-support.c
index 13b946b575..9bed17e902 100644
--- a/panda/src/cb-support.c
+++ b/panda/src/cb-support.c
@@ -179,18 +179,7 @@ bool PCB(after_insn_translate)(CPUState *env, target_ptr_t pc) {
 }

 static inline hwaddr get_paddr(CPUState *cpu, target_ptr_t addr, void *ram_ptr) {
-    if (!ram_ptr) {
-        return panda_virt_to_phys(cpu, addr);
-    }
-
-    ram_addr_t offset = 0;
-    RAMBlock *block = qemu_ram_block_from_host(ram_ptr, false, &offset);
-    if (!block) {
-        return panda_virt_to_phys(cpu, addr);
-    } else {
-        assert(block->mr);
-        return block->mr->addr + offset;
-    }
+    return panda_virt_to_phys(cpu, addr);
 }

 typedef struct {
```

It looks like computing the physical address from the memory region and offset returned by `qemu_ram_block_from_host` is the issue here.

**Comment by AndrewFasano** [comment]
We recently found and fixed a bug with the taint system when > 3gb ram was in use (issue #607 and PR #654). Not sure if it's related, but it might be worth looking at since it sounds like this could be similar.

**Comment by Quentin01** [comment]
Looks related but if I'm correct, getting RAM offsets in `PANDA_CB_PHYS_MEM_AFTER_WRITE` instead of the physical address is another bug. 

I still don't know why sometimes `mr->addr` + the RAM offset isn't equal to the physical address, it happens when the guest physical address is bigger than `mr->addr + mr->size`. 

@AndrewFasano Do you have an explication for this?
