### ISSUE TITLE
With the file_taint plugin，replay will result in error “detect_infinite_loops: Assertion `false' failed”？

### ISSUE THREAD

**Issue by ClearLove27149** [panda-re/panda#742]
The output of the terminal has “cpuid with invalid ptr in EAX: vaddr=0x1 paddr=0xffffffff. Probably not a Panda Hypercall”

**Comment by ClearLove27149** [comment]
and ram is growing fast，

**Comment by AndrewFasano** [comment]
You shouldn't see the `detect_infinite_loops` error when using file taint.

The `cpuid with invalid ptr` is just a warning and normal. The large ram usage is also normal for taint (our taint analysis fundamentally needs a bunch of memory to track what's tainted). 

Can you provide the recording and command you were using to run PANDA? Also any details about the guest OS and architecture would help.
