### ISSUE TITLE
plugin-specific code included by pandalog.c

### ISSUE THREAD

**Issue by m000** [panda-re/panda#76]
Some plugin-specific code has slipped into `pandalog_print.c` and `pandalog_print.h`. This makes enabling specific plugins in  `config.panda` mandatory. Some kind of refactoring is required to remove this artificial requirement.

**Steps to reproduce.**

Disable the following plugins in `config.panda`:
- taint
- taint2
- tainted_branch
- file_taint
- ida_taint
- ida_taint2
- tainted_instr

Run `make distclean && ./build.sh` from the `qemu` directory.

Compilation of `pandalog.c` fails:

```
In file included from /home/user/panda/qemu/panda/pandalog.c:10:0:
/home/user/panda/qemu/panda/pandalog_print.h:17:22: error: unknown type name ‘Panda__SrcInfo’
 void pprint_src_info(Panda__SrcInfo *si);
                      ^
/home/user/panda/qemu/panda/pandalog_print.h:18:42: error: unknown type name ‘Panda__TaintQueryUniqueLabelSet’
 void pprint_taint_query_unique_label_set(Panda__TaintQueryUniqueLabelSet *tquls);
                                          ^
/home/user/panda/qemu/panda/pandalog_print.h:19:25: error: unknown type name ‘Panda__TaintQuery’
 void pprint_taint_query(Panda__TaintQuery *tq);
                         ^
/home/user/panda/qemu/panda/pandalog_print.h:20:35: error: unknown type name ‘Panda__TaintQueryHypercall’
 void pprint_taint_query_hypercall(Panda__TaintQueryHypercall *tqh);
                                   ^
/home/user/panda/qemu/panda/pandalog_print.h:21:28: error: unknown type name ‘Panda__TaintedBranch’
 void pprint_tainted_branch(Panda__TaintedBranch *tb);
                            ^
/home/user/panda/qemu/panda/pandalog_print.h:22:27: error: unknown type name ‘Panda__TaintedInstr’
 void pprint_tainted_instr(Panda__TaintedInstr *tb);
                           ^
/home/user/panda/qemu/rules.mak:24: recipe for target 'panda/pandalog.o' failed
```

**Comment by tleek** [comment]
Thanks Manolis for catching this.  I'll have a go at fixing tomorrow.

**Comment by tleek** [comment]
Also, thanks for osi_linux!  I am extending it to return lists of open
files and open sockets.

**Comment by m000** [comment]
@tleek No prob. A fix for this isn't urgent at all - we could all live with having to build a few extra plugins for some time. I just raised the issue so it is fixed whenever someone has the time.

Regarding linux_osi, I have already implemented fd->filename resolution in my prov_tracer branch. I intend to push the changes soon, so you may want to wait 1-2 days. I was planning to to this a bit later, but if you're interested I can rush it a bit.

Regarding the

**Comment by tleek** [comment]
You interest me strangely with this fd->filename resolution.  I saw stuff
in osi_linux.h (read_dentry_name) but that was just a teaser.  Are you
figuring out which fd's for a process are regular files via something like
the following?

a. getting task struct for the process
b. following task's files filed to get to fd_array
c. iterating over fd_array (open fds for proc)
d. for each corresponding struct file, doing
->f_path.dentry->d_inode->i_mode and testing that via, effectively
S_ISREG(mode) macro?


Here's a proposal.  I think we should expand PANDA's osi API to include a
few more fns to be provided by the os-specific implementations like
osi_linux.


// returns list of open files for this process
OsiFiles *get_process_files(CPUState *env, OsiProc *process);

// returns list of open network sockets for this process
OsiSockets *get_process_sockets(CPUState *env, OsiProc *p);


Where OsiFiles and OsiSockets are containers that look a lot like OsiProcs
and OsiModules.

OsiFile, OsiSocket would be somewhat OS-neutral, akin to OsiProc and
OsiModule


typedef struct osi_file_struct {
  char *path;
  target_ulong fd;  // assuming pretty much every OS has something
corresponding to this
  void *private;  // a pointer to struct file in linux, so we can get at
things.
};

// these are basically what's in sockaddr_in.
typedef struct osi_socket_struct {
  short family;
  unsigned short port;
  unsigned long addr;
};







On Mon, Jul 27, 2015 at 11:58 PM, Manolis Stamatogiannakis <
notifications@github.com> wrote:

> @tleek <https://github.com/tleek> No prob. A fix for this isn't urgent at
> all - we could all live with having to build a few extra plugins for some
> time. I just raised the issue so it is fixed whenever someone has the time.
>
> Regarding linux_osi, I have already implemented fd->filename resolution in
> my prov_tracer branch. I intend to push the changes soon, so you may want
> to wait 1-2 days. I was planning to to this a bit later, but if you're
> interested I can rush it a bit.
>
> Regarding the
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/moyix/panda/issues/76#issuecomment-125431500>.
>



-- 
When  I see an adult on a bicycle, I do not despair for the future of the
human race. - H. G.Wells

**Comment by m000** [comment]
Code implementation has been demand-driven. `read_dentry_name` was the first thing I needed (to resolve the library names used by processes in `fill_osimodule()`).

fd resolution works by getting the file_struct for the fd (will be NULL if not a file). Resolving the dentry of the file_struct gives you the name relative to the mount point. Then the mount point name has to be resolved until we reach / and concatenated with the dentry name to get the full-path of the file.
Since these have been implemented, getting get_process_files() to work should be straightforward.

Regarding the proposed structs, I'm not sure what the equivalent of an fd is in Windows. If it isn't a basic type, then we have some thinking to do.
Also shouldn't the socket struct contain both endpoints?

PS. Maybe we should move the thread to the list or create a new issue for extending osi functionality?
