### ISSUE TITLE
PyPanda ‘memsavep’ error in Python3

### ISSUE THREAD

**Issue by devdkerr** [panda-re/panda#772]
The memsavep python binding to libpanda fails in Python3, seemingly because the fileno() returns a file descriptor but the underlying C function expects a 'FILE *'.

I attempted a ctypes call to fdopen to dereference the file descriptor to a 'FILE *' but get a casting error where it actually returns a LP_FILE and not a 'FILE *'.

**Comment by lacraig2** [comment]
Hey @devdkerr,

Good catch. I fixed this in #774. It should be in mainline soon.

Let me know if it works for you. Thanks.
