### ISSUE TITLE
How to speed up the coverage plugin in a mips emulation

### ISSUE THREAD

**Issue by yinfeidi** [panda-re/panda#811]
When I use panda the emulate a mips router, I can trace the coverage in asid as well as osi mode. But, the emulated router responsed very slowly in osi mode while not in asid mode. I assume the OSI is costing. I wonder how to speed up the coverage pluin. Or, whether I can know the the address range of one specific program in the image so that I can use the asid mode with limiting the corresponding pc range.

**Comment by lacraig2** [comment]
It seems to me that the arguments in the coverage readme cover the options you are interested in.

There is overhead in OSI. If you believe that to be your issue you should set the mode to something other than `osi-block`. Additionally, don't set a process name and set `pc` to your relevant range.

https://github.com/panda-re/panda/blob/master/panda/plugins/coverage/README.md
