### ISSUE TITLE
Queued functions don't follow exception model for threads

### ISSUE THREAD

**Issue by lacraig2** [panda-re/panda#823]
Queued functions in the blocking thread throw exceptions instead of saving exceptions and throwing in the main thread like other functionality does.

Minimal Example

```python3
from pandare import Panda, ffi

panda = Panda(generic="arm")


@panda.queue_blocking
def setup():
    do_make_error_here_for_invalid_function()

panda.run()


```

**Comment by AndrewFasano** [comment]
Bumping this because it keeps causing me problems - @lacraig2 any chance you'll be able to fix this?

**Comment by lacraig2** [comment]
I thought I fixed that. Maybe not. I'll take another look.

**Comment by lacraig2** [comment]
This seems to be fixed.

Minimal example:

```python3

from pandare import Panda
panda = Panda(generic="x86_64")


@panda.queue_async
def run_cmd():
    call_nonexistent_function()

panda.run()
```

https://asciinema.org/a/aKFYanBi9CikqfKdt3b0gDw2e
