### ISSUE TITLE
I can't get process name when using the coverage plugin with osi-block mode

### ISSUE THREAD

**Issue by yinfeidi** [panda-re/panda#832]
Last month I downloaded the panda and it worked well using the following command:
`-os linux-64-ubuntu -panda osi -panda osi_linux:kconf_file=kernelinfo.conf,kconf_group=mips,load_now=true \
    -panda coverage:filename=coverage.csv,mode=osi-block,start_disabled=true \`
I can get the follwing info:
`(kernel),3617,3617,1,8011d31c,16
tcapi,3617,3617,0,2afc4f24,12
ifconfig,3616,3616,0,2b38b6b8,12`

Well, today I download a newer version and I noticed that there is commit a few days ago. But in the coverage.csv, there is no process name.
`(unknown),0,0,0,0x45127c,28
(unknown),0,0,0,0x459870,16
(kernel),0,0,1,0x804cd0f0,24`

The kernel and the kernelinfo are the same, and I use the same command:
`-os linux-64-ubuntu -panda osi -panda osi_linux:kconf_file=kernelinfo.conf,kconf_group=mips,load_now=true \
    -panda coverage:filename=coverage.csv,mode=osi-block,start_disabled=true \`

**Comment by AndrewFasano** [comment]
Are you running a live system or working with a recording? If it's a live system, there's a chance something has changed in the guest between your executions which is causing the difference. If you're using a recording on two versions of PANDA and getting different results, that's probably a bug. 

@nathanjackson did make some changes to the coverage plugin recently so he might have other ideas.

**Comment by nathanjackson** [comment]
Hi @yinfeidi, I think the problem is that your kernel config might be missing the task switch hook address.

See: https://github.com/panda-re/panda/blob/master/panda/plugins/osi_linux/README.md. Specifically, there is a section at the bottom of the Summary where it describes how to fill in that field.

If that doesn't fix it let me know, but I will need a replay+kernel config that can be used to reproduce the issue.

**Comment by yinfeidi** [comment]
I did add this field by searching switch_task_hook_addr in kernel source and following is the panda info in init time:
`PANDA[osi_linux]:adding argument kconf_file=kernelinfo.conf.
PANDA[osi_linux]:adding argument kconf_group=mips.
PANDA[osi_linux]:adding argument load_now=true.
PANDA[coverage]:adding argument filename=coverage.csv.
PANDA[coverage]:adding argument mode=osi-block.
PANDA[coverage]:adding argument start_disabled=true.
PANDA[core]:initializing osi
PANDA[core]:loading required plugin osi_linux
PANDA[core]:initializing osi_linux
PANDA[osi_linux]:W> kernelinfo bytes [20-23] not read
PANDA[core]:loading required plugin syscalls2
PANDA[core]:initializing syscalls2
PANDA[syscalls2]:using profile for linux mips
PANDA[core]:/home/hunter/Desktop/panda/1/panda/plugins/panda_osi_linux.so already loaded
PANDA[core]:initializing coverage
PANDA[core]:loading required plugin osi
PANDA[core]:/home/hunter/Desktop/panda/1/panda/plugins/panda_osi.so already loaded`
However there are still unknown process names. I am using linux kernel 2.6.39 in a mips device.

**Comment by nathanjackson** [comment]
I have not tested this plugin with MIPS at all, so there is a very good chance something is wrong there.

How did you use the source exactly to find the switch task hook address?

I can debug further if you can provide a guest image.

**Comment by yinfeidi** [comment]
After I compile the kernel I can get the file 'System.map' in the output dir. I use the kernel in [firmadyne](https://github.com/firmadyne/kernel-v2.6) project. And I just use panda to trace the emulated mips firmware.

**Comment by nathanjackson** [comment]
I really need some sort of minimal example that doesn't require me to go setup my own guest. If you can provide a guest image, kernelinfo, and the command you used to run PANDA, I will try to see what's wrong with it. Otherwise, I won't be able to help.

**Comment by yinfeidi** [comment]
I upload my running environment [here](https://drive.google.com/file/d/1SkugUt_Ws2_nFyZnnb0YKdmQsylH7wj0/view?usp=sharing). You can check the kernelinfo and my kernel in this directory.

**Comment by nathanjackson** [comment]
@yinfeidi I just had a chance to look, but it looks like your tarball is corrupt.

**Comment by nathanjackson** [comment]
I also just put in a PR that fixes something possibly related to your issue, but I'm not 100% sure.

https://github.com/panda-re/panda/pull/838

**Comment by yinfeidi** [comment]
Sorry, the new commit doesn't help, and [this](https://drive.google.com/file/d/1_9QXGdIEEnlGKw3Q8PYUUHOfGMN6-2q9/view?usp=sharing) is no-corrupt running env.

**Comment by nathanjackson** [comment]
Great! I was able to reproduce the issue, but it looks like I might need to lean on the PANDA Slack channel to help me out. I know basically nothing about MIPS and I think the issue is with how the current process is obtained for MIPS.

I think what's going on is that when the task change notification fires, we're still in kernel mode. For some reason, it looks like the code won't let me obtain the current task in kernel mode on MIPS, but I haven't totally verified this yet. Before I made my recent changes, we were querying OSI on every single block but this has a lot of overhead. My goal was to optimize this by only running the OSI calls when they're actually needed (after a context switch or execve).

**Comment by nathanjackson** [comment]
I actually think there might be a few things going on. It looks like for some reason the TCG optimizer is removing the task change notification call in MIPS but not X86. This means that the function to update the current process info never runs. I will investigate this issue further, it seems like it could affect more than just MIPS and I just got lucky that it worked for X86.

However, I think if I fix this we'll still have an issue where we can't retrieve the current process on MIPS while in kernel mode. I'm not sure if I will be able to fix this or not.

**Comment by nathanjackson** [comment]
@yinfeidi I just submitted a new PR that I think at least partially fixes the issue: https://github.com/panda-re/panda/pull/842. I think the issue existed on X86 and other architectures but at least on X86, we got lucky it wasn't an issue.

However, while debugging I was reading the osi_linux MIPS guest code and it led me to believe there is another issue: you can't currently get an accurate current process while in kernel-mode, which is where the task change notification is executed. While my PR seems to at least partially fix the issue you ran into, I can't currently vouch for the accuracy of the process names\IDs that are reported.

Could you try the new branch on #842 and let me know if the reported process name\PID\TID is seems correct?

**Comment by yinfeidi** [comment]
Thx, it works and I can get process info, but I don't know if the process info is correct. And I don't know the difference between the unmodified osi_linux plugin and the recent modified one. Which is more accurate and which has less overhead?

**Comment by nathanjackson** [comment]
I would expect the new way of doing things with `coverage` and `osi_linux` to be faster, it is on X86 but it is also accurate.

The now problem lies in whether or not we can obtain the correct current process for MIPS while in kernel mode. Maybe @lacraig2 or @AndrewFasano have thoughts about the current process accuracy when in kernel mode?

**Comment by AndrewFasano** [comment]
I think it should work, but I haven't tested it too much. OSI uses a cached value for the r28 when the guest was last in kernel mode (code [here](https://github.com/panda-re/panda/blob/7e266b57708ad04c2adad272bd57bbe752cefce9/panda/plugins/osi_linux/default_profile.cpp#L24-L28)). When writing that, I assumed even in kernel mode r28 should always be a valid pointer to the current task struct. If that's not the case, we should probably change [this function](https://github.com/panda-re/panda/blob/1e18bc3be0d3f6c2da5966b8ca088a5c8925c2f7/panda/plugins/osi_linux/osi_linux.cpp#L629-L639) to update `last_r28` only when switching from kernel to usermode.
