### ISSUE TITLE
panda-system-x86_64: Not a migration stream

### ISSUE THREAD

**Issue by BinaryWarlock** [panda-re/panda#843]
Using the pandare/panda Docker image. Ran `panda-system-x86_64 ...` and attached a monitor, ran `begin_record foo` and `end_record`, then ran `panda-system-x86_64 ... -replay foo`, then got:

```loading snapshot
panda-system-x86_64: Not a migration stream
Failed to load vmstate
Failed to start replay
```

What am I doing wrong?

**Comment by BinaryWarlock** [comment]
This still happens with the latest HEAD, any ideas on how to troubleshoot it? What does `Not a migration stream` mean exactly?

**Comment by BinaryWarlock** [comment]
@AndrewFasano Yeah, so I'm doing this to record:
```
panda-system-x86_64 -m 128m -net none \
        -cpu qemu64,fsgsbase=on \
        -drive if=pflash,format=raw,unit=0,file=/usr/share/OVMF/OVMF_CODE.fd,readonly=on \
        -drive if=pflash,format=raw,unit=1,file=./OVMF_VARS.fd \
        -hda fat:rw:/tmp/fs \
        -boot order=c \
        -chardev stdio,id=debug,mux=on \
        -serial chardev:debug \
        -monitor unix:/tmp/qemu-monitor-socket,server \
    -serial null \
    -serial chardev:cons &
    ```
    So I'm using stock OVMF firmware for UEFI, and the rest is just setting up serial ports. I then connect to the monitor socket and run `begin_record /tmp/recording`, let it run, and then exit qemu (or `end_record`).
    
 To replay I tried using the same command but with `-replay /tmp/recording`, and also a cut down version with just the `-m 128m -cpu ... -replay` and it does the same thing.
 
 Any ideas?

**Comment by AndrewFasano** [comment]
Hm, so I was able to reproduce this after installing `ovmf` from apt and running

```
panda-system-x86_64 -m 128m -net none \
  -cpu qemu64,fsgsbase=on \
  -drive if=pflash,format=raw,unit=0,file=/usr/share/OVMF/OVMF_CODE.fd,readonly=on \
  -hda fat:rw:/tmp/fs \
  -boot order=c \
  -nographic
```

Then Ctrl-A + C to switch to the monitor for `begin_record foo` and `end_record`. Then I added `-replay foo` and got the same error. I'll investigate a bit more

**Comment by AndrewFasano** [comment]
I'm not sure why this is happening, but I removed the `-hda` argument and changed the drive arguments to remove `format=raw,unit=0,` and then it started working for me.

```
panda-system-x86_64 -m 128m -net none \
  -cpu qemu64,fsgsbase=on \
  -drive if=pflash,file=/usr/share/OVMF/OVMF_CODE.fd,readonly=on \
  -boot order=c \
  -nographic
```

I've never seen the `-hda fat:` argument before so it might be hitting some unhandled code in the RR system. If you make a file system and pass it through with `-drive` you might have better luck.

**Comment by BinaryWarlock** [comment]
Thanks, that proceeds further (another issue is happening though). I'll close this for now, we can open another issue for `hda fat:` support.
