### ISSUE TITLE
How do I get virtual machine time on replay？

### ISSUE THREAD

**Issue by ClearLove27149** [panda-re/panda#844]
How do I get virtual machine time on replay？The time I get from qemu_clock_get_ns() is wrong.

**Comment by AndrewFasano** [comment]
The PANDA recording model doesn't fully model peripherals such as the qemu clock - it only records (and then replays) the data actually requested by the guest during the execution.

If you find a place in your recording where the guest is getting the time, you could read it there (either by grabbing it while executing the replay or by pulling the value out of the non-determinism log).
