### ISSUE TITLE
Website down

### ISSUE THREAD

**Issue by 0xchase** [panda-re/panda#847]
When running a basic panda python script for the first time, it prints

```
Qcow ubuntu_1604_x86.qcow doesn't exist. Downloading from https://panda-re.mit.edu. Thanks MIT!
```

Unfortunately, this download doesn't work since **https://panda-re.mit.edu/** appears to be down.

Is there a different place I can download this manually?

Also, the link to the slack channel won't work for this reason.

**Comment by AndrewFasano** [comment]
We just had a hardware failure over the holidays and are working to recover our server. Hopefully we'll have it back up tomorrow.

If it takes much longer, I'll try getting our qcows online somewhere else.

Sorry about that.

**Comment by AndrewFasano** [comment]
It's back up now, sorry again for the downtime!
