### ISSUE TITLE
Getting it started with Docker on Linux

### ISSUE THREAD

**Issue by NeuralFlux** [panda-re/panda#896]
I have been trying to get the docker container working, as mentioned in the quickstart. However, I do not understand how to begin using the framework.

Doing a `docker run` and then connecting via VNC just gives me an error saying `No bootable device.`

Otherwise, opening a bash shell by `docker exec` does not give any leads either.

I would like to know how to get started with the framework, that is, how to start recording? What is the final interface?

**Comment by AndrewFasano** [comment]
The Docker container just sets you up to run PANDA. To actually do an analysis with PANDA, you'll need a guest filesystem + kernel to emulate.

We provide a number of these at [panda.re](https://panda.re/frame.php?url=/qcows/). So you can download one of those in your container and run that. For example, to use our generic Ubuntu Bionic image and load a snapshot after boot is complete you can do:

```
$ docker pull pandare/panda
$ docker run -it pandare/panda
# wget https://panda.re/qcows/linux/ubuntu/1804/x86_64/bionic-server-cloudimg-amd64-noaslr-nokaslr.qcow2
# panda-system-x86_64 ./bionic-server-cloudimg-amd64-noaslr-nokaslr.qcow2 -nographic -m 1G -loadvm root
```

If you use the [python interface ](https://panda-re.github.io/panda.html)  this process is largely automated.

**Comment by NeuralFlux** [comment]
Thank you very much.
