### ISSUE TITLE
 panda_datatypes.h missing and can't be generated

### ISSUE THREAD

**Issue by username7778** [panda-re/panda#916]
how fix this? here is log: https://pastebin.com/8eVjUBTh

thx

**Comment by AndrewFasano** [comment]
It looks like you're trying to install the python bindings but you haven't installed the python dependencies. In particular, the error
```
    from cffi import FFI
ModuleNotFoundError: No module named 'cffi'
```
shows that you haven't installed cffi.

What script are you running? The `install_ubuntu.sh` script installs these dependencies [here](https://github.com/panda-re/panda/blob/master/panda/scripts/install_ubuntu.sh#L90) with:
 ```
python3 -m pip install pycparser "protobuf==3.0.0" "cffi>=1.14.3" colorama
```

**Comment by username7778** [comment]
its fixed had to install pypanda first than run install_ubuntu.sh. 
ok but now i have new error.
i ran make install and it says:
install -d -m 0755 "/usr/local/share/panda"
Makefile:687: *** new RPATH too long - cannot adjust .so files for installation.  Stop.
root@andre-VirtualBox:/home/andre/panda# 

i hope my questions are not to annoying since its my first hours on linux

**Comment by username7778** [comment]
hello
i open a new issue for the RPATH too long problem.
i forgot to say that i used the install_ubuntu.sh script when i got this error with the python dependencies.
install pypanda first than build panda with install_ubuntu.sh fixed it.
