### ISSUE TITLE
Protobuf Error on Build

### ISSUE THREAD

**Issue by JasonKramer525** [panda-re/panda#974]
I am trying to build panda on Ubuntu. When running 'make', I run into an error with the plog-cc file in src. I have also tried running the install_ubuntu script. I currently have version 3.4.0 of libprotoc

./plog.pb.h:182:10: error: ‘PROTOBUF_CONSTEXPR’ does not name a type; did you mean ‘PROTOBUF_CONSTEXPR_VAR’?
  182 |   static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
      |          ^~~~~~~~~~~~~~~~~~
      |          PROTOBUF_CONSTEXPR_VAR
./plog.pb.h:389:10: error: ‘PROTOBUF_CONSTEXPR’ does not name a type; did you mean ‘PROTOBUF_CONSTEXPR_VAR’?
  389 |   static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
      |          ^~~~~~~~~~~~~~~~~~
      |          PROTOBUF_CONSTEXPR_VAR
./plog.pb.h:500:10: error: ‘PROTOBUF_CONSTEXPR’ does not name a type; did you mean ‘PROTOBUF_CONSTEXPR_VAR’?
  500 |   static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
      |          ^~~~~~~~~~~~~~~~~~
      |          PROTOBUF_CONSTEXPR_VAR
./plog.pb.h:636:10: error: ‘PROTOBUF_CONSTEXPR’ does not name a type; did you mean ‘PROTOBUF_CONSTEXPR_VAR’?
  636 |   static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
      |          ^~~~~~~~~~~~~~~~~~
      |          PROTOBUF_CONSTEXPR_VAR
./plog.pb.h:757:10: error: ‘PROTOBUF_CONSTEXPR’ does not name a type; did you mean ‘PROTOBUF_CONSTEXPR_VAR’?
  757 |   static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
      |          ^~~~~~~~~~~~~~~~~~
      |          PROTOBUF_CONSTEXPR_VAR
./plog.pb.h:868:10: error: ‘PROTOBUF_CONSTEXPR’ does not name a type; did you mean ‘PROTOBUF_CONSTEXPR_VAR’?
  868 |   static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
      |          ^~~~~~~~~~~~~~~~~~
      |          PROTOBUF_CONSTEXPR_VAR
./plog.pb.h:979:10: error: ‘PROTOBUF_CONSTEXPR’ does not name a type; did you mean ‘PROTOBUF_CONSTEXPR_VAR’?
  979 |   static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
      |          ^~~~~~~~~~~~~~~~~~
      |          PROTOBUF_CONSTEXPR_VAR
./plog.pb.h:1136:10: error: ‘PROTOBUF_CONSTEXPR’ does not name a type; did you mean ‘PROTOBUF_CONSTEXPR_VAR’?
 1136 |   static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
      |          ^~~~~~~~~~~~~~~~~~
      |          PROTOBUF_CONSTEXPR_VAR
./plog.pb.h:1305:10: error: ‘PROTOBUF_CONSTEXPR’ does not name a type; did you mean ‘PROTOBUF_CONSTEXPR_VAR’?
 1305 |   static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
      |          ^~~~~~~~~~~~~~~~~~
      |          PROTOBUF_CONSTEXPR_VAR
./plog.pb.h:1480:10: error: ‘PROTOBUF_CONSTEXPR’ does not name a type; did you mean ‘PROTOBUF_CONSTEXPR_VAR’?
 1480 |   static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
      |          ^~~~~~~~~~~~~~~~~~
      |          PROTOBUF_CONSTEXPR_VAR
./plog.pb.h:1657:10: error: ‘PROTOBUF_CONSTEXPR’ does not name a type; did you mean ‘PROTOBUF_CONSTEXPR_VAR’?
 1657 |   static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
      |          ^~~~~~~~~~~~~~~~~~
      |          PROTOBUF_CONSTEXPR_VAR
./plog.pb.h:1768:10: error: ‘PROTOBUF_CONSTEXPR’ does not name a type; did you mean ‘PROTOBUF_CONSTEXPR_VAR’?
 1768 |   static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
      |          ^~~~~~~~~~~~~~~~~~
      |          PROTOBUF_CONSTEXPR_VAR
./plog.pb.h:2050:10: error: ‘PROTOBUF_CONSTEXPR’ does not name a type; did you mean ‘PROTOBUF_CONSTEXPR_VAR’?
 2050 |   static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
      |          ^~~~~~~~~~~~~~~~~~
      |          PROTOBUF_CONSTEXPR_VAR
./plog.pb.h:2232:10: error: ‘PROTOBUF_CONSTEXPR’ does not name a type; did you mean ‘PROTOBUF_CONSTEXPR_VAR’?
 2232 |   static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
      |          ^~~~~~~~~~~~~~~~~~
      |          PROTOBUF_CONSTEXPR_VAR

**Comment by lacraig2** [comment]
I see a simliar issue in another project. https://github.com/onnx/onnx/issues/639

Which version of protobuf are you using? They recommend a different version in that thread.

**Comment by JasonKramer525** [comment]
> I see a simliar issue in another project. [onnx/onnx#639](https://github.com/onnx/onnx/issues/639)
> 
> Which version of protobuf are you using? They recommend a different version in that thread.

I think I saw that one already. I tried with both libprotoc 3.4 and 3.8 and both didn't work. I might try in an Anaconda environment next or in a VM

**Comment by AndrewFasano** [comment]
This should hopefully be fixed by #1030. If you still encounter this bug, feel free to reopen this issue!
