### ISSUE TITLE
pypanda mem_hook callbacks not being triggered

### ISSUE THREAD

**Issue by onthehub** [panda-re/panda#975]
I've seen `@panda.cb_virt_mem_after_write` trigger for an address but a corresponding `@panda.hook_virt_mem_write` or `pyperipheral` registered at that address won't fire.

**Comment by lacraig2** [comment]
Try registering an equivalent physical memory hook for that region.

**Comment by onthehub** [comment]
Yep, an equivalent physical memory hook for the address will fire.

**Comment by pcworld** [comment]
hook_virt_mem_write should be fixed by #1118.
No idea about pyperipheral; it doesn't appear to use the mem_hooks plugin, so is not covered by the above PR. From skimming the code it is used only for MMIO, were the addresses you tested it with mapped to MMIO?

**Comment by lacraig2** [comment]
Looks like this issue has been resolved.
