### ISSUE TITLE
does it support monitoring the instructions of the specified module?

### ISSUE THREAD

**Issue by notes365** [panda-re/panda#986]
Most of the time I don’t want to monitor the entire system, because there is too much noise, I only want to monitor the specified driver module/process.

If not, please support this feature when [updating qemu](https://github.com/panda-re/panda/issues/570), thanks

**Comment by AndrewFasano** [comment]
Sorry for the slow response, I wrote a reply last week but apparently I never sent it.

Yes, PANDA can certainly do that. It depends on how you wish to monitor the module/process of interest, but you have a few options.

You can register any PANDA callback, e.g., `before_block_exec` and then whenever it fires use OSI to check the current process to see if it matches the one you're interested in. Or you can get the current process mappings with OSI if you're interested in a particular module and only run your analysis if the current PC is within that module. Doing OS introspection before every block is a pretty heavy-weight approach so you would probably want to either do this on a replay or optimize it by caching the asid (and potentially module offsets) that you're interested in.

If you're just interested in collecting coverage, you can use the coverage plugin and provide a `process_name` argument. I don't think that plugin currently supports collecting coverage just for a single module within a process, but if that's what you're interested in, I imagine it would be a fairly small change.
